---
title: "Transdisciplinarity, Institutional Analysis, Adversarial Risk Analysis"
author: "Brad Venner"
date: "10/10/2025"
output: html_document
---

# Transdisciplinarity

I was trying to spell Shahid Rahman's name correctly in order to find the source of my quotation of him in my Google mail signature. (I still love the quote, but it's probably too long for an email signature and seems somewhat quaint in our increasingly adversarial times). I was reminded of my interest in Rahman's logical work by the book series *Logic, Epistemology and the Unity of Science*. This series was explicitly about renewing the unity of science movement developed by Otto Neurath. When I first looked at this title many years ago I did not know Neurath, who I now consider one of my intellectual heroes thanks to Dan O'Neill.

I stopped reading Rahman pretty early due to what I felt were excessively "syntactic" presentations of game-theoretic logic. I preferred the categorical approach to games that I was reading from Mellies. Mellies also had interesting things to say about "constructive" type theory. But I never really mastered his papers, the underlying linear logic nor the interactions between the cartesian and monoidal logics that characterized the logic. I've since revisited some of this work under the notion of the actor model, message passing, adjoint logic and session types.

The basic thesis of the series is that logic has an important role to play in the unity of science. I've preferred the idea that category theory plays this role, but it would not make sense to ignore potential contributions from philosophical logic an an *a priori* manner. Peirce developed his category theory in close contact with concerns in philosophic logic.

# Institutional analysis

The other branch of knowledge I've been reading about has been institutional analysis, broadly speaking. My interest was triggered by a passing comment on a categorical systems theory page about interest in institutional analysis and a link to Ghorbani's work. This paper 

Volume 20 of the series is on the legal system. The first chapter, available via Kindle preview on Amazon, discussed Aristotle's notion of rhetoric. Aristotle's notion of rhetoric was closely related to legal reasoning. Aristotle seemed to have a preference for rhetoric around politics (institutional design?) and less interest in the more concrete resolution of disputes between concrete persons that characterize legal systems.

I have been increasingly working on acceptance sampling problems from external consulting clients at work. I had anticipated that a main thrust of my remaining work time would be on "measurement systems", but I think that I will also have to do work on "acceptance sampling". In some ways this is an extension of measurement systems work but now with potentially conflicting understandings of the results of measurement. There is an implicit or explicit appeal to a "judge" to interpret evidence. 

A regulatory body is both an organization and functions as a "missing market institution" in monopoly regulation. But this framework doesn't seem to apply to safety regulation, where the presence of multiple actors in a market is completely consistent with killing employees or polluting the environment. What is the theory of regulation in this case? Rather than a missing market institution, we have a missing tort institution. On the other hand, Coase argued that if transaction costs are zero and property rights are "clear" (somehow existing without a legal system or enforcement, like the Star Trek episode with a virtual war with real consequences) then markets will develop the optimal solution, and both regulations and torts are there to provide a second-best solution to the market solution.

Herbert Simon' essay *Organizations and Markets* directly contested the new institutional economics that Coase founded. Simon argued that four phenomona help explain how organizations function: authority, rewards, identification and coordination.

## The imaginary as a social institution

In addition to reading Castoriadis, I've read some secondary liturature on him, particularly by Suzi Adams. She is a member of the "social imaginary collective" and wrote a book called *Castoriadis' Ontology,* which explores the turn that Castoriadis made between *Socialism or Barbarism* and *The Imaginary Institution of Society* and continued later in life. 

I must confess that this has made me way less interested in Castoriadis. I think much of my attraction is his vibrant prose, which is way more interesting than the dry ruminations of Joas or Dewey, even though I may like their ideas more.

But part of it is the somewhat mystical take on the nature of the social imaginary that is inherent in Castoriadis. My sense is that this is a limitation of his semiotics and his subsequent turn to "organicist" notions of the social. The "body" of society is organized in such a way as for the social imaginary to be passed from person to person in an organic way. Compare this to Dewey's social psychology, which is rooted in the notion of habit. The network of natural, social and cultural habits produce limits on creation and create a "world". Therefore, Dewey emphasizes the crucial role of education (as does Castoriadis) in developing the "habit of changing habits". This explicit appeal to conscious reflection as the underpinning of "creative democracy" is much more prosaic than Castoriadis' more poetic notions, but has the benefit of a potential program of action. We recognize the need for education in the "language institution" but are less skilled in education in the "imaginary institution". Perhaps it might be useful to go back to Dewey's *Art as Experience* audiobook as the social aspects of aesthetics are probably explored here.

The notion that creatures create their own lived world is also a basic assumption in biosemiotics. As Deely explains it, humans are unique in that this "world/habit" is subject to change. The Tartu/Moscow school of semiotics emphasizes semiotics as modeling. This raises a unique challenge to mathematical semiotics, since semiotic and mathematical modeling are somewhat opposed and "categorical semiotics" would have to pay respects to both notions of "model".

So traditions in pragmatics and semiotics both point to the potential for creative expansion of lifeworlds given by cultural heritage.

Adams outlines how Castoriadis began rethinking the notion of creativity in *physis* under the influence of Varela's notions of autopoeisis. She says this caused a shift from a "regional ontology of human creation* to a "general ontology of creative emergence".

## Pragma and praxis

Marxism has been called by subsequent writers a *philosophy of praxis*. 

# Adversarial risk analysis

In Lindley's paper *On the Evidence Needed to Reach Agreement Between Adversaries*, Lindley applies a decision-theoretic framework to the problem of interaction. In adversarial risk analysis, the interaction problem is reduced to a Bayesian decision problem by placing prior distributions on the behavior of the "adversary" (including whether the opponent is adversarial). I need to do some additional research, but it's not clear to me if the notion of decision includes the notion of strategy, as used in approximate dynamic programming. I seem to remember a paper about when a dynamic programming problem can be transformed into a Bayesian decision problem, and this would be a good thing to understand.

Biological paper on organization, use of Koopman operators, general modeling of an organism as performing stochastic optimization.

What are the closure rules that transform a decision problem into an optimization problem? Are there general criteria for performing this transformation? Does the notion of a "Markov" decision problem accomplish this closure? Powell wrote a new book *Reinforcement Learning and Stochastic Optimization*; a 2019 version is available online but the 2022 paid version is 380 pages longer. The new version includes a chapter on multiagent systems - may be worth it? Each section is larger - is this due to typesetting? Powell's book does address the difference between the two approaches, but doesn't declare one approach superior and looks for opportunities for bridge-building. 

Powell's chapter models single agents using the sequential decision-making framework developed in the book, and then adds a "communication" dimension. There is some structural similarity with Ghorbani's approach of "institutional modelling," which adds institutions to agent-based models.  

Revisit the development of stochastic control problems in Idris. Given the current interest in LLM-based Lean programming, could a Lean-based formulation allow for LLM-based agents to develop stochastic control models? This was Nic's insight into how LLM-based agents would use more explicit mathematical models. Can some of the crucial approximation approaches in Powell's approximate dynamic programming be formalized in Lean?

## Sequential decision, game semantics, and interaction

The sequential decision model is a quite stylized and artificial model of interaction. The strict turn-taking model ignores the basics of concurrency and the actual bombardament of any agent with possible messages received out of order, as highlighted in the actor model of concurrency. However, the sequential model can be imposed unilateraly by an agent playing against an environment or by agreement with an opponent. 

Meilles, in a paper that I'll need to dig up when I have more time, considered a variety of interaction models in his categorical game semantics. This included a more general notion of interleaving as a relation while still keeping the turn-taking sequential model.

Another class of more general interaction models are (potentially) the interaction graphs developed by Seiller. They have a paper on the "linear logic of Markov processes" that looks very interesting, but with a heavy technical background. My extremely brief and casual skim of his *Mathematical Informatics* habilitation thesis showed a very impressive program. It seemed like it could be valuable for mathematical semiotics. One thing I like about Seiller's work is that the notion of type is derived from more primitive notions of interaction. This approach is more compatible with Mari's measurement ontology, for which a property is a property of an object, and then interpreting a type as a property that is attached to some object. Perhaps this is an advantage of a more bottom-up approach to computer science rather than the top-down approach of category theory (an idea that Nic has had).

An aside. The notion of type seems like it should be compatible with the notion of "natural kinds". Since the latter were explicitly attacked as unreal in the "philosophy of ideas" (e.g. John Locke )