---
draft: true
title: "Generalized Constrained Dynamic Modeling for the Energy Transition"
author: "Bradley Venner"
date: "11/27/2025"
output: html_document
---

After looking at this more deeply, I think the specific formulation of Richter et. al. is not the best path for formalizing accounting systems. However, it probably is possible to describe power systems using classical mechanics, so it's probably possible to describe the technical system using a physical model. The REA framework is about describing "economic events" that relate the exchange of physical and economic resources between "agents". What is the relationship between these two domains? The fact that both systems could be described within a generalized Lagrangian framework   

The accounting model that describes the corresponding economic flows , in part because "hydraulic macroeconomics" is over 70 years old. However, the basic critique of static equilibrium models seems valuable and the economic modeling language should be some ability to represent underlying physical systems. But I believe that the interface between the physical and monetary systems should start at cost accounting. Are Richter's earlier effort on combining stock-flow consistent and environmentally extended input-output models more promising?   

The very name "energy transition" implies a dynamic model where a fossil-fuel based energy system is transformed into a "clean" energy system with substantially decreased greenhouse gas emissions. 

However, the institutions that govern the energy transition, such as public utility commissions, use static equilibrium models to help plan this transition.

Recent progress has been made in developing more dynamic models in economics. Surprisingly, these models are modest generalizations of the constrained dynamic models used in physics. 

This coincidence has two major advantages. First, it allows for the development of physically realistic economic models when the physics underlying the economic model can be described as a constrained dynamics problem. Second, the constrained dynamic model can be represented as a system of differential-algebraic equations. This means that these equations can be solved using existing algorithms and solvers. In particular, advances in the use of GPUs for solving such systems may allow for solution of problems of "realistic" scale as would be seen in an electrical system capacity expansion problem.

Utilities represent an algebraic constraint on goods as a function of agents. Are utility functions also a constraint on prices? Prices are "intensive" quantities as opposed to "goods" that are "extensive" quantities. There are "budget" constraints for each agent that are the dot product of the price vector with the quantity vector. There are also resource constraints over goods. 