---
title: Haskell plans
date:  2016-11-25
slug: haskell-plans
---
After wrestling with Hakyll, GitHub, *et. al.* for over a day and being unable to answer my son's question as to why I was bothering, I thought it would be a good time to write down my ambitions.  Doing so will force me to confront the distance between my current state and my intended future state.

In this Trump world, all decisions have to be revisited.  Every moment that I'm working on something must pass through this filter.  So what how will learning Haskell help bring about the post-Trump world?

I still have hope in the *categorical semiotics* project.  But what are the practical effects of the project?  One thought behind the use of Hakyll was to _eat my own dogfood_.  Writings on categorical semiotics should be written in literate Haskell (or Coq).  But it would be great to have a more practical impact.  

What sort of software would I develop if I could, and how would that be facilitated by Haskell (or functional programming more generally).  Since my background is statistics, it seems tempting to work in the data science area.  It seems like approaching both data (like the Haskell categorical databases implementation) and probability (Bart Jacob's categorical probability model) from the categorical perspective could be interesting.  But do I have time for this in a Trump world?

A broader target would be network science.  Shouldn't software to support greater democracy be based in network theory and science?  And wouldn't it be great if this network theory arose from categorical semiotics?  And why not cure cancer at the same time?     
