---
title: Kevelson on Money
author: Brad Venner
date: 2017-02-22
slug: kevelson-on-money
---
# Charles Peirce's Method of Methods

##Chapter 8:  _Money Matters:  Dollar Signs, Marks and Modes of Exchange_ 

> But to the present date there has been no examination of Simmel's _Philosophy of Money_ within the framework of modern semiotics.

> In his paper on the Economy of Research, Peirce rejects some fundamental assumptions of Bentham's economics and property, and esepcially notes the work of Jevons whose work in economics is the foundation for a new scientific method of money. I refer briefly to Jevons below; but in passing we noted that Peirce took issue with Jevon's concept of _substitutability_, a concept which Jevons incorporated in his economic theory from his logical studies, or _vice versa_.

> Peirce's point is that money is not a substitution of value, but an interpretation of value.  I.e., money is a sign, or system of signs which are in relation to an object of representation - a Representament - as Interpretant to referent sign.
