---
title: "Syllabus:  Ecology, Society,  Semiotics"
author: Brad Venner
date: 2017-08-24
---

# Motivation:  computational trinitarianism
A blog post by Robert Harper, most likely in jest.

> Trinitarianism is the central organizing principle of programming language research

# Philosophy, Mathematics, Science
Although the original trinity in was logic, category theory and computer science, 

## Philosophy

## Mathematics

## Science

# Peirce's Architechtonic

## Logic as semiotic

## Classification of the Sciences

# Categorical semiotics

## Weak categorical semiotics

### Goguen's algebraic semiotics

## Strong categorical semiotics 

Motivated by the clear family resemblance of Peirce's late semiotics and the structure of a three-category

Categorical logic founded upon topos theory - in this formulation category theory is more broad than topos theory.

Adjoint modality in a topos as foundation of physics.  Close family resemblance to Peirce's gamma graphs with a network of modalities.   

Jacobs claim for a broader categorical logic.

Ellerman's formulation of adjunction as profunctor

Brain functors

# Sustainability

The re