---
title:  Discourse ethics and the constitution
author:  Brad Venner
date:  2017-12-13
slug:  discourse-ethics-constitution
---

While listening to the oral arguments on the writ of mandamus hearing in [Juliana vs the United States](http://ourchildrenstrust.org/us/federal-lawsuit/) a couple days ago, it struck me how the basic question of how an "unenumerated" constitutional right can appear after 250 years is central to the constitutional branch of the case.  Of course, the answer is relatively simple - the ability of humanity to destabilize the climate system is relatively new, and therefore this right was not recognized until the ability to infringe it was developed.  But this means that the idea of a *universal right* must be allowed to change with time.  But then if universal rights change over time, does this mean that they are essentially contingent?  And if they are contingent, then what does that say about the Constitution?  Are there "timeless" principles in the Constitution?  If the Constitution is simply a contingent document, then why even look to it?

Now the obvious answer is that the Constition evolves, and that one of the main virtues of the Constitution is that it allows change.  One way that it changes is via the amendement process, but it also changes through the common law.  Wikipedia calls this the *living constitution* (or *loose constructionism*) theory of constitutional interpretation, and says that some members of this tradition refer to themselves as *organicists*.  But this idea is controversial.  Proponents of *natural law* appeal to an unchanging notion of nature as foundation of human morality, which in turn provides the basis for developing an unchanging constitution.  *Originalists* intend to interpret the Constitution by reconstructing the conceptual frameworks of 1781.

According to Wikipedia, [jurisprudence is the study and philosophical theory of the law](https://en.wikipedia.org/wiki/Jurisprudence).  So does it make sense to study jurisprudence broadly?  Glancing down the Wikipedia page shows lots of parallels between philosophy and jurisprudence, as would be expected.  Our Children's Trust has forced me to study jurisprudence, and my partial immersion in the legal world and the relationship between science the law, and should help me write in this area.    

Interpretation is a central concern of semiotics, so it is no suprise that Peirce's thought has had an impact on *organicism.*  

Apel's answer is to split ethics into an ideal communication community and an actual communication community.  

# Edit:  11 May 2018

Kenneth Westphal describes Hegel's social philosophy as [natural law constructivism](https://www.academia.edu/31281504/Hegel_Natural_Law_and_Moral_Constructivism).  If successful, it would overcome the opposition between *loose constructionism* and *natural law* outlined above.  Westphal discusses how Hegel tried to overcome the opposition between ontological realism and historical relativism in his epistemology, claiming Hegel as the grandfather of *pragmatic realism*.  Natural law constructivism attempts a similar reconciliation in moral philosophy.

Westphal argues that constructivism can avoid arbitrariness by basing constructions on "objective facts concerning our very finite species of embodied semi-rational agency, together with basic, pervasive features of our context of action, namely the globe we inhabit." [@Westphal:2017:Hegel], (p.3.)  Although a stable climate system capable of supporting life may be admitted as an objective fact, does the contention over the issue of anthropogenic effects show the limits of constructivism.     
