---
title: Strydom on the meta-cognitive order
date: 2017-12-24
author:  Brad Venner
slug: strydom-meta-cognitive-order
---

Piet Strydom's social theory comes as close to what I was envisioning for [Pragmatic Ecosocialism](https://github.com/bvenner/pragmatic-ecosocialism) as anyone I've read so far.  My subtitle for the project is "towards a social and political philsophy that is naturalistic, pragmatic and critical".  Strydom calls his theory *cognitive sociology*, which is based in the critical theory of Habermas and Apel, which of course implies a healthy dose of pragmatism. He has written several papers on the relationship between this theory, critical theory and pragmatism.  The term cognitive in his project is a reference to cognitive science, which is taken as a paradigmatic case of a naturalistic theory of cognition, but which also allows for a "transcendental" role for cognition.  I first encountered terms such as "left-Hegelian" and "immanent transcendence" in his work. 

In his paper [*Pragmatism and the Question of Form*](https://www.researchgate.net/publication/301222738_Pragmatism_and_the_Question_of_Form_From_a_Critical_Theory_Perspective), Strydom develops the concept of *elementary social forms*, which mediate between instinctual behaviors in animals and the socio-cultural world of modern humans.  These social forms are shared by primates, early humans, and modern humans.  This concept seems like a natural sub-layer within the notion of conventional sign as developed by Murphy, which harkens back to the notion of Ethos as developed by Aristotle.  Strydom even uses the term "second nature" to describe this concept.  This is directly analagous to Aristotle, with the map (nature -> (second nature = first society) -> society), or using the Greek terms (physios -> (second physios = first ethos) -> ethos)  analagous to (poential -> (second potential = first actuality) -> actuality).  The map between actuality and ethos is interesting, as the encounter of the ego with the non-ego seems at it's most acutely painful in it's social manifestation.

These "second nature" constraints are framed as largely negative by Strydom, but Peirce seemed to have a more charitable view of the "sentiments", particularly in his lectures *Reasoning and the Logic of Things,* where he denied a necessary link between logic and sentiment.  The 20th century certainly seemed to bear out his concern with the potential impact of logical ideas divorced from sentiment.

Recently, Strydom has been developing the applications of the concept of "limit" within social theory.  Strydom emphasizes two type of limits, the convergent sequence leading to a fixed point and the divergent sequence leading to infinite collections, with the natural numbers being the paradigm case.  Strydom traces this idea to Kant, in a formulation that I didn't really understand.  He then contrasts the identity of subjective, inter-subjective, and objective as the normative categories authenticity, rightness, truth (thought of as the cogntive "divergent" limit) and the socially embedded realization of these ideas, which he calls the cultural model, which he relates to the convergent limit.  The convergent limits correspond to ideals such as cognitively fluid subject, democratic-cosmopolitan society, and sustainable human-nature relations.   

So how does Strydom's concepts of limits correspond to the categorical ideas of limit and colimit, as developed by Lawvere, Ellerman, etc.  This is a non-trivial mapping, and it would take some development to relate the two ideas.  So it may be easier to directly develop the idea of "social limit" within category theory rather than limits in analysis.  On the other hand, there is Pavlovic's development of the idea of continuum as coalgebra, which might be a way to develop these ideas. 
