---
title: Latour and Wark
date: 2017-12-27
slug: latour-wark
---

I was looking through my old *Research* folder and saw a folder called *Algebraic Semiotics.*  Within the folder was an article that I had downloaded by Bruno Latour entitled *To modernize or to ecologize*.  I must have downloaded it while reading a Goguen paper, since he cited Latour several times.  The title caught my eye, and so I opened it and started to read.  The paper was written in 1998.  Latour followed up this paper in 2004 with the book *Politics of Nature*, which covers similar material.  In 2013, he wrote an book *An Inquiry Into Modes of Existence*, where the modernize or ecologize phrase is reused.  In 2017, an English translation of his 2015 Gifford lectures entitled *Facing Gaia* was published.  Finally, he wrote an article in Harper's called [*The New Climate*](https://harpers.org/archive/2017/05/the-new-climate/).

So clearly Latour has developed an impressive body of work on the relationship between nature and politics.  What is interesting is that "science studies" has been blamed in part for the relativization of science.  Climate deniers will repeat the same critiques of scientific knowledge that Latour made in his early years.  In the introduction to AIME, he begins with a story of a climatologist that defends his findings by citing the need to trust in the institution of science.  He claims that science studies and the scientist are on the same team, and that science studies can help the scientist understand the institution of science in order to help defend it against relativists and nihilists.

In * The New Climate* essay, Latour develops the plausible fiction that there is a common cause between climate denial and growing inequality.  In the fiction, the global elites recognize that the climate crisis was impending, and drew two conclusions:  

> Yes, this catastrophe needs to be paid for at a high price, but it’s the others who will pay, not us;

and

> we will continue to deny this undeniable truth.

Latour justifies his story as necessary, because

>Without this plausible fiction, we can’t explain the inequality, the skepticism about climate change, or the raging deregulation. 

Latour compares the situation to the *Titantic*, with the global elites making a getaway in their lifeboats and the passengers left behind howling in rage.  To thoroughly kill the metaphor, the ship is modernism, and it had become clear to the elites that the modernism project had hit its limit in the iceberg of the climate crisis.

In searching for more about Latour's project, I came across a review of *Facing Gaia* by McKenzie Wark.  
