---
title: Wage slavery and dominum
author: Brad Venner
date: 2017-04-10
slug: wage-slavery-and-dominum
---

Embedded in David Graber's [Debt: The First 5000 Years](https://www.mhpbooks.com/books/debt/) is a discussion of the origin
of the word "dominum" in Roman law.  This has an interesting parallel to Ellerman's critique of the notion that *ownership 
and governance are blent.*  According to Graber, this confusion could be traced back to the dual meaning of *dominum* when 
Roman law was re-introduced into Italy in the 12th century.  The Christian connotation of *dominum* was that of lordship 
(governance) while the Roman legal meaning was of a private property owner.  In Roman law this broked no confusion, since the
property owner exerted an absolute authority over his things - his slaves and children (wives were a joint venture between husband and father
and therefore were not exclusively under the dominum of the husband.)  

Now Ellerman criticies Marx for accepting this dual meaning from fuedalism, but we perhaps should be kinder to Marx in that
this concept has deep roots.   
