---
title:  Notes on Stakeholder Theory
date:  2017-11-14
author:  Brad Venner
---

I'm currently reading the book "Stakeholder Theory" by Freeman et. al.  In their third chapter they discuss pragmatism as a philsophical foundation for stakeholder theory but use Rorty's version of pragmatism.  This was dissapointing as I had ordered the book in part due to it's reference to pragmatism in the description.  Since "stakeholder" is a key concept in ISO 9004 (and perhaps other business excellence frameworks) I'll continue to read it as there are parts that I like, but I'd like to find an existing approach to organizations that would be as practical as the REA Framework (i.e. an approach to informations systems that helps improve practices within organizations) without some of the "capitalistic" commitments of REA (everything is a resource collapses private, social and public goods, everything is an agent collapses individuals and organizations, etc).  

Now one approach is to focus on organizational modeling.  This presumes a modeling language and an organizational theor .  How about AQL for the first and REA for the second?  Then I could pursue projects like interpreting REA within AQL.  This may help me understand how REA may be modified to be more consistent with a normative semiotic.  This would require reflection on the categorical informatics framework itself, perhaps.  Another approach would be to use Sowa's semiotics-inspired ontology within his overall first-order logic approach.  Again, it might be interesting to try to develop a conceptual-graph interpeter within AQL.

But what about a more sophisticated modeling language or ontology?  Modal HoTT for the modeling language.  But are there more sophisticated organizational theories?  Are there organizational theories that have a committment to workplace democracy, open knowledge systems, etc?  In their paper "From Stakeholders to Institutions", Mason characterizes social enterprises as better described by institutional theory than stakeholder theory.  Scott wrote a book "Institutions and Organizations," now in it's 4th edition, that tries to develop an "institutional theory" that cuts across economics, political science and law.

Another organizational theory is "critical management studies."  Hugh Willmott seems to be a major figure in this development.  In theory, this should be the shortest distance between Apel's work and organizational theory.  I liked Willmott's 2017 paper on strategic knowledge management.  However, the term "critical" seems as broad as "pragmatism," so the devil will be in the details of this work.

So my assignment is to read all three books.

Does the notion of institution collapse the customary/stipulated dimension developed by James Bernard Murphey?  If so, then is the notion of an institution the right one?  I liked the idea of building on institutional economics and pragmatism, as Mirowski recommended, but perhaps this is a less promising direction than it seemed?

The title of this project was taken as a parallel to Peirce's *The Principles of Philosophy:  Logic, Psychics and Physics," but in looking at my overall plan there seems to be a structure of phenomenology, normative science and metaphysics that corresponds to my proposed divisions of *Categorical Semiotics*, *Semiotics of Money" and "Ecology, Society, Semiotics"  
