---
title:  Notes on secondary sources for Peirce's semeiotics
author:  Brad Venner
date: 2017-11-15
slug: notes-on-secondary-sources-peirces-semeiotic
---
# T. L. Short

Short is a mystery.  No obvious presence at a university or a academic social network.  His 2007 book *Peirce's Theory of Signs* [@Short:Peirce:2007] claims to be a naturalistic theory of signs.  In his introduction he lists some alternatives, including Apel's transcendental semiotic.  So are we back to comparing transcendental philosophy to philosphical naturalism.  Are both contemporary authors bringing contemporaneous philosphical debates back to Peirce?  

Gare's speculative naturalism also calls for a naturalistic intepretation of Peirce, although given Gare's interest in Schelling, and Schelling's status within German idealism, it's not clear to me what the modification of naturalism by speculative actually results in.  Gare does criticize contemporary philosophical naturalism, so presumably if Short's analysis results in a semeiotic to close to this position, perhaps the more transcendental semiotic of Apel would be preferred.

All this brings to mind Murphy's development of the distinction natural, conventional, stipulated.  He argues that binary oppositions developed between nature and culture often collapse the third dimension.  

# Helmut Pape

In his review of Short's book (only partially available for free), he comments that he prefers a more communitarian than individualistic intepretation of Peirce.  

# Ahti Pietarinen

Seems to be moving from game-theoretic semantics to a more category-theoretic interpretation in his "DiaMind" project.  This is worth tracking.
