---
title:  Some philosophical meta-narratives
author:  Brad Venner
date:  2017-12-02
slug: some-philosophical-metanarratives
---

Perhaps it's simply the philosopher's I've chosen to read, but each one proposes a narrative of the history and purpose of philosophy, or what is called *metaphilosophy*.  Last night it was Roberto Unger's history in *The Self Awakened* [@Unger:1997:Self].  He proposes a *radical pragmatism* as the enemy of the *perennial philosophy*, the latter which he traces back to Plato but also claims is a non-Western tradition.  He doesn't claim that pragmatism is an especially important place to start, and states that the philosopher that would be closest to his viewpoint would be Nicholas of Cusa.  His arguments for beginning with a radicalized pragmatism are pragmatic:  *domesticated* pragmatism is the official philosophy of the United States, the imperial power, and it's notions are being spread throughout the world.

Unger's narrative intersects Arran Gare's narrative in a number of interesting ways.  In *The Philosophical Foundations of Ecological Civilization* [@Gare:2017:Foundations], Gare identifies a tradition of the "radical enlightenment" as a movement highly influenced by Giordano Bruno.  The Stanford Encyclopedia of Philosophy identifes Bruno as one the few followers of Nicholas of Cusa.  So perhaps there is a parallel between the radical enlightenment and radical pragmatism, and thus between the moderate enlightenment and domesticated pragmatism. 

In Gare's narrative, the radical enlightenment proceeds through Italian civic humanism to German idealism and then to British idealism and American transcendentalism.  But Gare has a parallel narrative called *speculative naturalism*, where Bruno also plays an important foundational role.  Within German idealism, Schelling is the key figure.  This idea is taken up by Peirce and then Whitehead.  Speculative naturalism is key to understanding ecological   
