---
title: Knowledge Representation Redo
author:  Brad Venner
date: 2017-12-20
slug: knowledge-representation-redo
---

In preparing for a talk I'm giving on representative sampling, it seems like a good time to defend why I spend my time reading philosophy and critical theory when I could be keeping track of the exponentially expanding literature on machine learning.  The latter would probably be better for my career and perhaps less frustrating.  Furthermore, the efforts in machine learning have led to an incredible flowering of applied Bayesian probability.  But I believe that my original encounter with Peirce was motivated by work in understanding the concept of representation, mediated through the work of John Sowa on knowledge representation.  But before this there was the objective Bayesianism of Jaynes, who called probability theory "the logic of science".  Peirce's scientific logic was undoubtedly richer and more philosophically grounded than Jaynes, but Peirce was a noted sceptic of Laplace's early 'objective Bayesianism.'  It also became clear to me that probability as logic was grounded in propositional logic.  Peirce's later analysis of probability seemed to depend upon understanding his later semiotics, as he applied his modal categories to probability resulting in actuality, potentiality and necessary aspects of this single concept.  Furthermore, Peircean semiotics seemed fundamentally to be about representation.  So this was one motivation.

Now my graduate degree was in environmental risk assessment, and my job after graduate school was in environmental enforcement.  I was never comfortable with risk assessment, which often seemed to be a way to rationalize a disfunctional relationship between capitalism and the environment, and an unlikely path to develop a better one.   
