---
title: Pragmatic Ecosocialism
author: Brad Venner
date:  2017-04-06
slug: pragmatic-ecosocialism
---

An attempt at political philosophy based on Peirce's pragmatism.  A parallel construction to 
[pragmatic realism](https://benjamins.com/#catalog/books/bsp.55/main) as a description of Peirce's 
metaphysics.  Build upon the notion of a social-ecological system, global in scope.  Notions of wealth:
social, ecological and built.  Property as a conditional relationship on built environment but ultimately
secondary or instrumental to social and ecological wealth.  Commons asset trusts for ecological wealth.

Philosophy as a bridge between the *psychical* and *physical* sciences - a similar construction to Locke.  
Peirce's notion of philosophy as coenoscopy.  Social-ecological systems are studied by methods in the special
sciences and do not take a reductive, rationalistic approach to the subject matter.

Parallels between mind-body and social-ecological relationship.  Peirce's notion of mind as intrinsically social.  

Relationship between Peirce and Hegel.  Foundational role of Hegelianism within socialism.  Relationship between
the universal categories and dialectical materialism.  How pragmaticism addresses limitations within Hegelianism.

Relationship to "real utopias."  *Do not block the road to inquiry* as applied to social systems.  Applied semiotics
as allowing cyber-physical-social systems to develop.  Simulating real utopias to improve cyber-physical-social systems.  
Ellerman's exploitation/exploration analysis - need for multiple parallel explorations of future states.  Multi-agent systems
and agent-based simulations as related approaches to cyber-physical-social systems.  

Ecological macroeconomics as a foundational approach, but with an institutional flavor including knowledge, law, logic, etc.  
