---
title:  K.-O. Apel on reflexive foundations
date: 2017-11-15
author:  Brad Venner
slug: apel-reflexive-foundations
---
# Reflexive Foundations

I read part of an essay from K.-O. Apel yesterday (the part I could read on Google Books) where Apel outlined his arguments for a "reflexive foundations" for philosophy.  The argument was similar to his original transcendental semiotics papers, but I really liked the term "reflexive foundations."  Apel also seems to distinguish between "first philosophy" and "metaphysics"

An obvious question is whether modal homotopy type theory has the same quality, or in other words, is modal homotopy type theory a "reflexive foundation" for mathematics, or "first mathematics"?

A related question.  Can metaphysics be developed as a reflexive foundation for the natural sciences, or a "first science"?  

These questions are motivated by my sense of the mutual dependence between science, math and philosophy in the development of knowledge.  Now science and math both seem to be happy to leave normative issues to philosophy.  But is there an extended empirical inquiry that corresponds to the normative sciences?  My understanding is that critical theory places this within the "critical social sciences" or the "critical human sciences" or that German term that I can never remember.  

Come back to this post when I've gotten this book.  I requested via ILL today.

# Organization and order

I believe that it was Mirowski that talked about the mutual interaction of our concepts of natural and social order.

Yes, he called it the Durkheim-Mauss-Douglas thesis.  Thanks, Google Books!

I'd love to include the "DMD Thesis" graph from the book right here.

So the term "organization" was first applied the social order side.  It was derived from "organon" by the Midieval latin.  It seems highly likely to me that the derivation was from the use of "Organon" to describe Aristotle's logical works.  But then again "organ," which meant instrument in Greek, has both a natural sense, as organ of the body, and a social sense, such as a musical instrument.  So the same term was used for the means to produce sound and the means to hear sound.  So both ears and lyres were organs.

# Semiotic and dialectic

Reading Joseph Randell's essay [Peirce and The Socratic Tradition](http://www.iupui.edu/~arisbe/menu/library/aboutcsp/ransdell/Socratic.htm).  One of my core ideas is the "categorical dialectic" developed by Lawvere, Bell and Schreiber can be understood as "categorical semiotic."  Thus it's comforting to hear Randsell's claim that > ... there is a core of ideas in Peirce's understanding of what logic is which is similar to the core ideas implicit in the practice of Socratic dialectic.  Now Ransdell makes a very different claim than Apel in stating that this insight goes all the way back to Socrates and that Peirce is Socrates' proper heir.  This makes the still radical claims of Peirce's novel program by Apel and Deely look practically modest.  

So how does he support this claim?  He claims that Socrates' dialectics began >by conceiving of the elenchic or refutational aspect of the argumentation ... as inducing an aporia or awareness of an impasse in thought>, and then >by using the conflicting energies held in suspense in the aporia as the motivation of inquiry.>   
