---
title:  Notes on *Ecological Macroeconomic Models*
date: 2018-03-11
author:  Bradley Venner
---

Notes on [@Hardt:2017:Ecological]

If Sraffa distinguishes between the distribution of the surplus as based on political or ethical concerns, then this provides a nice distinction between *Semiotics of Value* and *Ecology, Society, Semiotics,* as the latter can concentrate on larger philosophical issues, letting this repository focus on economics and theories of value within economics.

So this paper was referenced by Verger [@verger:2018:basis].  O'Neill is associated with the Center for a Steady State Economy seems like a big-shot within ecological economics - his book *Enough is Enough* [@Deitz:2013:Enough] was made into a short documentary.  He is currently a lecturer at the University of Leeds.

Hardt is a doctoral student at the University of Leeds.

Recalling Bell's *From Absolute to Local Mathematics* [@bell:2986:absolute], he explores the negation of a negation returning to the original category but in a transformed way.  Sraffa's theory of value may to the same thing.  If marginalism was the negation of classical theories of value, then Sraffa's negation of marginalism may look like the classical theory of value, but in a transformed way.

Instead, Rezai and Stagl [@rezai:2016:ecological]
stress that ecological macroeconomics should build upon the in-
sights gained in other heterodox economic fields, such as Marxist, neo-
Ricardian, and evolutionary economics.
