---
title: Semeiotic and Dialectic
date: 2018-02-21
author:  Brad Venner
slug: semeiotic-dialectic
---
> I regard the fact that I reached the same result as he did by a process as unlike his as possible, at a time when my attitude toward him was rather one of contempt than of awe, and without being influenced by him in any discernible way however slightly, as being a not inconsiderable argument in favor of the correctness of the list.  Peirce, 1903.


So what is the relationship between Peirce's semeiotic and Hegel's dialectic?  More formally, can the modal homotopy type theory applied to Hegel's dialectical logic also be used to understand Peirce's semeiotic?  It might be useful to explore this question more informally.

Peirce's development of his tripartite division of logic into speculative grammar, logical critic and speculative rhetoric parallels the Scholastic triviuum of grammar, dialectic and rhetoric.  Pushing this analogy, we could identify Peirce's logical critic with Scholastic dialectic.  

John Kaag, in his paper *Hegel, Peirce and Royce on the Concept of Essence*
paper [@Kaag:2011:Hegel] draws the analogy between Hegel's concept of *essence* and Peirce's concept of *secondness*.  Using Schneider's interpretation of modality as adjoint functors, we can interpret secondness as a pair of adjoint functors.

Robert Stern, in his paper *  

Hegel claims that finite entities do not have “veritable, ultimate, absolute being” because they are dependent on other entities for their existence in the way that parts are dependent on other parts within a whole; and idealism consists in recognizing this relatedness between things, in a way that ordinary consciousness fails to do. (p. 24)
