---
title:  From Property to Trust
author:  Brad Venner
date:  2018-06-13
slug: from-property-to-trust
---


# Hero's Journey and Dialectics
Apel characterizes the "common philosophy" as an uneasy truce between the "objective" public sphere, conceived as a mechanistic, value-free domain, and the "subjective" private sphere, where values are a matter of individual choice.  The climate change crisis as destabilizing the balance.  

Trial as conflict between realism and individualism.  Science meeting liberal capitalism within the legal institutions formed by liberal capitalism, to question the political structures developed under liberalism.  

Property as the central concept of liberalism.  The ontology of nominalism as individuals and their properties, with relationships between individuals being ruled out.  Under this framework, "ownership and rulership are blent"  

The central concept of trust under the new paradigm.  The *ens* of the trust is managed in actuality for future generations.  Knowledge of climate as a social process that is scientific and can be trusted.  Relationships between individuals based on trust.  The beloved community. 

# Some grand narratives

## Changes in the mode of production
Marx:  Feudalism -> Capitalism -> Socialism

## Changes in ideology

Deely:  way of being -> way of ideas -> way of signs

Olesky:  naive realism -> modern nominalism -> pragmatic realism

Apel:  ontology -> epistemology -> semiotics

Wark:  feudalism -> capitalism -> vectoralism

Gare:  Neoplotinism -> mechanistic materialsim (nihilism) -> ecological civilization

## Changes in the mode of exchange

Graeber:  Oscilations between metalism and accounting

Karatani:  Gift -> Ruling and Protection -> Commodity Exchange -> "Mode D"

