---
title: Democratize, Socialize, Nationalize
author: Brad Venner
date: '2018-09-18'
slug: democratize-socialize-nationalize
---

What should the process of increasing democracy in economic matters be called?  I've gone back and forth on the title of my proposed talk on finance, from *Nationalize Finance* to *Socialize Finance* to *Democratize Finance*.  The last term now seems best due to my recent reading of John Bellamy Foster's [*The Endless Crisis*](@foster:2012:endless), which outlines the theory of monopoly-finance capital, and the presentation of Richard Werner titled [*Scientific Macroeconomics and the Quantity Theory of Credit*](@werner:2018:scientific).  Both of these works have helped fill in the cracks left in Michael Hudson's brilliant construction of the central role of debt and credit.  Hudson compares the FIRE sector (finance, insurance, real estate) to a parasite extracting life from the real economy.  The above works help clarify this relationship.

In the theory of monopoly-finance capital, there is a strong interaction between finance and monopoly, with the monopoly tendency in finance encouraging monopoly in the real economy.  The underlying engine is accumulation.  Accumulation results in decreasing wages relative to profits, leading to fewer profitable investments in the real economy, resulting in an overall economic stagnation and the increasing tendency of finance to place resources into asset growth rather than productive investments.  Given Foster's Marxist roots, it may make sense to call the counter to this process *socialization*, indicating moving in the direction from capitalism to socialism.  But the term *socialism* can be understood as *state socialism* or *democratic socialism*, and thus unqualified, "socialize" does not indicate a tendency toward decentralization and democratization.  "Democratically socialize finance" may be most clear, but doesn't ring.

A Google aside:  Wolgang Merkel wrote a paper called [*Is capitalism compatible with democracy"](@merkel:2014:capitalism).  His department (Abteilung) is called *Demokratie und Demokratisierung*.

Werner's analysis of credit creation points to three possible uses for the credit creation power of banks:  asset growth, consumption or production.  He claims that public policies can help channel this power into productive avenues.  One of his central prescriptions is a decentralized, non-profit banking system modelled in part on the German system.  Again, the emphasis is on countering centralized monopoly power in finance, which could also help decrease the tendency of finance to create monopolies.

Using the term "democratize" in the economic context implies a certain commitment to [economic democracy](https://en.wikipedia.org/wiki/Economic_democracy).  The Wikipedia page is quite interesting and polyglot, with references to Schweickart, Alperovitz, Ellerman, Henry George, and Martin Luther King.  But it also makes references to many other authors that I haven't heard of.  The excerpts from J.W. Smith's book are particularly interesting.  
