---
title: Community, Commodity, Commons
date: 2018-02-07
author:  Brad Venner
slug: com3
---
# Community, Commodity, Commons

What makes an equal exchange?  Graeber points to the gift as having a distinct history prior to exchange for money and contrasts the rich types of gift exhange with the lifeless declaration of equality of exhange.  In his telling, once exchange reaches equality it the exchange is over.  The rich social relationship "collapses" into exchange, resulting in a decoupling.  Exchange is a terminal object in a relational category?

Wark's discussion of the gift is more contemporary.  

# Vectoralism as neoliberalism

Wark's discussion of the vectoral class has a nice parallel with Mirowski's work on the rise of "information" in economics.  Wark discusses this in his chapter on Brown in General Intellects.  Wark doesn't use the term 'vectoralism' to describe the intellectual regime of obtaining property rights over signs, but it seems like Hayek's work in the economic theory of information was intended to provide such a theory.  Wark discusses the potential that a revolution in the for  

Read this and get back to this section. 
