---
title: Modeling abductive reasoning
date: 2018-07-09
author:  Brad Venner
slug: modeling-abductive-reasoning
---

Felin et. al. propose an evolutionary model where novelty corresponds to symmetry breaking in a phase space.  They call this the "frame problem," an explicit link to logic and AI. They do not make an explicit link to semiotics. [@felin:2014:economic]

Caterina and Gangle, in their *Iconicity and Abduction*, use topos theory to model abduction. 

> the core method of category theory, which lifts properties characterizing individual objects to structural properties characterizing systems of relations linking individuals to one another, helps to illuminate the creative, context-dependent and tenative nature of abductive inference.

This notion of learning as "lifting" 

David Spivak, in chapters of Seven Sketches [@spivak:2018:seven], develops general models of learning from a category-theory perspective.  Spivak also developed the idea of category theory as a mathematical model of mathematical modeling.

Peirce links abductive inference to perceptual judgements.  Deely develops the Latin view of being as first known as prior to the ens reale/ens rationis distinction, which seems to fit Peirce's model of speculative grammar prior to logical critic.  

Brandom claims that classical pragmatism was unified by an evolutionary theory of knowledge.  This meant both that cognition was *naturalized* and emerged through an evolutionary process, which is now widely accepted.  Brandom also claims that the evolutionary theory of knowledge applied to learning itself, with a population of "habits" that were selected through experience.  This latter claims sounds pretty individualistic-atomistic.
