---
title: Supersession Arguments
author:  Brad Venner
date:  2018-07-23
slug: supersession_arguments
---

Rereading Charles Taylor's short note [@taylor:2000:comment] on Jurgen Habermas' discussion of philosophy's post-Hegel development [@habermas:1999:kant].  Taylor develops the notion of 'supersession arguments':

> Taylor:where we show that there is a rational path from A to B, but not in the
reverse direction. But we have to see this path not only as a line of argument, and
not only as an actual transition, but as both together [@taylor:2000:comment], p. 4

It strikes me that "abduction" as the origination of novelty is a key component in the introduction of irreversibility in "cultural evolution."  But this requires a more complete model of cultural evolution.  Following Apel, this model should be grounded on the link between theory and practice - the need to stand in our present moment facing the future without the reassurance of 'historical necessity.'  Because of the widespread Darwinian notion of biological evolution, this isn't much of a hurdle.  The more difficult notion to justify is that reason can intervene in cultural evolution and move it in the proper direction.

So can the idea of supersession arguments be linked to abduction as a logical concept and the symmetry-breaking concept of novelty in Longo's biological and economic models of evolution.  Again, the need to develop concepts in their inter-dependent "moments" of nature, society and culture?

Aside:  what to call this?  I love "computational trinitarianism" but I'd like to ground this in the Hegelian/Peircian schema.
