---
title: Logic, Natural, and Social Philosophy Interacting in Hegel
date: 2018-05-21
author:  Brad Venner
slug: ecology-hegel
---

Alison Stone's article [@stone:2012:gender] in [@brooks:2012:hegel] argues that Hegel's natural philosophy impacted his social philosophy.  By taking an animal organism as a model for society, Hegel can justify restricting women to the domestic sphere by analogy to organs in an animal organism, which are completely specialized for the good of the whole.  She makes an interesting argument that a vegetative organism would be a more democratic model, as each portion of a plant can develop into a whole (i.e. a stem cutting can grow roots).  She argues that such analogies had been made by German "romantics" and thus were available to Hegel.

It seems obvious now that if a natural metaphor was chosen to describe society it would be 'ecology' not 'organism'.  But was this concept accessible to Hegel?  

Hegel's model of logical growth is the spiral, but "negation of negation", which results in a lifting, also results in a linear development of "the absolute".  So the result is something like a spiral path on the surface of a cone.  The result is a philosophical process that grows in a straight line.  Apel [@apel:2004:kant] points out that this standpoint corresponds to Hegel's standpoint that philosophical analysis was retrospective.  Looking backwards, this main developments along the pathway can be distinguished and the dead ends, false paths, and trampled cultures can be safely ignored.  Apel says the challenge is to develop a philosophy that can stand in the present and contribute to the needs of practical reason is essential, and thus the integration of theoretical and practical philosophy is essential.  In the same paper, Apel sketches his three post-Hegelian efforts to develop this integration as Marxism, existentialism and pragmatism (with a special shout-out for Peirce, of course).

Did Hegel bring an "organism" model to his conception of the logos, and thus his absolute?  Is the spiral growth model assumed in his logic?  Habermas argues [@habermas:1999:kant] that Hegel's development of "objective spirit" during his Jena days prior to publication of the Phenomenology of the Spirit was "detranscendalizing", but that he fell back into Kant's transcendend subject with the development of the "absolute spirit".  Given the heavily Christian influence in his philosophy, it seems that an anthropomorphic notion of the absolute spirit was inevitable.  Plus, Hegel did not have the advantage of evolutionary science.

Clearly, modern evolutionary science has shown that there are lots of dead ends in the evolutionary process.  No species can be confident that they are on the right path.  Evolutionary development clearly does not progress in the notions of a linear, straight line development, and the notion that any species was "necessary" seems discredited.

Furthermore, Hegel's association with Marxism helps discredit this notion of linear growth.  As Apel puts it [apel:2004:kant],

> the reaction against the attempts of Hegel and Marx to reduce the "ought" in favor of a supposedly dialectical necessity at work within the historical process


Can we apply the Hegelian method against Hegel?  It reminds me of people that complain about people that criticize Christianity using the moral categories used by Christianity.  Judging him against his own standard.

Modal homotopy type theory seems similar to transcendental semiotics in terms of founding the systems on a few necessary assumptions about what it even means to be a "logical system".  How is basing the notion of logic on a "topos" similar to basing the notions of ethics on "discourse" or basing the notion of "logic" on intersubjective validity of argumentation?  Were these moves by Apel an attempt to get around the "totalizing" notion of society as an organism? 
