---
title: Notes on Critique of Heaven and Earth
author: Bradley venner
date: '2018-11-24'
slug: notes-on-critique-of-heaven-and-earth
---

[*A Critique of Heaven and Earth*](https://www.giffordlectures.org/lectures/critique-heaven-and-earth) is the name of a Gifford series lecture by Arend van Leeuwen.  At times enlightening and infuriating, the lectures go through Marx's intellectual development, from his high school writings to his more mature critiques of political economy, although the latter in much less detail.  

The lectures are infuriating because it is hard to tell where Marx's writings end and van Leeuwen's paraphrases begin.  The convoluted prose could be blamed on a young author trying to develop his thoughts, but it is not clear how much van Leeuwen is to blame.

The lectures are enlightening because they help frame the central problems that Marx was wrestling with and how he came to his program.  A central thesis of the lectures comes from a quote from Marx:

> The immediate task of philosophy, which is at the service of history, once the saintly form of human self-alienation has been unmasked, is to unmask self-alienation in its unholy forms. Thus the criticism of heaven is transmuted into the criticism of earth, the criticism of religion into the criticism of right and the criticism of theology into the criticism of politics.

The notion of 'self-alienation' could be the continuing dualism between form and matter, which splits the world into a fallen creation and a heavenly eternity, inherited from Plato.  However, ecosocialism emphasizes the alienation between nature and the economy, and the process of overcoming this alienation is the development of ecosocialism.

Marx came to his critique of political economy via his analyis of Hegel's Philosphy of Right.  Hegel developed this work along the same structure as his logic, and the structure of *ethical life* consisted of the family, civil society and the state.  van Leeuwen gives Hegel credit for the development of the separation of civil society and the state as a way to overcome problems in Rousseau identification between the two concepts.  

| Latin | Greek | Hegel |
|-------|-------|-------|
| civitas | polis | family |
| societas civilis | koinonia politik\U0038 | civil society |
| res publica | ? | state |

Hegel sketches the role of the philosphy of law as reconciling the Augustinian dualism of the *city of God* (civitas Dei) and the *worldly city* (civitas terrena).  These opposites are reconciled in "the rational plane of right and law".  "Thus the reconciliation which is disclosed in the *state* as the image and acutality of reason is now something objective."

Marx perceives that Hegel's solution of identifying the concept of the state, as the reconciliation of heaven and earth, with the actual existing Germanic state, as problematic.  van Leeuwen's sketch of this process is extremely confusing, but he claims that Marx saw the problem as essentially a logical problem.  

Note that Saito's book [*Karl Marx's Ecosocialism:  Capital, Nature and the Unfinished Critique of Political Economy*](https://monthlyreview.org/product/karl_marxs_ecosocialism/) considers the same period of time in Marx's writing as van Leeuven's, and this book should be next on my 'agapistic ecosocialism' reading list.
