---
title: 2019 Mission
author: Bradley Venner
date: '2019-02-27'
slug: 2019-mission
---

On Chapo Trap House, Larry Charles relayed the story of saying 15 times a day "Borat will be a worldwide hit".  Can I formulate a similar proposition for a project that could be finished this year?

Democratic planning would be my Borat, i.e. the subject of a proposition.  Endorsed by a wide variety of thinkers I admire, this seems to be a key hurdle in both the theory and practice of democratic socialism.  It is a key theoretical distinction for democratic socialism, distinguishing it from state socialism with centralized planning. It is a key practical distinction as well, as socialists need to have a good story on why democratic planning would be superior to our current mixed public/private planning process.

So what is the predicate?  What would be the 'objective' and the 'deliverable'?  Can we think big enough?  Some possibilities would be:
 - a handbook jointly developed by DSA
 - a course designed for university study
 - a software system designed to foster democratic planning
 - a conference joining academics and activists
 - a workshop like P2P has done with top people in the field resulting in a white paper

Whatever the predicate, it should be self-reflexive.  A plan to improve democratic planning should be developed democratically.  I'm leaning towards a national level working group at DSA to serve as an incubator, as this could give it the high level visibility that such a vast project would need, an organization for which democratic planning is necessary, and some technological infrastructure to help develop the project.  However, I'd like to have DSA be a node in a larger network that is open to non-DSA'ers.

What about a predicate about a 'body of knowledge'.  This would have to be used in a somewhat tongue-in-cheek manner, as this sort of organic metaphor sounds very centralized.  But the good thing about this metaphor is that there are readily available benchmarks from other disciplines.  

What about 'Democratic Planning Association'?  Again, the danger of this metaphor would have to be recognized.  Traditional professional associations seem like a long ways away from democracy.  Actually, 'Association for Democratic Planning' (ADP) has fewer Wikipedia acronym matches.   
