---
title: Notes on Interview with NYDSA Energy Democracy  
author: Bradley Venner
date: '2019-12-06'
slug: notes-interview-nydsa-energy-democracy
---
Introductions

# PG&E discussion

## inter-chapter coordination in

Gustavo

# coalition building

## Gustavo - NY
started campaign about a year ago.  At the beginning, no one was interested.  Climate movement dominated by liberals without interest in public ownership.

Had a big kickoff for campaign.  Two tactics.  Send letters/other contacts to legislators.  Canvassing.  Split members into tables based on who their state legislators are.  Cool to see members of different organizations do organizing on their own.  Groups are doing deep powermapping in their districts.  Done lots of town halls.  People that voted for Bernie Sanders - contacted them and they added their names.  

Sunrise, XR, various other smaller groups in coalition.


## Emily - SF

Major conflicts within coalition is with CCA advocates.  What would happen to CCA if you do state takeover.  What coop model would look like in   
