---
title: Thoughts-on-real-utopias
author: Bradley Venner
date: '2019-10-22'
slug: thoughts-on-real-utopias
---

After the first day of the fiercevulnerability workshop, I read Eric Olin Wright's 2015 article on Jacobin outlining his approach to anti-capitalism [@wright:2015:anticapitalist].  Wright used the old chestnut of a two-by-two table to classify four approaches to anti-capitalism, and placed his 'real utopias' idea on the diagonal of the table, unifying 'reforming capitalism' and 'eroding capitalism'.  The two axes were 'primary target of strategy' and 'goal of strategy'.  Reforming capitalism is classified as a 'macro-political' target and a 'neutralizing harms' goal.  'Eroding capitalism' is classified as a 'micro-social' target and a 'transcending structures' goal.

Now as a dedicated Peircean, I'm used to three level classifications.  Of course, there are no shortage of three-level divisions of the social realm.  Hegel proposed the family, the market and the state.  In the next day of the workshop, Kazu proposed the Ghandian iceberg, which proposed the personal (self-transformation), the community (community uplift) and direct action (analogous to the state?).  Marie's thesis used the micro, meso and macro social levels. Piet Strydom proposed a similar three-level classification in his cognitive sociology.  

Now one way to think of the micro-level is that it is characterized by a gift economy - freely shared resources among a group of closely related people.  It seems that the 'network' outlined at the end of the workshop is intending the 'team' to achieve this micro-level intimacy.  The size of the 'workshop', with 30 people, is close to David Bohm's dialog group size.  So this might roughly be the limit of the micro-level, i.e. the largest group size that allows for face-to-face community building.   George Monbiot proposal for a politics of belonging seems to imagine rebuilding such micro-level.

Now it seems like the target dimension of a real utopia must be at least at the meso-scale, and to some extent be self-similar enough to allow for scaling to at least the nation-state level.  Thus, a 'real utopia' must take on social organizing beyond the face-to-face level.  It may be that any such structure must build upon a functioning micro-scale, but that the early human experience of the unit of production being at the same level as the unit of social organization is clearly not returning.

The reparations goal in YTBN seems very undertheorized.  While links between racism and capitalism have become increasingly mainstream (e.g. the 1619 podcast), Nancy Frasier's work, David Graeber's analyis of the links between money and colonialism, etc., the direct focus on reparations places this notion on a zero-sum finite resource allocation framework, which seems unlikely to generate the widespread unity necessary for the decarbonization transition.  Anti-capitalism without economism, i.e. targeted at capitalism as a way of life rather than as an economic system, and linking ecological, gender and racist harms, seems more valuable to me than an approach that fails to identify the systemic component, as YTBN seems to do.

But clearly 'eroding capitalism' must target capitalism as a system, not merely as an economic system.  Is it too much to place democracy as the next system, suitably theorized, such as Frega's wide view of democracy?  Frega develops democracy as a concept that could span the micro,  meso and macro levels.  Could such a view incorporate but transcend 'justice' as a central metaphor?  I'm afraid that Frega's work would not resonate with social justice warriors as presently construed.  But could I develop a 'democracy' workshop that could be as powerful as fiercevulnerability but grounded in the central notion of democracy?   
