---
title: Thoughts on Value Flow Networks
author: Bradley Venner
date: '2020-09-25'
slug: thoughts-value-flow-networks
---


Value flow networks attempt to fundamentally rethink accounting, taking it from a strictly monetary concept to a larger concept of value and flows of value.  Double-entry bookkeeping can be thought of as documenting the flows between different accounts, recording the relationship as a debit on one account and a credit in the other.  Value flows enlarge this concept from "money" to "resources."  This moves accounting from tracking strictly money to tracking other resources, and starts to resemble resource planning software.

[Mikorizal Software](http://mikorizal.org/about.html) has developed a network resource planning software that has been used to support [Sensorica's open value accounting](http://www.sensorica.co/value-networks).  Network resource planning seems to be a good fit to the "laboratory enterprise" in that EPA has a number of more-or-less independent laboratories that nevertheless need to coordinate across different activities.  The nice thing about open value accounting is that it could potentially open up the laboratory network to "citizen scientists" in the same way that Sensorica has opened up their design processes to a wide number of participants.

The [Value Flows project](https://www.valueflo.ws) is an extension of the network resource planning approach to allow for inter-operability between systems.

The Resource-Event-Actor vocabulary that underlies the

There are several applied category theory projects that seem
