---
title: Notes on Liberalism and Social Action
author: Bradley Venner
date: '2021-01-17'
slug: notes-liberalism-social-action
---
Wilkinson's paper 'Dewey's Democracy Without Politics' [@wilkinson:2012:dewey] had many interesting footnotes to Dewey's 1935 book *Liberalism and Social Action*[@dewey:1935:liberalism].  So I decided to read it directly.

I've tried previously to read two books by Dewey:  *Logic, The Theory of Inquiry* and *Theory of Valuation*.  I did not finish either one.  In contrast, I have greatly enjoyed this book, and I have learned quite a bit from his historical overview of liberal theory.

> The objection that the method of intelligence has been tried and failed is wholly aside the point, since the crux of the present situation is that it has not been tried under such conditions as now exist (p 51)

The method of intelligence as a means of social action.  Liberalism is defined as enabling the full development of the capacities of the individual.  Its present task is to take on the development of institutions that enable this development.  These include institutions that alleviate material scarcity, which is now possible in contrast to previous generations.  

Marx said something very similar in terms of the goals of socialism, and full development of the working class.  So is this Marx's liberal side?  Marx emphasizes the social nature of the means of production, while Dewey emphasizes the social nature of intelligence.  At a deep level, intelligence is the means of production, but is Dewey too sanguine about the relations of power and violence that protect the means of production, as Wilkinson accuses him of?

> As long as freedom of thought and speech is claimed as a merely individual right, it will give way, as do other merely personal claims, when it is, or is successfully represented to be, in opposition to the general welfare.

>Let me mention three changes that have taken place in one of the institutions in which immense shifts have occurred, but that are still relatively external-external in the sense that the pattern of intelligent purpose and emotion has not been correspondingly modified.

> Civilization existed for most of human history in a state of scarcity in the material basis for a humane life. Our ways of thinking, planning and working have been attuned to this fact. Thanks to science and technology we now live in an age of potential plenty. The immediate effect of the emergence of the new possibility. was simply to stimulate, to a point of incredible exaggeration, the striving for the material resources, called wealth, opened to men in the new vista. It is a characteristic of all development, physiological and mental, that when a new force and factor appears, it is first pushed to an extreme. Only when its possibilities have been exhausted (at least relatively) does it take its place in the life perspective. The economic-material phase of life, which belongs in the basal ganglia of society, has usurped for more than a century the cortex of the social body. The habits of desire and effort that were bred in the age of scarcity do not readily subordinate themselves and take the place of the matter - of course routine that becomes appropriate to them when machines and impersonal power have the capacity to liberate man from bondage to the strivings that were once needed to make secure his physical basis. Even now when there is a vision of an age of abundance and when the vision is supported by hard fact, it is material security as an end that appeals to most rather than the way of living which this security makes possible. Men's minds are still pathetically held in the clutch of old habits and haunted by old memories.

> For, in the second place, insecurity is the natural child and the foster child, too, of scarcity., Early liberalism emphasized the importance of insecurity as a fundamentally necessary economic motive, holding that without this goad men would not work, abstain or accumulate. Formulation of this conception was new.  But the fact that was formulated was nothing new. It was deeply rooted in the habits that were formed in the long struggle against material scarcity. The system that goes by the name of capitalism is a systematic manifestation of desires and purposes built up in an age of ever threatening want and now carried over into a time of ever increasing potential plenty. The conditions that generate insecurity for the many no longer spring from nature. They are found in institutions and arrangements that are within deliberate human control. Surely this change marks one of the greatest revolutions that has taken place in all human history. Because of it, insecurity is not now the motive to work and sacrifice but to despair. It is not an instigation to put forth energy but to an impotency that can be converted from death into endurance only by charity. But the habits of mind and action that modify institutions to make potential abundance an actuality are still so inchoate that most of us discuss labels like individualism, socialism and communism instead of even perceiving the possibility, much less the necessity for realizing what can and should be.

> In the third place, the patterns of belief and purpose that still dominate economic institutions were formed when individuals produced with their hands, alone or in small groups. The notion that society in general is served by the unplanned coincidence of the consequences of a vast multitude of efforts put forth by isolated individuals without reference to any social end, was also something new as a formulation. But it also 0......+0 `q57i0\4`DGO9=0RS34formulated the working princ0iple of an epoch which the advent of new forces of production was to bring to an end. It demands no great power of intelligence to see that under present conditions the isolated individual is well-nigh helpless. Concentration and corporate organization are the rule. But the concentration and corporate organization are still controlled in their operation by ideas that were institutionalized in eons of separate individual effort. The attempts at cooperation for mutual benefit that are put forth are precious as experimental moves. But that society itself should see to it that a cooperative industrial order be instituted, one that is consonant with the realities of production enforced by an era of machinery and power, is so novel an idea to the general mind that its mere suggestion is hailed with abusive epithets-sometimes with imprisonment.
