---
title:  Thoughts on Knowledge Commons and Common Knowledge
author:  Bradley Venner
date: 2021 Nov 20
---

Inverting a proposed conceptual blend should be called *to goguen*, in honor of Joseph Goguen, who rigorously analyzed this notion in his algebraic semiotics. At a less formal level, I've found this technique very valuable at a "drive-size" technique for thinking. It's pretty easy to keep track of in one's head while attentions should be largely focused on more important tasks. So far I haven't written very many of these down, but the concept of 'knowledge commons' seems extremely important to me right now and worth recording thoughts about it, even drive-time thoughts.

In an ideal world, I would reread Goguen's work on algebraic semiotics before writing any more of this essay, but I will create a debt to my future self and continue on.

The term 'knowledge commons' was probably intended to contrast with 'common knowledge', which had a much earlier use. The 'neo-institutional' understanding of the 'commons' lends the notion of 'knowledge commons' a formal and rarified sense, bringing to mind the creative ways that humans have managed natural resource commons as cataloged by Elinor Ostrom. Inverting the blend, 'common knowledge' brings to mind something of no essential value.  It's academic sense is knowledge that does not neet a citation. It's common sense is largely critical - failing to possess 'common knowledge' is a problem, attributed to individual stupidity or intransigence. But in it's logical sense, common knowledge is a relatively deep subject, formally tackled in the late 1960's using multi-modal logic (https://en.wikipedia.org/wiki/Common_knowledge_(logic)). 

Similar questions are being asked around 'social knowledge' (e.g. P2P's social knowledge economy), 'social cognition' (i.e. various attempts), 'collective intelligence' (a formulation only a neoliberal could love, eliminating any mediating community into an atomic collective), and various 'knowledge economy' discussions.

First , the main source of value now resides in knowledges that are mobilised by living labour rather than fixed capital and the routine labour of execution. [vercellone:2008:articulation, p. 8]
The latter two are capital and management, in that management can only occur on 'routine labor'. In the laboratory, 'resource management' obscures the central value of 'living labor', and treating employees as 'resources' has resulted in a twin crisis of morale and quality.

As an aside, can Taguchi's 'parameter design' and Box's 'evolutionary operations' be reconciled? Is there something like 'on-line parameter design' that is appropriate for analytical methods?a34w