---
title:  Thoughts on Citizen Science, Risk Management, Collective Intelligence, and Social Inquiry
author: Bradley Venner
date:   7/14/2021
---
Should citizen science be a central component of EPA's regulatory mission, or should it be confined to the 'research and development' side of the house?  

GovLab's paper on 'collective intelligence' points to the first concept. In this report, public problems have become so complex that the expertise necessary to solve them no longer resides within a regulatory agency. 

Does this model of collective intelligence assume

# Pragmatist theories of governance

Roberto M Unger develops his model under the moniker 'democratic experimentalism.' There are strong parallels to his work and Dewey's beyond the title, including his emphasis on ensuring agency of individuals that sounds much like Dewey's 'new individualism'. Unger has a 'market, state, society' program with markets oriented around the 'knowledge economy', the state a 'high-energy state' that can make decisions more quickly and fluidly, and the society piece providing security in the face of innovation in the market sector. My sense 
