---
title:  Notes on Imagination Unleashed
author:  Bradley Venner
date: 2021 Jul 21
---
I'm reading this as part of my project to advocate 'collective intelligence' with the 'citizen science' initiative.

Roberto Mangabeira Unger co-wrote this paper with Geoff Mulgan, author of Big Mind and in charge of something at Nesta. After discovering this paper I ended up watching a few videos of Unger co-presenting with Jeffery Sachs, which was a great comparison for Unger. I find his style a little off-putting, but when compared with Sachs I'll definitely take his passion for progressivism.  In these videos, Unger outlines his political program for a progressive alternative that is very reminiscent of Dewey in general. One contemporary update is his focus on the "knowledge economy". My sense is that his understanding is more shallow than the frameworks developed by the P2P Foundation, but this work is considerably more mainstream and it may tie into the more generic 'collective intelligence' framework, which has the benefit of being more technocratic and thus potentially more interesting to EPA higher-ups than Unger's more overtly political program (or Mackenzie Wark's Hacker's Manifesto or my democratic ecosocialist leanings).


