---
title:  Notes on Imagination Unleashed
author:  Bradley Venner
date: 2021 Oct 10
---
I'm reading this as part of my project to advocate 'collective intelligence' with the 'citizen science' initiative.

Roberto Mangabeira Unger co-wrote this paper with Geoff Mulgan, author of Big Mind and in charge of something at Nesta. After discovering this paper I ended up watching a few videos of Unger co-presenting with Jeffery Sachs, which was a great comparison for Unger. I find his style a little off-putting, but when compared with Sachs I'll definitely take his passion for progressivism.  In these videos, Unger outlines his political program for a progressive alternative that is very reminiscent of Dewey. One contemporary update is his focus on the "knowledge economy". My sense is that his understanding is more shallow than the frameworks developed by the P2P Foundation, but this work is considerably more mainstream and it may tie into the more generic 'collective intelligence' framework, which has the benefit of being more technocratic and thus potentially more interesting to EPA higher-ups than Unger's more overtly political program (or Mackenzie Wark's Hacker's Manifesto or democratic ecosocialism).

This might be one of the best outlines for the transformative potential of the knowledge economy that I have read. Although less artistic than "Hacker's Manifesto", it is more concrete and grounded, the work of an artistic lawyer rather than a lawful artist. Although it bears similarity to various P2P Foundation proposals, as the work of a single author it strikes me as slightly more coherent. 

> Another emerging set of approaches, ‘data trusts’, focus on creating legal structures to provide independent stewardship of data for the benefit of a group of organisations or people that wish to use it.71

Energy data trusts seem particularly important. 

It might be unfair to say, given my relatively shallow reading of Unger's work and my overall agreement with his project, but it seems like Unger uses a Kantian dualism between humanity, which is totally free, and a natural philosophy that is necessitarian. This seems like an unfair critique, given Unger's position against 'liberalism' in his early work in *Knowledge and Politics*.  

Vercellone's 2007 paper is great. Very in keeping with the P2P Foundation, Wark's Hacker's Manifesto and Dewey's Individualism Old and New, but with a much more explicit textual foundation in Marx's work. 

Vercellone sets the struggle as *cognitive capitalism versus the general intellect*, stating

the necessity of recognising, against the logic of capital, the increasingly collective nature of technical progress, in order to place it at the service of the increase of effective liberty of individuals and the ‘diversity of existence’, and to affirm the primacy of use-value over exchange-value. [vercellone:2007:formal, p. 31]