---
title: Thoughts on Critical Accounting
author: Bradley Venner
date: '2022-04-03'
tags:
  - semiotics-values
---

Robert Bryer's two books, *Accounting for Value* and *Accounting for History*, together make the case that Marx placed accounting at the center of the capitalist system and that accounting rules could be understood as the expression of an essential theory of value, which Bryer refers to as the accounting interpretation of Marx. 

Bryer argues that Marx's concept of socialism was something like worker co-operative firms that still operate with a capitalist accounting framework. This understanding seems close to Richard Wolff's focus on the democratic workplace as a key institution of socialism. It also seems to share some common concepts with Varoufakis' ideas in *Another Now*, at least as expressed in his interview on Current Affairs.

> All the social functions of the capitalist are now performed by salaried employees. The capitalist has no further social function than that of pocketing dividends, tearing off coupons, and gambling on the Stock Exchange [engels:1880:socialism, p 76].

On the other hand, there is the ecological economics understanding of Marx, which focuses on the 'metabolic rift' induced by capitalism. This failure to "account" for waste and circular flows of production does not seem to be directly addressed by workplace reform.

There is also Bellofiore's interpretation of Marx's value theory, based on a post-Keynesian/monetary circuit theory, which focuses on the interplay of money markets (bank capital), commodity markets and labor markets in a monetary circuit.

My intuition (guess) for the last 10 years has been that
Implementing REA within categorical database theory. 

