---
title: "Entry"
author: "Brad Venner"
date: "11/12/2022"
output: html_document
---

# Category theory for energy democracy

Ideas for application of ideas from category theory to energy democracy.

Another title could be "category theory for the energy transition", which is a much more neutral-sounding technocratic title. 

Energy democracy imagines that the energy transition is more than a shift to "clean energy" and that ideas from energy justice have an important role in guiding the energy system to a more just and human provision of energy services to everyone. 

There is also a practical side to energy democracy. The energy transition requires a fundamentally different energy architecture. The current electricity grid has few providers and many customers. The shift to renewable sources allows for a considerably more decentralized architecture, with many providers and many sources. The zero marginal cost nature of renewable generation requires a shift from a focus to providing the lowest marginal cost to reducing total system cost, challenging many of the basic assumptions that have been used to design electricity markets. The addition of storage changes the fundamental nature of electricity provision, changing the nature of the commodity from the need to instantaneously balance supply and demand to resemble more "classic" commodities, where the decisions to buy and sell are decoupled. Electricy demand can also be fundamentally changed, moving from uncoordinated demand that requires substantial generation resources to meet to a more coordinated move that can shift demand to times of greater supply.

There is no shortage of imagination at the technical level about what these new systems might look like, under names such as the "smart grid", "transactive energy", "grid modernization", etc. Many "transactive energy" proposals look to expand market-based thinking to lower grid voltages, imagining economic transactions that occur betewen "prosumers." But there is no a priori reason to restrict interactions on the grid to only economic transactions. At higher volatages, supplies that bid into provision of services in a 15 minute block essentially turn over their control systems to the ISO. At this operational scale, economic decision-making is too slow.  

While the physical design of the grid constrains the possible solutions in a hierarchical manner, the ability of communications to escape these hierarchical boundaries cannot be ignored. Widespread access to communications allows coordination between nodes that are not directly connected. This poses both risks and opportunities. Security concerns will likely push to restrict node access to local scale, while benefits from non-local coordination could potentially improve resilience and lower costs.

# What can category theory do for energy democracy?

Survey existing research within applied category theory and speculate on how these developments might be used  

Begin from areas in category theory that are developing in ways that may have potential applications to energy system modeling.

## Games, lenses, learning

General characterization of reinforcement learning as a lens (Hedges)

Stochastic optimization in dependent type theory implemented in Idris ()

## Networks, systems, dynamics, processes

Initial characterization of resistor network diagrams as categories by Fong.

Categorical systems theory as a theory of dynamical systems (Jaz Myers)

## Logic, diagrams, formal methods

Applications of category theory for software development. Can include both languages and software engineering.

## Data, ontology and knowledge representation

Model-based engineering, diagrammatic logic and views.

Representations of electric systems by Pollard.

# What can energy democracy do for category theory?

What are the current major issues in energy democracy? How are more technocratic visions of the energy transition or grid modernization modified by the need for democratization? An easier target for a review paper might be to factor the problem through grid modernization, i.e. "applied category theory for grid modernization" and "grid modernization and energy democracy", since the engineers working on grid modernization might be interested in both subjects, just maybe not all at once? The term "grid modernization" was probably invented to be vague and apolitical, so it fits as a "neutral" intermediate term.

The composite would be a special case of the general relation between category theory and democracy. Using Peirce's categories, and taking category theory as "phenomenology" (the possible, could be) and democracy as "normative science" (the contingent, would-be), this leaves actuality, i.e. metaphysics, ontology, science, the objective realm), which perhaps should not be abstracted over. Then energy democracy is one of many "sectoral" approaches within economic democracy. 

By focusing largely on the technical needs of the grid, grid modernization doesn't really mean anything in terms of future direction. It either neglects the potential for new institutional design or explicitly takes existing grid concepts as invariants (i.e. private ownership). 

Are there existing concepts, frameworks, etc. that already exist in the energy democracy that pose interesting problems for category theory? What additional developments within category theory might be required? Perhaps more precisely, what additional developments in category-theory inspired software tools might be helpful?  

## Energy systems ontologies

Use RMI's basic ontology of material, control, and economic levels but expand them towards an energy democracy framework. This three-layer model will have some similarities to internet architectures, in keeping with the idea that the "internet of things" has some important applications to energy systems.

### Layer 1: physical layer

### Layer 2: dynamical layer

### Layer 3: value layer

## Grid architectures

Kristov's integrated-decentralized systems seems more descriptive than NREL's autonomous energy systems. The latter seems to have been formulated during the self-driving car hype era. It perhaps describes the less-implemented side of the proposed architecture - the ability of systems 

Transactive energy and autonomous energy systems have been integrated in the paper 
