---
title: ""
author: "Brad Venner"
date: "10/26/2022"
output: html_document
---
# double categories, delta lenses, chu spaces

In his Ph.D. thesis, Bryce Clarke relates the concepts of lenses and double categories. Delta lenses are interpreted within a double category of functors and cofunctors. This double category resembles the double category of relations, with "horizontal" morphisms as functions and "vertical" morphisms as relations. 

Chu spaces are a generalization of relations. Profunctors are a generalization of relations. How are Chu spaces and profunctors related?

Chu spaces are examples of *-autonomous categories. Thus, states and events are both objects within the same category. On the other hand, the double category interpretation places states in one category and events in the other. (aside - how is the state/event duality related to Lawvere's space/quantity duality? Is there a Kan extension hiding somewhere?).

An earlier paper Clarke develops lenses within internal categories, which is also developed in his thesis. 

# game semantics and lenses via reverse-mode automatic differentiation

A recent paper with the title *Functorial String Diagrams for Reverse-Modle Automatic Differentiation* extends the *functorial boxes* developed by Paul-Andre Mellies for use in linear logic to analyze automatic differentiation algorithms. The paper develops the notion of hierarchical string diagrams, which are string diagrams that can contain other string diagrams within them.

This paper is worth studying for two reasons. First, it might help me understand reverse-mode auto-differentiation, which I