
Source: From Z.A. Jordan’s book “The Evolution of Dialectical Materialism,” published by Macmillan, 1967. This chapter of the book is reproduced for non-commercial, educational purposes only, and no permission is granted to reproduce the text.

# The anthropological conception of nature

Jordan describes Marx's metaphysics as "anthropological realism".  He classifies this as an epistemology.

Jordan claims that the move from Marx's realism to "dialectical materialism" was facilitated by Engels, who had a  "representational real"

Peirce's epistemology has been called "pragmatic realism" by several successors (similar to Jordan's renaming above).  

> Thus, Bertrand Russell suggested that the identification of knowledge with the process of knowledge in the course of which both subject and object are transformed may be described as an anticipation of Dewey’s instrumentalism.[[58]](https://www.marxists.org/reference/subject/philosophy/works/en/jordan2.htm#n58)

> 58. B. Russell, _Freedom and Organization_, p. 192; ‘Dewey’s New Logic’, p. 143. Dewey repudiated any affinity between Marx and himself by accusing Marx of the one-factor fallacy and the belief that the conditions provided by the environment are supreme. See _Freedom and Culture_, pp. 75-76. Precisely in this respect there is no difference between Marx and Dewey.

# The idealist and the materialist conception of history

In the next section, Jordon goes on to contrast the idealist and materialist ideas of history. Many of his framings endorse a nature-society-culture triad. Have I been developing a "materialist" understanding of history? Or is this a pragmatist theory of history?

Jordan endorses the nature-society-culture triad
> It is a fateful error to set society and culture over against nature. For society and culture which grows within it are a part of nature rather than a state of human existence opposed to nature, and culture originates not only in but also through society.

The internet, developed long after Jordan, has loosened control over "intellectual production," but the lack of progress on climate change shows that a certain anarchy in intellectual production tends to favor the status quo, which helps the ruling class. Pehaps Bryer is correct that the lowest level of this control over "intellectual production" is the "calculative mentality" that appears in multiple epochs (the accounting theory of history).

> For in every epoch the ruling ideas are the ideas of the ruling class, and the class wielding the dominating economic power in society is thereby its ruling intellectual force. The class which controls the means of material production has control at the same time over the intellectual production; those who rule as a class rule also as thinkers, as producers and distributors of the ideas of their age. These ideas are ‘neither pure nor external’. The ruling ideas express the dominant material relationships grasped as ideas, that is, they reflect the relationships which make a given class the ruling one and secure its domination.

> Assume a particular state of development in the productive faculties of man and you will get a particular form of commerce and consumption. Assume a particular stage of development in production, commerce and consumption and you will have a corresponding social structure, a corresponding organization of the family, of orders or of classes, in a word, a corresponding civil society. Assume a particular civil society and you will get particular political conditions, which are only the official expression of civil society.[[77]](https://www.marxists.org/reference/subject/philosophy/works/en/jordan2.htm#n77)
> 77. Marx’s letter to P. V. Annenkov of 28 December 1846.

Another triadic statement by Jordan:
> While men establish their social relations in conformity with their material production, they produce ideas, principles, and categories in conformity with their social relations.

# The social origin of man's distinctive characteristics

In Jordon's analysis, materialism and idealism seem to be both "ontological" and "epistemological" theories that mutually influence each other. They resemble meta-philosophies in this sense. For example, the next quote implies that some form of individual subjectivity must be imported into mechanical materialism in order to make sense of the theory.

> The failure of mechanistic materialism was due to the fact that from its point of view the world was an external object to be observed and described.


> The distinctive human traits are not a manifestation of man’s supernatural origin and substance; they are as natural as man’s animal characteristics. They derive and evolve from the association and interaction of individuals and, generally, from life in society.

A more detailed expression of the dependence of culture (ideas and systems of thought) on society, which plays a crucial mediating role.
> Unlike mechanistic materialism, which is anxious to explain how ideas and systems of thought are produced by physical and chemical processes in the brain, historical materialism tries to show how ideas and systems of thought emerge from and are determined by social conditions, which both shape and mould man’s behaviour and are shaped and moulded by man.

>But Marx ignored Rousseau’s dialectics as spurious, firmly holding to the view that men have always lived in society and believing that the individual is ‘a social being’ or ‘an _ensemble_ of the social relations’. Consequently, society is as real as the interacting individuals of which it is composed are real.[[102]](https://www.marxists.org/reference/subject/philosophy/works/en/jordan2.htm#n102)
>102. Marx, _Zur Judenfrage_, _MEGA_ 1/1/1, p. 595; _MEGA_ 1/3, pp. 116-17;  _EPM_, pp. 104-5; _TF_ vi.

Is society a category?
> Society is not an aggregate of individuals but a totality of interacting individuals. Therefore, society changes and develops according to its own laws which are not psychological but specifically social laws. They help towards understanding social phenomena and the social behaviour of individuals. As Marx put it, just as society is produced by men, so society itself produces man as man.[[104]](https://www.marxists.org/reference/subject/philosophy/works/en/jordan2.htm#n104)
> 104. Marx, _MEGA_ 1/3, p. 116; _EPM_, p. 103.

In *The Currency of Politics*, Marx's understanding of the nature of money was that it was difficult to control money through politics, and Eich believes that this has caused Marx's followers to neglect the political aspects of money. Jordan 