---
title: "Journal Entry"
author: "Brad Venner"
date: "12/31/2023"
output: html_document
---

# How to dogfood

One of potentially great things about the Mycorrhiza Cooperative is that it is intentionally prefigurative. That is, the structure of the company and the intended relationship between its workers and its users "prefigure" the intended society that software for social change is intended to bring about. The goal should be a virtuous cycle, where the software helps facilitate development of an organization that is capable of reconciling expertise (or leadership) with democracy. In this metaphor, expertise is the fungus in a symbiotic relationship with democracy, envisioned as flowering above-ground plants.

To do this, should the software be designed to be prefigurative from the start? And if so, where to start? I believe that 

It would be te

# Modular retrieval-augmented generation and cognitive architectures

Gao, et. al. describe three paradigms of retrieval-augmented generation (RAG) in LLM's: naive, advanced, and modular. 

# Product, platform, or something else

> tl;dr — A product is a conceptual whole intended to serve a specific purpose. A platform is a set of independent-yet-interlocking tools which can be externally orchestrated to create products.

Kislay Verma proposes two laws 

[Steve Yegge's internal memo within Google on platforms](https://gist.github.com/kislayverma/d48b84db1ac5d737715e8319bd4dd368)

# Mikorizal Software

Just a heads-up that Bob and Lynn Haugen, who Marie and I attempted to work with about 5 years ago, have an organization called [Mikorizal Software](https://mikorizal.org/). I don't know if Bob has trademarked the name, and I doubt that he would sue even if he had, but it might be neighborly to contact him and ask. I think both you and Mirror would agree with much of what he's about and his website has some nice bits. I think your vision is more political than economic (or perhaps bringing the economic under democractic control), 


# PostgresML