---
title: "Journal Entry"
author: "Brad Venner"
date: "04/06/2023"
output: html_document
---

# Substitution in Economics

Compositionality is often centered in applied category theory. But for economic applications, is substitution the more important notion? The substitution operation is closely related to translation, a key notion in semiotic. The notion of habit also involves substitution in key ways. A situation can lead to an action when the situation conforms to the abstract notion of situation encoded in the habit. 

Substitution is also relevant to notions of commensurability. The "hedonistic" philosophy of neoclassical economics assumes that every commodity is in principle exchangeable for every other commodity. This exchangeability relation must be "purely subjective" since no objective basis for exchangeability can be found within the commodities. Marxism tries to show that capitalism is essentially founded on the "socially necessary labor time" used to create each commodity. Marx left it as an exercise for the reader whether socialism would be founded on a similar idea. 

Although it's easy to say that socialism should be built upon an "inter-subjective" or "supra-subjective" notion of value, I've nevery been clear about what this looks like. Can focus on the notions of substitutibility and commensurability be used to derive an "inter-subjective" theory of value? If all signs are in principal supra-subjective, then measurement itself is an inter-subjective notion. Measurements are explicitly developed to be commensurable but this takes a metrological system to realize in practice.

Martinez-Alier, O'Neill and Munda state that ecological economics should be founded on a notion of weak comparability of values. This paper had 1,164 citations on April 6, 2023. John O'Neill is a co-author on the paper, and includes a review of Neurath's contribution to the socialist calculation debate.

Hypothesis: the theory of types now developed presents a language where the subtleties of substutition and commensurability can be treated in a mathematically rigorous way.

O'Neill's later book *Environmental Values* [@oneill:2008:environmental] attempts to develop a comprehensive theory of environmental value. The *weak comparability* framework is Co-author Andrew Light is now a member of the Department of Energy under the Biden administration, and wrote an earlier book *Environmental Pragmatism* that maybe I should read. 

Munda has focused more on multiple criteria decision making as a framework for implementing weak comparability. Like Light, he has also gone on to work in government, in his case for the European Union. Munda wrote a book *Social Multi-Criteria Evaluation for a Sustainable Economy* in 2008. [@munda:2008:social].

In [munda:2016:multiple], the term *compensability* is used instead of *substitutibility*. These seem to be used interchangeably in the genral

# Signs, Social Ontology, and Critical Realism

Roy Bhaskar, who developed critical realism, is cited by Bellamy Foster and Gare, and has developed a theory of "dialectics". Therefore, he's on my reading list for the "dialectics and semiotics" project. This paper [@nellhaus:1998:signs] by Tobin Nellhaus develops this comparison.

This paper was published in the *Journal for the Theory of Social Behavior*. The title of this journal points to overlaps with pragmatism, which is among other things a theory of social behavior. In pragmatism, the concept of habit is the element of continuity in action, which may be close to the concept of *behavior*. 

This reminds me that I need to get a copy of the book *Habits: pragmatist approaches from cognitive science, neuroscience and social theory*. This book has papers by Testa and Frega, but not many by Peirce scholars. There also doesn't appear to be anything from the active inference community. I think I read the introductory essay on Google Books.

# Ordinal parallels to compositional game theory

According to the Wikipedia entry on [ordinal utility](https://en.wikipedia.org/wiki/Ordinal_utility), cardinal utility is used in game theory and choice under uncertainty, while ordinal utility is used for choice under certainty. 

# Categorifying the polis

Began John O'Neill's book *The Market: Ethics, Knowledge and Politics* last night (April 11, 2023). This book is critique of the major positions defending the market in political philosophy that also serves as an apologetic for socialism (in it's associational form). Chapter 2 critiques the notion of "neutrality" in values. The pro-market argument is that markets uphold a plurality of values held by individuals by being neutral towards values. This lets individuals pursue their notion of the good without interference from the state. If the state were to choose a particular notion of the good, this would interfere with individual choice. 

O'Neill defends socialism through appeal to Aristotle. Aristotle's notion of human well-being was as a plural bundle of *ends*. These various ends are developed by different associations. The *polis* was of sufficient scale to self-sufficient at meeting these *ends*. Although a family was partially sufficient, it was at too small a scale to be completely self-sufficient. The polis is a special form of association, a "political" association.

This line of reasoning reminded me of category theory. In category theory, the completion of a particular mathematical structure in a category can have a different structure than the structure itself. For example, the category of sets is not a set. The category of all categories is not a category but two-category. This is a similar move to the association of all associations is not an association.

A little excursion on pluralism. Neither category theory or pragmatism are equivalent to pluralism. The hope for some sort of unity to arise out of plural views seems common to both Peirce and Aristotle. The integration of all human ends for Aristotle is *happiness* of the *polis*, while for Peirce the integration of all views of reality is *truth* in the *community of inquirers*. 

What is this integration, this unity? For Peirce, does truth lie in the community of inquirers? Is the notion of convergence the same as the notion of equilibrium in thermodynamics? For Aristotle, is the community happy? Or does the polis provide constraints, a guide to development that is somehow similar to biological development? The earliest stages of the development of the organism somehow create the constraints that guide the development of the later organism. The "final cause" is present at the initial stage. It resides in the genes, as material symbols or forms. But this "organic" metaphor does not seem to capture the looser notion of integration that exists within ecosystems. An ecosystem, as a whole, has a weaker notion of integration. The "wholeness" of a "system" is different than the "wholeness" of the "organism".

The unity of ecosystems should be a central focus of biosemiotics. Can a categorical semiotics help clarify what this emergent whole is? How is it related to Marx's "universal metabolism of nature"? More importantly, is there a semiotic economy, and how is it related to Marx's "social metabolism"? Oikos, nomos and logos, theory and practice. In Murphy's framework, "Nomos" is like custom, "logos" like stipulation. For Poinsot, the third leg was "natura", whose Greek equivalent was "physios". For the Stoics, there was "mythos", "nomos" and "logos" (https://textrhet.com/2020/01/09/sophistic-appeals-mythos-logos-nomos/). For Aristotle, there was "pathos", "ethos" and "logos". Peirce clearly built upon the Aristotelian triad. It's not clear to me where Poinsot's development came from, but there is some notion that emotions and myths are "natural". There is also the notion of what is shared in common - "mythos" is a story that everyone knows, while every human has the same "pathos". 

There is also the Rosen/Pattee view of a complex system as a system where multiple valid perspectives are possible. The happiness of a polis may be a valid unity, but cannot be reduced to a single dimension.

O'Neill claims that many socialists are Aristotlians, citing Marx and Polyani. Marx derived his distinction between use-value and exchange-value from Aristotle. 

In the 1920's, Polyani and Neurath disagreed about Neurath's assertion of only in-kind 
