---
title: "Journal Entry"
author: "Brad Venner"
date: "03/01/2023"
output: html_document
---

# Accounting as semiotics

I took a sudden turn towards research in accounting systems after a discussion with Steve Byers around ESG (Environment, Social, Governance) systems in business. I was not able to articulate as well as I would like why ESG was insufficient. But I was also struck by acute triadomany, with the parallels between governance-environment-social and democratic-eco-socialism. They seemed like potential allies. So I started researching ESG accounting.

I'm not sure what the Google search terms were, but my focus shifted upon finding Rob Bryer's books that he wrote after *Accounting for History*. I mentioned these previously. Byrer criticizes the trend in accounting towards "fair value" theory, which was developed by Irving Fisher as a direct attempt to refute Marx's labor theory of value. This move towards subjective valuation parallels the similar move in neoclassical economics away from "objective" measures and in probability theory towards "decision theory".

I haven't made much progress, or even known if I should continue, work on my *Semiotics and Values* project, as the gap between economic and philosophical theories of valuation seemed too far apart. I am now more hopeful that accounting theory can help bridge this gap. Even the basic notion that economics and accounting are separate, if related fields, is helpful, as they have pursued different notions.

I've encountered a number of semiotic-type framings in the accounting literature. As quoted in Bryer, "accounting is the language of business", an explicitly semiotic statement. My understanding of the semiotics is as between logic and systems, with elements of both.

Ijiri's accountor-accountee-accountant trichotomy [@ijiri:1983:accountability] to describe the accountability relationship and the role of the accountant as intermediary seems very close to the triadic relationship of the sign. Some of Peirce's definitions seem to include an active cooperative role for the three elements of a sign relation, which could be used to justify this perspective. For example, Peirce defines semiosis as:
> an act, or influence, which is, or involves, a cooperation of three subjects, such as a sign, its object, and its intepretant, this tri-relative influence not being in any way resolvable into acts between pairs [@peirce:1905:collected, 5.484]

This is where a compositional theory of accounting seems necessary, as each of these components is quite complex. Bookkeepers generate records from business processes, the records are translated into reports by internal accountants, reports are audited by external accountants, and the reports are interpeted by capitalists (i.e. investors). It seems better to consider this whole process as semiosis, which can be decomposed into smaller accountability relationships. So is there an "atomic" accountability relationship? Is every semiotic relationship an accountability relationship. If not, what distinguishes an accountability relationship from a more general triadic relationship? 

Peirce analyzes the act of giving as a triadic relationship
> consists in A's making C the possessor according to *Law*. There must be some kind of law before there can be any kind of giving - be it but the law of the strongest [@peirce:1904:collected, 8.331]

> This emphasizes that triadic relations are essentially examples of thirdness, that is, they introduce a law-like or rule-like character to the relations between elements [@liszka:1990:peirce, ]

The accountant has a detailed view into the records kept by the accountor and translates them into reports, which are viewable by the accountee. The accountant asserts that the representation of the records in the report is "fair". 

Ijiri develops the accountability framework in more detail in *Theory of Accounting Measurement* [@ijiri:1975:theory]. 

Ijiri's discussion of the role of the accountant is very similar to Peirce's discussions of the interpretant as translation. The accountant represents the activity of an "accountor" to an "accountee". This mediating role helps fulfill the accountability relationship between the two parties. The accountant protects the privacy of the accountor, revealing only those aspects that are necessary to the accountee. The accountant plays the role of a boundary or an interface, revealing certain aspects of an "object" while restricting others. There is something similar to a secure communication channel, but there is more of a sense of the quality of the representation. This triadic relationship doesn't seem well represented by the "utterer/interpreter" relationship that Peirce used to discuss "logical critic". In some ways the the accountant is an utterer - the accountants report is like a sign vehicle. But the "object" of the sign is the activity of the accountor and the report is a representation of that activity. This seems essentially more triadic than the more dualistic notions and perhaps points to accounting as more rhetoric than critic. The accountant develops signs that facilitate the accountability relationship but can also be deceived the the accountor. Like any mediator, the accountant cannot overcome a bad faith accountability relationship.

Peirce is quoted in [@liska:1990:peirce]

>  The whole purpose of a sign is that it should be interpreted in another sign and its whole purpose lies in the special character which it imparts to that interpretant.

This formal semiotic development must be compositional to allow for the complexity of actual accounting processes. Bookkeepers play a crucial role in developing records that serve as the basis of the accountant's reports. 

In terms of developing formal models of accounting systems, one possibility could be the discrete temporal type theory developed by Spivak. Myer develops temporal type theory as an example of the variable sharing paradigm of composition. The discrete temporal type theory might be a better representation of accounting systems then the petri net representation, since the temporal type theory is designed to describe systems of differential equations and thus has a natural stock-flow type of understanding.

There is a recent Julia library developing probability models within a data flow framework. I believe that this would be equivalent to a "parameter setting" theory of composition. Is there a corresponding "variable sharing" theory of probability? Does the presence of a topos theory in this model rule out a Boolean topos? 

# Fair-value accounting

Notes on the paper *‘Fair Value’ accounting as the normative Fisherian phase of accounting* [@cardao-pito:2018:fair]. Cardao-Pito cites Bryer but does not seem to have an explicitly socialist take on accounting.

Discounted cash flow implies a link between probability and money. Baez developed this link in a note on Azimuth. There is something like a monoidal functor between an additive category representing time and a multiplicative category representing "uncertainty". I wrote a response on the blog (looks like I forgot to save this locally) that mentioned this relationship as being generalized in linear logic. 

The relationship between probability and accounting is also explored in *Accounting: an Information Science*.

They summarize Fisher's theory
> Fisher’s theory leads to three premises that support increasing the wealth of owners/shareholders. These three premises are: (a) the ‘right’ equity/stock market prices of firms are equal to future cash flows that are payable to organisations’ owners/shareholders; (b) the purpose of the firm and its managers is to maximise the value of the equity/share prices; and (c) hence, the purpose is to maximise the cash flows (wealth) payable to owners/shareholders. If fair value accounting norms fall in line with Fisher’s theory, they must also be aligned with these normative aims.

