---
title: "Entry"
author: "Brad Venner"
date: "01/17/2023"
output: html_document
---

# SEBoK

# Social Systems Theories

Systems theories, as developed out of the natural sciences, did not necessarily include social aspects. 

SEBoK divides systems engineering into product, service and enterprise systems. Enterprise systems include an explicit social component. 

Luhmann and Parsons are both identified with developing systems theories within sociology. Luhman was a student of Parsons at Harvard. Luhmann later developed a rival theory.

Luhmann's theory was influential in the Vienna social ecology textbook. Luhmann also seems to be the base "systems theory" used by Bier in his "cybersemiotics." 

Scherr compares Luhmann's social systems theory and critical theory [scherr:2020:systems]. Luhmann's theory can be understood as potentially critical, but needing to develop a "scientific" viewpoint of society prior to the normative critique.

# Semiotics and open systems

Slowly reading Lerman's paper. One thought was that (early?) Peirce's model of the learning community is modeled after a closed system, which eventually reaches equilibrium. The notion of an independent, fixed reality serves as a fixed point. Lerman contrasts a Markov (stochastic) process as a closed system with a Markov decision process as an open system. 

Closure laws, on the other hand, are systematically important. Living systems are "self-renewing", in that they are open systems that still maintain some "equilibrium" with their environment. Rosen's closure laws (i.e. living systems are closed to efficient causation) are a central aspect of living systems: "a material system is an organism if, and only if, it is closed to efficient causation" [rosen:1991:life, p. 244]. Luhmann's autopoetic social systems are closed in some sense to inputs from the outside. Living systems must maintain a balance of open and closed, as exemplified by a cell membrane. So an open/closed dichotomy is 

Open systems are a better metaphor for learning processes than closed systems. Markov decision processes are used in reinforcement learning. The book *The Road to General Intelligence* [swan:2022:road] discusses the basic foundation of reinforcement learning for machine intelligence and why this approach is limited. They suggest the metaphor of "semantically closed learning," borrowed from longtime Rosen collaborator/critic Howard Pattee's notion of "semantic closure". 

Pattee discusses Rosen's *Life Itself* [rosen:1991:life] in his paper *Laws, Constraints and the Modeling Relation* [pattee:2007:laws]. Pattee considers DNA as a symbolic system.

> The central problem in hierarchy theory is the evolutionary emergence of new levels of control in organisms. [pattee:2007:laws, p. 3]

Stjernfelt discusses a similar notion of "level of control" in Peirce [stjernfelt:2016:dicisigns].

> 
# Measurement systems in double categories

In [lerman:2018:networks], Lerman mentions that his goal in introducing double categories into open systems theory was to reconcile the dynamic operads approach of Spivak with th notion of maps between dynamic systems inspired by coupled cell networks. The double categorical formalism he develops does this.

Could this move be repeated for measurement systems? Foley's paper on operads in complex systems design [foley:2021:operads] contains a nice analysis of a laser inferometer system. Morphisms of operads map between different system levels in their paper.

Monotone co-design problems are a related notion of design of a complex system. (e.g. [zardani:2022:co-design]).



# Culture, custom, society, habit, nature

Murphy discusses the social philosopy of Aristotle as being of two components: custom and habit. Custom mediates between the cultural sphere and the social sphere, while habit mediates between the social and natural spheres. Thus, custom and habit are like functors between the different categories. 

# Accounting for uncertainty

There is a close analogy between universal exchangeability in monetary systems and universal uncertainty in knowledge systems. The "subjective" notion of value in economics and the "subjective" notion of uncertainty in Bayesian belief systems are both motivated by utilitarianism. Both systems have earlier "objective" intepretations in classical economics and frequentist probability, respectively. Keynes is a key player here, as he wrote in both probability and economics.

# Pattee and Rosen

Pattee wrote *Laws, Constraints and the Modeling Relation* to describe what he saw as a change in Rosen's perspective between *Anticipatory Systems* and *Life Itself* and also to describe their long-term collaboration in theoretical biology.

Pattee and Rosen both believed 
> in the necessity of multiple alternative models to understand complex systems. This view was essential for hierarchic systems, and in fact, this was Rosen’s measure of complexity, i.e., the number of inequivalent models necessary to adequately explain a system (AS p. 322).

This notion of complexity calls into question the universal models of exchangeability and uncertainty posited in neoclassical economics and subjective Bayesianism. If complex systems have multiple inequivalent models, then should the notions of exchangeability and uncertainty also have multiple models? Reductionism assumes that all phenomona can be "reduced" to a single physical models without denying that a reductionist models may be one complementary model. I have not seen neoclassical economics or subjective Bayesianism described as "reductive", but they seem to share the notion of a single model. I'm guessing there is some literature out there discussing this point. 

There seems to be some similarlity with this definition and philosophical pragmatism. Peirce believed that no amount of "actuality" could fill up a "would-be". 

> By the time we left CTB (1975) Rosen and I agreed that Newtonian physics and even quantum physics [20], can be augmented by non-integrable constraint formalisms to model informational processes. This includes complex biological systems, measurement, predictive model-based controls, open-ended evolution, and symbol systems like natural, formal, and programming languages.

Pattee characterizes Rosen as an idealist and himself as a materialist. This is analogous to Marx/Hegel and Dewey/Peirce.

> A materialist does not believe symbol systems exist except as a material embodiment in genes, brains or computers, and consequently it is nature’s laws that place limits on symbol vehicle manipulation, not the other way around. [p. 7]

A great summary of the Marx - Hegel relationship as well. Not as clear in Peirce - Dewey.

Pattee quotes von Neumann:
> Probability logic cannot be reduced to strict logics, but constitute an essentially wider system than the latter [p. 9]

A categorical justification, thinking of an uncertainty system as a Kleisli category for a monad, would be the difference between a logic system and a modal logic system.

# The Necessity of Biosemiotics

Continuing on a Pattee bender by reading *The Necessity of Biosemiotics*. [pattee:2007:necessity]. 

> Biosemiotics recognizes many levels of control. Rate control, as in enzyme catalysis, is only the first level of control constraints. Symbolic constraints are a type of record that requires higher levels of organization. (p. 118)

As mentioned above, Stjernfelt describes this as a Peircean notion.

> There is a great amount of arbitrariness in these choices of parts and operations, but as we shall see, the basic logical separation of symbolic description and material construction does not depend on these choices.

Is "symbolic description" what Peirce called theory, and "material construction" what Peirce called practice in Kaina Stoicheia. This would equate Pattee's "symbolic description" and Peirce's "formal perception" and Pattee's "material construction" and Peirce's "material production."

Theory proceeds from "matter" to "form". Theory perceives. Theory
> sets out from a sign of a real object with which it is acquainted, passing from this, as its matter, to successive interpretants embodying more and more fully its form, wishing ultimately to reach a direct perception of the entelechy [EP2, 304]

Practice proceeds from "form" to "matter". Pactice constructs. Practice, in
> setting out from a sign signifying a character of which it has an idea, passes from this, as its form, to successive interpretants realizing more and more precisely its matter, hoping ultimately to be able to make a direct effort, producing the entelechy. [EP2, 304]

Pattee cites Rocha as recommending renaming *semantic closure* to *semiotic closure*. Rocha is now at CUNY-Birmingham, Pattee's former university. Pattee relates this concept of closure to the "epistemic cut" that is required for any symbol system. This might be a very interesting topic, given the emphasis on semantic closure in the *Road to General Intelligence* and their use of category theory to develop this idea. How would semiotic and semantic closure differ in this setting, and are there lessons for categorical semiotics.  