---
title: Post
author: Brad Venner
date: 2018-02-26
---

# How to proceed on accounting research

Can I use semiotics not as some pre-existing structure but as a guide to inquiry? 

That accounting, economics and finance are separate fields, with different methods and assumptions, is one of the most valuable ideas that I've gotten from Bryer. Some accounting theorists have 'resisted' the Economics Empire, developing their own theories of valuation distinct from economic theories. However, mainstream accounting does accept this. Even more, the theory of valuation, as a normative theory, has been imported into accounting as a "positive" theory, and is used to disparage more explicit normative theories in accounting.

In *Accounting for Value*, my understanding is that Bryer argues that the labor theory of value was an implicit theory of value behind capitalist accounting principles. In *Creating the Big Mess*, my understanding is that Bryer argues that Irving Fisher developed the "net present value" theory of valuation in order to refute this Marxist account. Fisher's theory eventually became widely accepted in accounting. 

The "net present value" idea has been enshrined in the Colorado laws on electric utility regulation. One of my goals should be to understand the basis for this theory of valuation. There is clearly a close relationship between this idea and probability theory. 

What are the socialist alternatives to this theory? Peirce's theory of 'would-be' seems like a potential application. Peirce argued that *esse in futuro* was not subject to the law of excluded middle. This opens up the potential for topos theory as the mathematical foundation for accounting theory. Perhaps temporal type theory could be used? [@shultz:2019:temporal] Spivak outlines a discrete version of this theory. 

Myers develops temporal type theory as an example of the "variable sharing" paradigm of composition, which seems to have some potential link to accounting. 

Another interesting application of Bryer's accounting history is that labor unions were pushing for "opening the books" during negotiations during the 1930s, but dropped these demands after the war. Bryer claims that management successfully convinced the unions of the "net present value" valuation theory, which led them to drop their demand for "open books". Could these paths be retraced? Could Trade Unions for Energy Democracy play a role in renewing this demand in the context of energy systems, particularly for vertically integrated monopolies? What would open books contribute to better utility regulation. 

# Theories of valuation and control

Ijiri's article *The Cost Principle and the Labor Theory of Value in Relation to the Role of Accounting Theories and Their Depth* [@ijiri:1999:cost] was cited in *Measuring and valuation in accounting -- theoretical basis and contemporary dilemmas* [@sdowska:2016:measuring]. Found this article trying to get a discussion of the difference between measurement and valuation in accounting, since this is "hot" topic in metrology.

The main goal of the article appears to be Ijiri's review of the book *Studies in Accounting* by Wasaburo Kimura, a 20th Japanese Marxist accounting theorist. Hence the article was published in *The Japanese Style of Business Accounting* [@sunder:1999:japanese].

Ijiri seems to agree with Bryer that the cost principle in accounting is compatible with the labor theory of value. He also develops a very Peircean notion of the role of accounting theory. 

> Let us consisder the three roles of theory: helping explain the real phenomena, helping predict the real phenomena, and helping choose action to change the reality.

This strikes me as close to abduction, deduction and induction. The notion of chosing action to change the reality seems close to Peirce's notion of the role of practice as moving from a form developed in mind to a realization in matter.

Ijiri goes on to develop the notion of notion of "understanding" as a level higher than the objectives or explanation, prediction and action. He says that understanding strives to focus on the principles behind a phenomena. Such theories
> are developed by using the ordinary theories as input and by analyzing the relationships among them.
This seems to fit the notion of induction as studying the relation among theories as posited in Peirce's gamma graphs and in categorical systems theory as natural transformations between double functors.

Note: this paper was not available on Sci-Hub and the book was not in Libgen. However, Google Books had the entire article available, less one page.

# Socialist accounting controversy

While the *socialist calculation debate* is a well-known episode in economics, the lesser-known *socialist accounting debate* is a related, arguably more important, and ongoing debate. The debates are related to each other in the way that economics and accounting are related but still independent fields. 

Some key thinkers:
1. Karl Polanyi
2. Robert Bryer
3. Irving Fisher
4. Pat Devine

Polani conceived of socialism as
>the tendency inherent in an industrial civilization to transcend the self-regulating market by consciously subordinating it to a democratic society. [@polani:1944:great, p. 242]

*Karl Polanyi's 'socialist accounting' and 'overview' in the age of data analytics* [@rief:2023:karl] provides a succinct history of the debate and the relationship between his accounting theory and the larger economic debate.

> On the contrary, Neurath’s important point was that monetary calculation
rendered commensurable what could not be commensurated and that direct comparison of whole economic plans and judgement of possible ways of shaping living standard was required (Neurath 1919, p. 146). According to Neurath, such decision making could not be replaced by calculation in any single unit of account, whether monetary, hours of work or else. The key point of Neurath’s calculation in kind was to avoid reducing multiple dimensions of value to a single denominator and to reorient the societal evaluation of economic activities to values that could not be expressed in monetary terms. [@rief:2023:karl, p 286]

> This last point also implied a critique of Lange’s approach, which suggested that a system of simultaneous equations could solve the problem of economic equilibrium in a socialist economy. Equilibrium prices would gradually be reached through an empirical process of trial and error (with the central planning board acting as an auctioneer). Against Hayek’s objections, Lange suggested that the electronic computer could solve the practical challenges of calculating the enormous equations and would be much speedier and hence superior to the market-based iteration process, which involved considerable time-lags (Lange 1967). For Lange, computer-assisted mathematical programming was fundamental for long-term economic planning. It fulfilled a ‘function that the market was never able to perform’ (Lange 1967, p. 161), but it did not render obsolete human judgment about economic policy.

Note the resemblance to heirarchical control within electricity systems. 

> Polanyi argued that different types of economy generate different agencies, techniques and objects of overview, depending on their practical aims and the particular questions asked (Polanyi 1922, p. 78). He did not understand accounting as simply a descriptive recording of facts, but instead as a representational regime that objectified the socioeconomic process into units of accounts capable of being totalled. Accounting brings into view (or out of view) certain elements of the socioeconomic process. It creates a knowledge base that orients economic governance.

> Polanyi’s broadly pragmatist conception of accounting led him to suggest that a socialist economy required its own mode of accounting suited to its particular goals.

# Operations, relations, management, governance

Myer's categorical systems theory arranges the data of a double category into operations (vertical morphisms) and relations (horizontal morphisms). In the parameter-setting doctrine of composition, the "operators" are lenses that compose dynamic systems and the "relations" are constraints.

Makkai's FOLDS includes only objects and relations. Makkai distinguishes this approach from generalized algebraic theories, which also include operations.

Corporations divide responsibilities between the board of directors and management. The board of directors is intended to focus on issues of governance - large, policy-level issues, while management focuses on the day-to-day operations of the company.

The U.S. constitution distinguishes between 