---
title: "Entry"
author: "Brad Venner"
date: "01/11/2023"
output: html_document
---
# Propositions as habits

The usual formulation of *propositions as types* can be usefully extended to with *types as habits*, composing to *propositions as habits*. This is a more explicitly pragmatic formulation than signs or systems. The notion of habit has been increasingly central in cognitive science as well as  in all of the classical pragmatists. A habit-based systems theory could be considered a "pragmatic systems theory," with the potential to unify sign-based and systems-based theories.  

To what extent do categorical semiotics and Myer's categorical systems theory overlap? Semiotics extends logic from a focus on symbols to the larger class of signs. Peirce's larger logical project extends logic at least to a philosophy of science, or possibly as far as a "theory of inquiry" in general. Since Myer's CST focuses on "natural systems" and logic on "cognitive systems", categorical semiotics should be able to address both systems and logics. 

Stjernfelt's essay *Dicisigns and Habits* [stjernfelt:2016:dicisigns] distinguishes between propositions as symbolic representations of habits and the "dicisign" as the broader class of proposition-like structures. A dicisign (dicent sign) is Peirce's new term for a proposition and has an actual existence as it's interpretant. If "secondness" is represented as a second (signified by *), then the possible dicisigns are [***],[0**] and [00*]. I'm a little fuzzy on Peirce's discussion of these - it would be good to review the "Syllabus" to confirm my understanding of this classification (EP 2:275 & 2:292, form the Commens dictionary). But the emphasis is on the mechanical aspect of habit, the understanding of habit as "necessary". What could be more necessary than actual existence?

# Value composition and decomposition

One of Rosen's themes is the difference between analysis and synthesis. The units developed for analysis are not necessarily the same units required for synthesis. This basic distinction seems to be missing from Myer's CST, although I would need to actually read the book to be sure. This distinction seems important for applications to measurement uncertainty (where the top-down/bottom-up distinction is closely related) and to value (where the social production process produces total value that must then be assigned to component parts in the process. Marx analyzed how this was actually done using double-entry accounting rules, which assigned profits based on these rules. Marx thus "inherently critiqued" classical economics by accounting norms. The link between (management) accounting and economics was obscured by marginalism. Accounting rules have been "harmonized" with marginalism with the transition from management accounting to financial accounting. Socialism faces the same general problem, but also must enhance social intelligence in the face of destructive value disputes. Socialism must move from accounting to accountability. The analysis of the "leading principles" of accounting, following Marx, and developing processes for ensuring value creation and accountability remains a major task.

Peirce took Kant's analysis/synthesis distinction and distinguished synthesis as abductive and inductive reasoning. This construction reminds me of the analysis of an adjunction as a special case of a Kan extension.

# Self-governance, self-control, second order cybernetics

According to the online Merriam-Webster dictionary, the term [governor](https://www.merriam-webster.com/dictionary/govern) is "Middle English, from Anglo-French governer, from Latin gubernare to steer, govern, from Greek kybernan". Therefore, it has the same Greek root as the term "cybernetics." But in general, cybernetics has been applied to the control of physical systems, while governance is applied to political systems. The term "control", on the other hand, has its roots in accounting, but is used in natural, social and political systems.

When Peirce talks about self-control of habits, this has an individualistic tone, whereas self-governance of habits has a more social/political tone. By the ethics of terminology, he probably should have used governance rather than control.

Perhaps no more complex explanation for how "control theory" became favored over "cybernetics" is necessary than the roots of "control" in early capitalism?

The term "self-cybernetics" never caught on, whereas "second order cybernatics" was used for the reflexive application of cybernetics. and other words such as "autopoesis" were coined to fill the gap. 

Zhao defines "cybernetics" as the "science of governance" [zhao:2016:defining] This would imply a similar relationship between cybernetics and governance as between jurisprudence and law, since jurisprudence is [a latin term meaning the science or knowledge of law.](https://curriculum.law.georgetown.edu/jd/jurisprudence/)

The term autonomous appears to be a neologism from the late 18th century, constructed from the Greek roots "auto", meaning self, and "nomos", meaning convention. Since the term was coined in the late 18th century, the concept of "nomos" was probably dualistic, in the contrast between natural (physis) and conventional law (nomos). But it is interesting to think of "nomos" in the tripartite sense of law, dwelling between natural and stipulated law [murphy:1990:nature]

# 3 -> 3 -> 3

Can Peirce's late classification of signs into 66 classes be seen as the profunctor 3 x 3 -> 3? The classification 3 -> 3 produces the 10 classes of signs as the homomorphisms between the reflexive graphs 3->3.