---
title: "Journal Entry"
author: "Brad Venner"
date: "02/10/2023"
output: html_document
---

# Knowledge graphs at EPA

In addition to participatory science, there are several other areas at EPA where knowledge graphs could have some application.

# Knowledge representation in double categories

My working thesis is that the link between knowledge and systems expressed in equipments (or perhaps double categories) is important for energy modeling. Knowledge representation is a cartesian equipment; are systems monoidal equipments?

Since CQL is based on the paper *Algebraic Databases* [@schultz:2017:algebraic], there should already be implemented a double-category representation of a knowledge base. 

Lambert's (blog entry)[https://topos.site/blog/2022/09/data-operations-are-functorial-semantics/] at the Topos Institute explicity links the "functional" knowledge representation (ologs) [@spivak:2011:ologs] with Pattersons "relational" knowledge representation (ologs) [@patterson:2017:knowledge]. Lambert makes the case that these perspectives can be combined from the double-category viewpoint. 

Patterson gives a talk at the Topos Institute outlining this perspective.[https://www.youtube.com/watch?v=TWEQT6HWJe8]. He states that his interest in category theory began with Spivak's functional olog paper. Functional ologs exist in the category of sets and functions, while relational ologs exist in the bicategory of relations. In the relational olog, objects are entities, morphisms are relations and 2-morphisms are implications (facts).

How do restrictions and extensions in an equipment fit the notion of "type refinement" functors? 

The (Wikipedia page on ologs)[https://en.wikipedia.org/wiki/Olog] states that the "target category" of an olog can be a Kleisli category, which includes both the Kleisli category for the powerset monad and the Giry probability monad. But this means that there should be link from the functional to the relational ologs.