---
title: "Journal Entry"
author: "Brad Venner"
date: "05/20/2023"
output: html_document
---

# Municipal digital socialism

How can socialists present a positive vision for the future when large-scale trends seem so negative? I was advocating for a "complementary currency" approach to local development to Nic last week, where a municipality could leverage under-utilized local resources to fill gaps in "social provision". But is this emphasis on complementary currency consistent with O'Neill's "associational socialism" or Morozov's "digital socialism" or the UK Labor Party's "universal social provision"? 

I haven't seriously looked at the complementary currency approach for a number of years. Prior to studying socialism in 2017, I was more interested in "monetary reform" approaches such as "positive money" or "modern monetary theory". But clearly this thinking is still basic to my positive view.  Another potential issue with a municipal complementary currency is the need to provide exchangeability with the US dollar to avoid conflicts with the "legal tender" requirements of the constitution. The need to provide exchangeability probably mitigates most of the benefits of a complementary currency, although it's possible that formally only a one-way exchange would have to be supported.

The idea of "digital municipal socialism" is to combine the infrastructure focus of "municipal socialism" with the novel coordination frameworks of "digital socialism". 

