---
title: "Entry"
author: "Brad Venner"
date: "01/11/2023"
output: html_document
---

# Potential EPA applications for categorical systems theory

## Bottom-up vs top-down approaches to measurement uncertainty

Top-down approaches are only as good as the proceses used to generate variation. This naturally leads to the idea of generating variability during the validation phase, a process historically known as "robustness testing". 

## Monotone co-design for analytical measurement systems

Monotone co-design has been used to develop a theory of design for engineering systems. The basic theory seems to be on binary profunctors, which are essentially relations. It seems like this theory could be used to specify analytical measurement systems (as methods) in terms of the relationship between pieces of equipment. But this neglects the time dimension, since the measurement process must unfold in time.

Operad theory from NIST [@foley:2021:operads]. Describes an instrument (an infereometer) as an operad. 

One clue could be the generalization of the operad approach to double categories pursued in categorical systems theory. Lerman described this as one of his motivations in his approach to open systems [@lerman:2018:networks].

Williams hints towards this in his [*cosmic logic*](https://cbw124.github.io/Logic/Logic%203.pdf). This "lifts" the double category of relations, where sets are types, to an "enriched" version where types are monads. His example of "judgements" in the enriched theory are a "bimodule". An example is that "resources can make products" in the category Poset.  

# Lenses as measurement systems

The four quadrants of a lens can be interpeted as an instrumental measurement system. The horizontal axis of the lens separates the physical from the informational, while the vertical axis separates the problem domain from the signal domain. In chemical measurement, the problem domain are chemicals, the signal domain is a numerical measure of a physical attribute, and the lens is the transductor between the two domains, i.e. the instrument. 

Spectroscopy would be a good target system, since the optical analogies in the mathematical treatment have actual optical counterparts. 

# Double categories, equipments, processes and systems

Logical systems - Christian Williams describes "fibrant double categories" as "a logic", with objects as types, morphisms as judgements, and two-morphisms as inferences (https://richardblute.files.wordpress.com/2021/11/williams-novfest.mp4)[Logic in Color]. Vertical and horizontal composition of 2-morphisms corresponds to composition in both sequence and in parallel. He then extends this analogy to equipments, using Myer's visual language for composing double categories/equipments. Then horizontal morphisms remain judgements, with vertial morphisms as terms. He recommends Wood's paper *Abstract pro arrows I* [wood:1982:abstract] as an example of the potential applications of equipments.

Database systems - *Algebraic Databases* [schultz:2016:algebraic] develops database theory within a proarrow equipment. 

# Categories for Markov decision processes and reinforcement learning

This would be a good focus for me to work on as it's adjacent to statistics.

Myer's formulation of Markov decision processes as double categories as a type of open system [myers:2020:double]. This formulation relies upon the "parameter setting" paradigm of composition. Is there a "behavioral" formulation?

Hedges' formulation of value iteration, a component of dynamic programming, as optic composition [hedges:].

*The Road to General Intelligence* and the critique of reinforcement learning as a general paradigm

Powell's formalization of sequential decision processes (universal but non-category-theoretic)

Botta's formalization of sequential decision processes in Idris (universal but not explicitly category-theoretic). Referenced by Hedges as an alternative to the open games formalism.

# Dynamic epistemic logic

I was searching the web on resources on game theory and rationality when I came across a chapter of a book co-written by Johan van Bentham, who I read during the Aplexys years. He emphasized the role of dynamic epistemic logic in the transformation of extensive game forms with public statements, which helps solve prisoner dillema-type situations. 

Shultz and Spivak have categorized dynamic logic with their temporal type theory. Could this work be extended to dynamic epistemic logic?

Myers includes temporal type theory as a paradigmatic case of a behavioral paradigm of composition. Could this analysis be extended to dynamic epistemic logic? Is there a non-state-based approach to sequential decisions? Could this logic be used in the Ilac's behavioral approach to distributed control in electricity systems? Lot's of intervening pieces, and this is pretty speculative.