---
title: "Journal Entry"
author: "Brad Venner"
date: "11/23/2023"
output: html_document
---

# The Power of the Sacred

Hans Joas is a German sociologist that has been at the forefront of the development of pragmatic approaches to sociology. I started to become interested in his work based on his review of a Castoriadis book, shortly after I had read *From Marx to Aristotle*. 

In his book *The Power of the Sacred*, Joas more explicitly brings Peirce's semiotic theory into his analysis. Based on summaries of the book, he attempts to develop the category of the "sacred" as the basis for a "social science" of religion. He generalizes the experiential category of the sacred to the experience of self-transcendence.

From the viewpoint of Peirce's categories, there seems to be a potential affinity between "aescetics", the first of the normative categories or the firstness of thirdness. Peirce did not develop this category in great detail, but he did make some characterizations that reminded me of Joas characterization of the "sacred". 

In Joas' chapter on Castoriadis in *Social Theory*, he summarizes Castoriadis' development of a "triadic" semiotic theory in reaction to structuralism, which was based on Saussure's diadic semiotic. It would be interesting to compare this theory to Peirce (and Dewey). 

Joas uses the phrase "fact of ideal formation" to describe Troeltsch's 
>study of the dynamic processes through which such ideals emerge, as well as reflexive recourse to these processes of emergence.
Joas uses 'ideals' synonymously with 'values' and somewhat distinguished from 'norms.' The emphasis is on the creation/appearance/emergence of new values, from which norms may be derived. Thus 'norm' has a usage that is closer to 'custom'.

# Proarrow equipments, databases, categorical systems

Christian William's enthusiasm for "fibrant double categories" (aka proarrow equipments, framed bicategories) had me looking forward to his dissertation. Unfortunately, the "gentle" introductory material from his talks was cut, and I found the resulting discussion difficult to understand. 

Three loosely connected ideas:

1. Categorical probability theory is based on the notion of a Kleisli category. This takes morphisms in the base category to "distributions" in the Kleisli category. In other words, from functions (the co-domain is single valued) to distributions (the co-domain is a distribution). The base category has products (i.e. is cartesian), and the Kleisli category has a monoidal product. (Classical probability theory also has sums - I need a better understanding of how these relate to the Cartesian structure). This interaction between a Cartesian and a monoidal category can be applied to more structures than classical probability theory, including non-determinism as relations. These structures are generalized to "Markov categories", which have their own string diagrams.

2.  In Pavlovic's *Programs as Diagrams*, the relation between a Cartesian and monoidal category is the relationship between "data" and "computation". Both data and programs are "cartesian", but computation is "monoidal". Using a fixpoint theorem, which I'd like to better understand, the data type "Boolean" maps to a computation type that includes additional values. This is related to the halting problem - something may be "derivable" in the Cartesian category but not "computable" in the monoidal category. Pavlovic's string diagrams show Cartesian arrows as thickened lines. Pavlovic uses "boxes" for computation but through Poincare duality these should probably be points. In linear logic, "boxes" represent monoidal functors and have a slightly different semantics.

3.  In linear logic, the monoidal category is "compact closed" and it's motivating example is vector spaces. The Cartesian and monoidal categories are related by an adjunction that gives rise to a monad/comonad pair. From the viewpoint of linear algebra, the "cofree coalgebra" is a complex structure discussed in the Wikipedia entry on linear algebra. The monad from the linear to the cartesian space is called the [storage modality](https://ncatlab.org/nlab/show/%21-modality) as it allows duplication of otherwise linear data.

This coexistance of the cartesian and monoidal structures (additive and multiplicative) in [linear type theory](https://ncatlab.org/nlab/show/linear+type+theory) in linear logic seems to have some resemblance to the similar relationship in probability theory. Given the "propositional" nature of both linear logic and probability theory, this may not be completely surprising. 

NLP has a particular map between vectors and probabilities. (write details).

Lambek researched linear types before Girard, so the ethics of terminology would probably require a different name. There's an interesting structure here with Lambek - Girard - Coecke.

The generalization to dependent linear type theory was begun by Shulman (who else), who called them [indexed monoidal categories](http://arxiv.org/abs/1211.1555).

[Frank Pfenning's course on linear logic](https://www.cs.cmu.edu/~fp/courses/linear/)77445

