---
title: "Analogy between "
author: "Brad Venner"
date: "05/23/2023"
output: html_document
---
Potential textbook: Measurement Across the Sciences. This focuses on a conceptual understanding of measurement systems as they might be realized in physical and social measurements. Mari's two co-authors are educational measurement specialists. The last chapter on semiotics of measurement could serve as an outline for the course. 

Potential textbook: Handbook of Measuring System Design. Focuses on physical measurement systems. Does include sections on systems thinking and life cycles. Includes several articles from Finkelstein on philosophy of measurement that might be interesting.

Potential textbook: Measurement Theory and Practice. By D. J. Hand. Develops a "pragmatic" theory of measurement that is "somewhat" related to 

# Introduction
1. Who am I? Who are you?

2. Transdisciplinary Frameworks

    a. Measurement 
    b. Systems
    c. Semiotics

3. Course structure
    a. Readings. Provide electronic versions of all documents on a document management system.
    b. Discussion. Each section has a practical running example. Discussions are intended to be cumulative.
    c. Programming. A domain-specific language for measurement systems. Probably in Julia for now, but Agda is a possibility. Include statistical analysis in course design, as well as probabilistic systems.
    d. Exams. These should be both subject and object. Particularly with Luca's ongoing example.
    e. Final project: Design or improve a measurement system, preferably in your major.

# Overview: Measurements, systems, semiotics

One classic piece of rhetoric (advice) for structuring a talk is to tell your audience what you're going to tell them, tell them, then tell them what you told them. A risk of this structure is that the introduction, the high-level overview, runs the risk of being too abstract and therefore confusing.

As we previously discussed, measurement, systems and semiotics have all been proposed as transdisciplinary frameworks. The "thesis" of this course is that these are related frameworks and that each has something to contribute to the study of measurement systems.

According to Cropley [@cropley:1998:towards_2], Finkelstein was the first to link semiotics and the measurement process.

## Reading: Chapter 8 of Luca

Chapter 8 of Luca was written as the concluding chapter of their book and therefore makes references to previous chapters. 

Of our three transdisciplinary frameworks, semiotics was developed at the highest level of abstraction and was intended to be the most inclusive. Measurement is the least inclusive and is the most opinionated. So all measurements are signs, but not all signs are measurements.

Insert "natural transformation graph" that shows the relationship between the concepts.

Insert Lawvere's nested Sierpinski diagram. 

## Lecture: Measurement by systems

Luca calls this "syntax"

## Lecture: Measurement of systems

Luca calls this "semantics". Relationship between measuring system and "system under measurement". Peirce's "actuality".

## Lecture: Measurement for systems

Luca calls this "pragmatics". Peirce called it "normative" or "would-be". Measurement as a purposeful activity.

## Discussion: Are grades measurements? 

# Metrology, measurement in the physical sciences

I'm not sure this should be a separate section. Luca contains parallel physical/psychical examples. I probably should stick to the textbook organization. Chapter 2 of the text outlines basic concepts, not all of VIM

## (Subfields)[https://en.wikipedia.org/wiki/Metrology]

1. natural metrology - measurands, units of measurement

2. technical metrology - measuring systems, realization of units in practice

3. social metrology - utilization of measurement systems in society. AKA legal metrology.

## Concepts and vocabulary in metrology

# Measurement systems

## Metric system

## National measurement systems

## Systems science

# Measurement Systems Theory

## Measurement vs measurability
Measurability is a theory about what things can be measured (a measurable property). Measurement considers the realization of measurability using a "measuring system". Measurement systems theory considers the theoretical aspects of this realization and thus has a broad overlap with systems theory and engineering. 

## Measurability theory

### Representational theory of measurability

## Measurement Systems theory

### Semiotic theory of measurement

> Working on the assumption that one of the shared goals of this list discussion is to consider the various ways that mathematical systems of logic might be used to foster more rigorous forms of inquiry in philosophical logic, then we might gain something by looking at Peirce's clarifications of these conceptions in measurement theory--which is largely a matter of applied mathematics. See CP 7.280-312. 

Chapter 8 of Luca

# Measurement Systems Engineering

1. Measuring system versus measurement system

2. Measurement systems lifecycle 

3. Requirements

4. Design and Development

5. Validation

6. Utilization
