---
title: Post
author: Brad Venner
date: 2023-04-02
---

# Logic in color and categorical systems theory

Myer's categorical systems theory and William's logic in color projects have superficial similarities. Both are based on double categories, both distinguish between morphisms between zero cells (functors) and one-cells (profunctors) as related but conceptually distinct processes. Williams cites Myer's early work on graphical models of double categories. 

To what extent can categorical systems theory be used to model energy systems? There are hints that the "bond graph" formalism used in energy transformation studies fits the variable sharing paradigm of composition developed by Myers. There is also the hybrid system model developed by Lerman, which follows from his work on "networks of open systems" paper. Hybrid systems can also be classified as "cyber-physical" systems. 

# Studying temporal type theory

Myers describes temporal type theory as a key example of the *variable sharing* paradigm of composition. There seems to be a "ladder of abstraction" here.

1. Willems on the behavioral approach to open, interconnected systems
2. Chapter 7 of *Seven Sketches* on sheaves
3. Schultz and Spivak on temporal type theory
4. Myers on the *variable sharing* paradigm of composition

However, I'm not clear that sheaves are necessary for the variable sharing paradigm. Although this may be an adequate translation of Willem's notion of behavior, is there a simpler notion? For example,the bond graph notion seems like it implements the variable sharing approach.

Peirce's notion of a proposition includes the notion of an index. The "subject" of a proposition is some region of space and time that can be indicated to some other understanding. This leads back to Stjernfelt's ideas of natural propositions, perhaps?

# Pragmatism and historical materialism

I've often considered the possibility of developing a course that relates socialism and pragmatism. A narrower project would be to consider the relationship between historical materialism and pragmatism. I've tended to think of this project as matching Hegel and Peirce as idealists and Marx and Dewey as naturalizing these projects. But chronologically the sequence is Hegel, Marx, Peirce, Dewey. Peirce begins his philosphical career at roughly the same time that Marx publishes Das Capital, but I am not aware of any direct connection between the men.   

Author | Born | Died
-------|------|------
Hegel   |   1770    |   1831
Marx    |   1818    |   1883
Peirce  |   1839    |   1914
Dewey   |   1859    |   1952

The biggest age gap is between Hegel and Marx. Given the 20 year age gaps between Marx, Peirce and Dewey, it's tempting to find an intervening philosopher, but given Hegel's influence on Dewey, Peirce, and Marx, it's probably still a good idea to leave him in the design.

Following O'Neill, perhaps a good strategy would be to find the common roots in Aristotle. These are explicit in Peirce, Hegel and Marx, but perhaps less so in Dewey (I would need to review Dewey's more academic writing in quest of footnotes.) This might be a good strategy for an academic course, as some students could have already developed a basic understanding of Aristotle.

All of these thinkers are also moving beyond Aristotle in some ways. I'm somewhat familiar with Peirce's approach. He even attributed "abduction" as an original conception by Aristotle that was obscured by a translator. Since I know Peirce the best, it might be easiest to work from his development back to Aristotle, then to move forward towards the other thinkers.  

Peirce develops his "speculative rhetoric" within the normative science of logic. The "dependency" model within his normative sciences would imply that aesthetics was not influenced by logic. But a more concrete connection with Marxism would imply that production, practice, and theory is a more Aristotelian division and has some benefits in terms of moving Peirce from a pure development of theory to a more political stance. Production is clearly associated with matter, or potentiality. Aristotle distinguished between "matter" and "nature", with living things being characterized as having souls that were not simply material. Since all signs must have a material basis, the production of signs is part of production. 

The mental sign of production, of the creation of possibilities, seems close to the notion of social imaginary. Without vision, the people perish. 

Is it possible to arrange these concepts in some sort of order? Ethos, nomos, energeia. Techne, pathos, mythos. Logos. The notions of firstness at the level of rhetoric all involve some form of appeal to emotion. The Stoic version of "mythos" seems at a higher level. While all humans have emotion in common, and these are closely related to our biological heritage, "mythos" has a more social connotation as shaping our emotional responses. A rhetorical appeal to emotion must rely upon signs, and the "narratives in common" understanding of mythos seems more reasonable. In this way, mythos and the social imaginary seem more closely related. 

But techne, production, seems much more than the mental understanding of firstness. Second nature, the material basis for human society, also seems to be a basis for the domain of nomos. 

The notion of secondness as habit and as the domain of practical reason. Dewey's notion of the role of intelligence in the examination of habit seems resembles Artistotle's practical reason. Politics seems like the relation between normative science and actuality. It's not clear to me how Aristotle distinguished between ethics and politics, since he covered these in distinct books. 

There seems to have been a fairly robust group of Aristotelian Marxists that developed in the 1960s. According to Blackledge,

> These factions were united in agreeing, negatively, that Trotsky had been wrong to classify the Soviet social formation as a degenerate workers state, and, positively, that Stalin’s Russia was a form of state capitalism. 

Castoriadis's journal *Socialisme ou Barbarie* was central. Other groups included the American Johnson-Forrest Tendency, led by Raya Dunayevskaya and CLR James, and the British Socialist Review/International Socialism group let by Tony Cliff and Mike Kidron, which included Alexander MacIntyre. Dunayevskaya's term for this tendency was "socialist humanism", which seems as good as any.



> MacIntyre argued that the role of revolutionaries was to develop programmes that brought ‘together three elements in our social life’: ‘the deep and incurable dissatisfaction with social life which capitalism breeds’; ‘the recurrent state of objective crisis in capitalist social order’; and ‘socialist theory’.[48] 

Blackledge expands his analysis of the tension in MacIntyre's book *Ethics in the Conflicts of Modernity* [@macintyre:2016:ethics]. Blackledge characterizes this book as a review of CLR James' work. James is important in the socialism humanism line of thought.

> Extending this argument in Facing Reality (1956), James and his co-authors, Grace Lee Boggs and Cornelius Castoriadis, wrote, “It is from the growing realisation that society faces total collapse that has arisen the determination of American workers to take control of total production away from the capitalists and into their own hands” (James, Lee and Castoriadis 2005, 31; MacIntyre 2016, 293–294).

>  By returning through Gramsci and Bloch to Lenin we can begin to reconceive Marxist politics not as an abstract utopia of the future but as a concrete utopia rooted in, but not reducible to, immanent tendencies within the present.
u