---
title: "Notes on The Semiotic Roots of Worldviews"
author: "Brad Venner"
date: "10/29/2024"
output: html_document
---

Notification of this paper came through email via ResearchGate. The subject line is very much in keeping with my current interest on the use of AI in implementing economic democracy and also revealing important aspects of "the automatic subject" (Marx's term) or "capitalist intelligence" (an inquiry similar to the AI Objectives Institute).

Of course, worldviews are of existential importance given the importance of the upcoming election and the impending threat of climate change.

There may be some overlap between the notion of "worldview" and the notion of "double categorical doctrine" being developed by Evan Patterson. The question is whether a worldview is a particular set of concepts formulated in a fixed logic (John Sowa seemed to advocate for something like this in his interpretation of modal logics, where facts in one frame could be possibilities in another.), or is a worldview also a different logic as implemented in CatCollab. This actually would be a good project in CatCollab

> We wish to distinguish worldviews from primarily subjective convictions. Worldviews are sign-systems and frameworks for understanding the world, whereas conviction measures the intensity of a knower’s holding a belief or a habit of interpretation.

Could a worldview be a "firstness of thirdness", or a "third nature"? If second nature (the built environment) is the firstness of secondness, then by analogy systems of belief would be accepted as "natural". They would have a basis in "second nature" as the basis of subjectivity in the "built environment" and would also be physical systems themselves. 

> A priori principles are malleable outcomes of how mind evolves in the universe, and thought is an embodied, enactive, and extended semiotic phenomenon (see Pietarinen 2021; cf. Snellman 2023).

> David Naugle even defines worldviews in the semiotic terms rooted in Peirce’s theory and classification of signs as a “semiotic system of narrative signs that creates the definitive symbolic universe which is
responsible for the shape of a variety of life-determining, human practices”

> Polanyi highlights personal knowledge and personal commitment that is necessary for using a theory or an instrument as a tool in scientific instrumentation.

This is why Michael Polanyi is the "lesser" Polanyi. This is clearly labor in Marx's formulation and by making it an "individual" property misses the social nature of labor. Knowledge production is production (what Marx calls mental production). Karl's more socialist committments. But this does provide evidence that Pietarinen is a "right pragmatist". (My current hypothesis is that Peircean's that neglect Dewey are almost always right pragmatists. )