---
title: "Notes on Technical Infrastructure for Energy Modeling"
author: "Brad Venner"
date: "3/30/2024"
output: html_document
---

What was hard about energy modeling

1. Figuring out which model to use
2. Learning to use Julia (i.e. putting long-term goals on par with short-term goals)
3. Deciding how much detail was necesssary for the model
4. We went down the Julia roll-your-own pathway, then went to Switch, but tried to keep the existing Julia code.
5. Identifying sources for data.
6. Transforming data into the correct format.
7. Getting things written up. 
8. Outreach. We never did develop a website or present our results in a systematic way to interested parties.
9. Reproducibility. We did not have a fully documented data engineering pipeline. 
10. Calibration. Reproducing Xcel's results to show that we could their model results. This turned out to be the must-run constraints.
11. Power network. We never moved past a copper plate model.
12. Time. We started too late and by the time we had the model working
13. Lack of support. Leslie was always at best "meh" about the work and did not line up any other advocates that could present the work during testimony.
14. The PUC. This whole system is designed in a legal framework that has no interest in the truth. This seems really obvious but was still a surprise.
15. I wasn't willing to devote 6 months of full-time work to do this.
16. Loss of motivation. We had no plan to present the results outside of Leslie.

If I were to redo this:

1. Have a separate server, perhaps a VPS, that would run a task queue for simulations (RabbitMQ and Celery).
2. All input and ouput files would be put into a database. 
3. Visualizations would be output from the database.
4. Spend money on cloud compute

Why do energy modeling
1. Every time you democratically plan how to create and distribute resources you are building socialism, because you're learning how to do it.
2. In this frame, building energy models is a step towards socialism.
3. Actively weakening capitalism.