---
title: "Notes on systemics"
author: "Brad Venner"
date: "7/9/2024"
output: html_document
---

# Wikipedia

Wikipedia is awesome. I began writing on "Systems, Semiotics, Socialism" without consulting the Wikipedia page on each subject. I'm now on my second revision of the title, now "Systemics, Semiotics, Dialectics". This has both an appealing symmetry in the word choice (three syllables, ending in "ics"). It also implicitly identifies my protagonists as von Bertalanffy (or Bogdanov?), Peirce (or Dewey) and Hegel (or Marx?) as founding these interventions that took existing principles and expanding them into proposals for a "meta-philosophy". It's attractive to use Bogdanov as my founder of "systemics" as there would be explicit links to dialactics. On the other hand, one could highlight the political tension in these fields between conservative (von Bertalanffy, Peirce, Hegel) and liberal? (Bogdanov, Dewey, Marx) tendencies. von Bertalanffy was literaly a Nazi.

# Systemics

The Wikipedia page suggested that the term systemics was coined by von Bertalanffy. 

