---
title: "Thoughts on the purpose of purpose"
author: "Brad Venner"
format: html
---

I was thinking about this question in the middle of the night. 

A fancier way to formulate this question would be the naturalization of teleology. Recent work by several philosphers, notably Leonardo Bich, follow up on the ideas of Pattee and Rosen that life (at the organism level) is characterized by closure conditions. Rosen called this closed to efficient causation, but Bich uses Pattee's formulation of closure of constraints. These ideas are also influenced by notions of biological autonomy developed by Maturana and Varela.

Bich extends this model to consider second-order constraints (i.e. constraints on constraints). While second-order constraints are subject to the same closure condition as first-order constraints (i.e. they are produced by metabolic processes governed by first-order constraints), Bich models them as operating in a more dynamic fashion. The main role of second-order constraints is "regulatory control" - controlling the timing and intensity of metabolic processes so that these are appropriate in space and time. 

Castoriadis' 