---
title: "Notes on Rethinking Regulation"
author: "Brad Venner"
date: "10/30/2024"
output: html_document
---

John Seddon rehashes his book in this manifesto. The proposed solution is to have the highest levels of a government service provider specify the "purpose" of the public service, and to delegate "measurement" and "methods" to lower levels of the system.

Seddon tends to fall in a dualistic distinction of regulator and regulatee, when regulatee should be divided into service provider and service receiver. Seddon's examples are all on direct public service provision and the specifications are placed on service providers, which then are applied to service receivers. For example,

> ... how well the relationship between government, regulators and Parliament works in performing their regulatory tasks ... I was struck by the fact that the fourth party in the regulatory system – those subject to regulation – is conspicuously absent from the analysis.

Presumably, many of these regulations specify how the provider should interact with recipients. Seddon complains about standard measures for these interactions that result in counter-productive behaviors by either providers or receivers. 

This tiering reminded me of two other three-layer tiers. The first is Nick Fisher's book "Analytics for Leaders", which specified the three zones of measurement as strategic, tacitical and operational. Fisher does not think that strategic measures are not measures, and this seems to differ from Seddon's take.

The second is the AI Outcomes Institute whitepaper, which specified three layers as inter-institution, intra-institution and individual. Fisher's approach seems more systematic.

This also reminds me of Marie's division in her thesis to macro-, meso- and micro-scales, presumably borrowed from the human ecology literature she was studying.
