---
title: "The Arbinger Institute and Vulgar Pragmatism"
author: "Brad Venner"
date: "10/16/2024"
output: html_document
---

Dan,

You offered to entertain feedback on the Arbinger Institute course "Developing and Implementing an Outward Mindset" that your institute presented to NEIC management and staff on August 27 and 28, 2024. In my opinion, while there were some valuable ideas that were presented in the course, the overall intent of the course was to justify the institution of the employer-employee relationship. The main vehicle was to obscure the important differences in the roles of family member, peer, employee and govenment agent common to every NEIC employee. This allowed Arbinger to develop false analogies between the roles and obscured the important role that public sector unions play in the delivery of public services by denying the fundamental reality of the employer-employee relationship. Although this was not as blatant as anti-union propaganda delivered in the private sector, I believe that it has a similar goal.

Although Arbinger Institue does not cite any intellectual influence in its materials, I believe that it is largely a species of "vulgar pragmatism", although more sophisticated than many other such efforts.  