---
title: "Notes on mathematics, narratives and life"
author: "Brad Venner"
date: "8/1/2024"
output: html_document
---
[@gare:2024:mathematics]
Gare's new article tracing the role of the understanding of life as mediating between mechanistic science and the humanities. Relatively dissapointing paper, which fell into the "Gare integrates all of his reading" genre without providing sufficient detail to know what he is integrating.

> While there are a number of important philosophers and other theorists, including mathematicians in the tradition of process metaphysics, I believe the five most important are Schelling, C.S. Peirce, Henri Bergson, Alexander Bogdanov and Whitehead.

> The development of Category Theory, which took place after Bergson, Peirce and Whitehead, was not influenced by Grassmann, but its leading exponent, William Lawvere (1996), argued that Grassmann’s extension theory was a precursor to Category Theory. (p 8)

> Lawvere, F. William. 1996. ‘Grassmann’s Dialectics and Category Theory’. In: Gert Schubring ed., Hermann Günther Grassmann (1809-1877): Visionary Mathematician, Scientist and Neohumanist Scholar. Dordrecht: Kluwer: 255-264

Definitely need this reference for SSD.

> Finally, semiosis was extended to the study of the relationship between different organisms and species within ecosystems, with Kalevi Kull arguing the all bonds with ecosystems are semiotic bonds. (p. 14)

Unfortunately, Gare gives no citations to a specific work of Kull. But this suggestion is interesting as a foundation for ecology, society, democracy.

> In a relatively recent work, *Mathematics as Modelling System: A Semiotic Approach* (2014), Marcel Danesi and Mariana Bockarova have defended Peirce’s characterization of mathematics by characterizing it thought through Peircian semiotic theory, at the same time providing a history of mathematics, including its notations, and the way it has been understood up to the present.

I only glanced at a couple pages of this paper, and while I agree with foregrounding "modelling", I believe that this should be understood as an analogy rather than a map. In other words, "modeling" should be restricted to language users and other terms should be used for the "models" used by biological agents (umwelt, anyone?). This move shares a similar problem with "cognitive biology". If one makes cognition identical with semiosis (cognitive biology = semiotic biology), then a new term must be invented for the emergent human capability. I admire Peirce's use to "thirdness" as an extremely vague term to describe that which is preserved across multiple scales and systems.