---
title: "Notes on responsibility"
author: "Brad Venner"
date: "10/01/2024"
output: html_document
---

Piet Strydom released an article on ResearchGate that was flagged today, entitled *Responsibility - a General Self-Referential Concept for Collective World-Creation*. 

There is a strong relationship between the concepts of "accountability" and "responsibility". One should not be held accountable for something unless one is responsible for it. Ijiri's notion of an interface in accounting seems similar to the notion of responsibility, where not every aspect of a system is subject to accountabilty.

Responsibility is also a key notion within causation. Shafer's paper *Causality and Responsibility* says that "attribution of responsibility, whether as blame or praise, always rests upon a claim about causation." SemanticScholar identifies only 13 citations of this paper.

I believe that these concepts are crucial for socialism. In general, the *Left* does not share a compelling model for how social property and accountability can be reconciled. The *Right* appeals to notions of shirking and free-ridership to motivate a continued need for *private property*, where in theory attribution of responsibility can be made. One could call this a "nominal theory of responsibility" that draws upon *modern individualism* for justification.

Unfortunately, Strydom never links the concepts of accountability and responsibility in his discussion of corporate ESG responsibility. Instead, he settles for more vague exhortations to make "corporate citizens" to be more responsible, rather than analyzing the legal and accounting rules that govern corporate behavior. Rather than thinking of a corporation as belonging to the domain of individuals, it seems more promising to think of them as belonging to the domain of governance, where the sovereign people grant a corporation certain powers in order to achieve a certain purpose. Corporate governance should be united with "state" governance, with all of the difficulties of holding powerful social actors to account. 

Strydom also seems to take an idealist view of history, where advances in the theoretical understanding of "responsibility" have driven history, rather than 

Shafer's notion of responsibility has the benefit of being much more concrete. He develops the notion of "Nature", which is a God-like intelligence that makes "predictions". This reads almost as a parody of Peirce's notion of the "would-be" and the "community of inquirers", in that only the "actual" structure of propositions are included and that the practical limitations of communication among scientists are elided in the notion of "Nature". The question of whether there are practical differences that are introduced by this difference in conceptions must be left for another time, as I must return to my responsibilities today.