---
title: "Notes on measurement systems project"
author: "Brad Venner"
date: "7/9/2024"
output: html_document
---

I just sat through Stan Deming's short course on "Statistical Analysis of Laboratory Data". I think that I could put together a more focused and interesting course that would use advanced computing to move statistical/uncertainty models closer to analytical practice. My basic tool would be "top-down" approaches, aka Bayesian hierarchical ANOVA as developed by Gelman, used to analyze single-laboratory validation studies. I could extend this approach to experimental design on one side and "measurement systems" on the other. This would force me to confine the philosophy to no more than 1/3 of the course and give the overall presentation a more pragmatic/statistical bent than what I've been considering for a "Measurement Systems" course.

A lab data course would also let me focus on compositional data, and specialize software to solve these problems. I'm not sure what this looks like, or even if compositional analysis is always the best framework.

I'd also like to expand to joint mean/variance models. 

I'd also like to expand to Taguchi designs.