---
title: "Thoughts on critical accounting"
author: "Brad Venner"
date: "8/20/2024"
output: html_document
---

Shortly after I finished reading Bryer's text *Accounting for Value*, I began doing a little reading on accounting systems. I had also put reading Kliman's book *Reclaiming Marx's Capital* on my list, where the details of the temporal single system interpretation of the "transformation problem" were outlined. However, I did not continue this initiative.

Recently, I've returned to this topic due to my commitment to reading Anwar Shaikh's *Capitalism* book as part of a reading group at the New School. Shaikh's discussion of the transformation problem simply dismisses the "temporal single system" interpretation from a "simultaneous single system" interpretation by essentially defending simultaneous validation as essential for evaluating a business as a "going concern". 

The [New Left Review review of Shaikh's book](https://newleftreview.org/issues/ii104/articles/john-grahl-a-new-economics) states that

> It must be said that it’s not clear why Shaikh, or indeed other Marxists, regard this issue as so important. Apart from the question of relative prices, there do not seem to be any propositions in Marxist economics in general or in Shaikh’s own version which depend upon it.

Grahl's question is important because it's hard for me to state what the impact of the choice would be. Marie asked me in the car about why this was important and I stumbled trying to answer. Perhaps one goal of a study of Shaikh could be to see if I could understand a "pragmatic consequence" of the concept.

Now Rob Bryer has filled several books with an analysis of why "replacement cost accounting" in particular, and managerial accounting in general, was replaced by "financial accounting" and how this was devistating for the labor movement, among other things.

The idea that I keep coming back to is Peirce's notion that the logic of a "would be" does not include the law of excluded middle. The notion of what an asset would bring as a discounted flow of value is contingent upon many things and, as a prediction about the future, has the logical status of a 'would be'. On the other hand, Bryer argues that accounting is about accountability, and is necessarily about the present state. Replacement cost accounting does not look to the future for what an item is worth but to the present - what would it cost me to replace an item in my current capital stock with a similar item. The fact that "prices of production" are dynamic means that this question can be answered by looking to the present, not the future.

I have two speculative links to this idea. The first is that the logics of possibility (allows contradiction), acutality and 'would-be' (no excluded middle) corresponds to the linear-affine-Cartesian triad of substructural logics outlined by Mellies. This idea clearly needs to be developed more clearly, and may not be true, but has a nice potential link to electricity systems, which when they include generation have been developed as an affine, not a linear system. The second is Ijiri's theory of momentum accounting and triple-entry bookkeeping, which struck me as very similar to Peirce's categories when I read an article related to Ijiri's system. Since Ijiri was more focused on a cost-based accounting theory, this seemed to be a development that could include the future in accounting in a more principled way than Fisher's future-oriented valuation theory.

I also have the vague intuition that a semiotic theory of economics would be valuable, uniting Marx and Peirce. Under this theory, the production process, or techne, would reclaim it's place as a site of knowledge as well as action, and the crass materialism of the labor process would be replaced by 'know-how'. The dependence of a sign on a material sign vehicle would be the link to materialism, while still allowing for a "formal" sign. The under-theorized notion of prices as "signals" would be replaced by a true semiotic analysis. Right now, the practical benefits of such a theory seem remote, but in theory would allow a better integration of "politics" (language-based) and "economics" (signal-based) as two aspects of the sign. This would would in theory depend upon making progress in the systemics-semiotics-dialactics project.

Relevance Lost: The Rise and Fall of Management Accounting. 1991. H.Thomas Johnson and Robert S. Kaplan. ISBN-13: 978-0875842547