---
title: "Notes on agency"
author: "Brad Venner"
date: "6/26/2024"
output: html_document
---

# Agency, accountability, responsibility

Ellerman's metaphysics appears to be highly nominalistic, with agents identified with mind and "property" identified with matter. His vector formalization of accounting expands the attributes of an agent beyond money and into a larger collection of alienable property. But an agent also has "inalienable" attributes, which appear to be properties of agency itself. Agents cannot transfer their agency to another agent. This includes "positive" transfers, such as assigning their share of profits to another agent, or "negative" transfers such as avoiding criminality. 

Ellerman analyzes the legal and actual domains, where the relationship between properties owned by agents are governed by contracts. This is a nominalistic formulation in that relationships 

Does this dualistic metaphysics identify "agency" and "responsibility" as a necessary (i.e. causal) relationship? In other words, given an outcome, does it assume that causality can always be identified? Ellerman explicitly assumes away non-causal relationships, such as loss of food due to spoilage, but is this a valid move? This is the problem with identifying "agency" with human cognition. Isn't the bacteria causing food to spoil acting with some agency as well? As Rosen argues, if causation is invoked with every "why" question, and causation is the same as agency, then the answer of "bacteria" to the question "why did the food spoil" must be one of causal agency.

Since Ellerman argues that he is reviving a "classical liberal" position, one taken up by Ricardian socialists, it seems unlikely that Marx did not already consider and reject his argument. Bryer argues that Marx located the "cause" of accounting rules to be capitalist value theory. Can Bryer's work be used to refute Ellerman's accounting arguments?

Google links the search term "inalienable right" to the Wikipedia page on [natural rights and legal rights](https://en.wikipedia.org/wiki/Natural_rights_and_legal_rights). Ellerman's concept of "inalienable right" seems close to Francis Hutchinson's and Hegel's concept, where what is inalienable are those aspects of personhood that distinguish persons from things.

The same Wikipedia page also questions the division into natural and positive law. Madison called this third "social law", which appears to be similar to Murphy's "customary law". 

> There is also debate as to whether all rights are either natural or legal. Fourth president of the United States James Madison, while representing Virginia in the House of Representatives, believed that there are rights, such as trial by jury, that are social rights, arising neither from natural law nor from positive law (which are the basis of natural and legal rights respectively) but from the social contract from which a government derives its authority.[35]

The Wikipedia page doesn't link the Greek concepts of physis and nomos with the natural/legal (i.e. positive) distinction. I believe that Castoriadis had some good insights into this division.
