---
title: "Compositionality"
author: "Brad Venner"
date: "10/10/2023"
output: html_document
---

My previous entry in this blog was focused on measurement systems. I'd like to wax philosophical around the notion of compositionality. This morning I listened to Vincent Bevins' interview on [*The Dig*](https://thedigradio.com/podcast/if-we-burn-w-vincent-bevins/) and read a summary of their book on [*The Guardian*](https://www.theguardian.com/world/2023/oct/10/the-mass-protest-decade-why-did-the-street-movements-of-the-2010s-fail). Bevins blames the failures of the street protest movements in the 2010 decade on the lack of organization of the various "new left" movements on their insistence on the "horizontal" dimension of organizing that left these movements susceptible to capture by more "vertical" right organizations that still maintained the illusion of protest. The "new left" rejection of the vertical dimension was a reaction to the failures of "actual existing socialism", which were traced back to the seed form of Lenin's vertical cadres.

The notion that democracy must be "purely" horizontal reflects upon the strong individualism/libertarianism/anarchism bias that characterized the neo-liberal period.

Systems theories are based on concepts of compositionality. A "system" is a whole that has "meaningful" parts. The potential benefits of categorical systems theory is that it does not simply take a single concept of compositionality for granted but allows for different concepts that are still somehow related.  

I believe that democracy does not simply take a theory of compositionality as "natural" but understands that democracy must also be created. Democratic subjects must be able to resist incorporation into totalizing systems 

# Orchestration

This term is increasing used in devops. Camus Energy is adopting the term for grid management. But it has a longer tradition of use in the "unity of science" movement. It was repeatedly used by Neurath, who stated that he adopted it from a lecture given by Horace Kallan in 1939. Nuerath's wrote a paper with the title *The Orchestration of the Sciences by the Encyclopedism of Logical Empiricism* [@neurath:19], which responded to another Kallan article.

> The synonym I would prefer is orchestration, with its implication of diversities of instruments and parts, of movements and pauses, of dissonances and discords as well as harmonies, of sequences whose every new item suffuses without deindividualizing all that have gone before. 