---
title: "Why study sociology"
author: "Brad Venner"
date: "5/19/2025"
output: html_document
---
I spent my "surplus" time this weekend and late last week reading "social theory", in particular Hans Joas' book on social theory, but also revisiting Roberto Frega's work. I've also spent a fair amount of time reading sociology-adjacent writers like Apel or Castoriadis. Is this a good use of my time? In particular, is sociology sufficiently valuable to developing *Citizens' Nexus* to justify the investment? In other words, is CN primarily a technological problem or an "institutional" problem? It's easy to elide this problem by using the term sociotechnical system, but the question of priority is a question of resource management. Would it be most productive to focus on developing citizens' assemblies using existing information systems, or would it be better to focus on developing information systems and then working with "partner" organizations to use and evolve the system. This latter strategy is what Mycorrhiza is doing with Kessler.

Another question is whether to pursue a textbook-level approach (such as reading Joas) or a Wikipedia-centric approach? As I was writing this entry I ended up spending a fair amount of time on Wikipedia, and it can feel more productive to develop a surface-level understanding of a network of concepts rather than the rather slow linear presentation of a work 

On one hand, sociology is attractive because it has developed as an alternative to economics and *Citizens' Nexus* is in my understanding primarily a project in economic democracy.  Historically, sociology focused on the "residual" of rational action, as explained by Joas, as it split from the more well-established fields of economics. It also seems like there is an unproductive split between economics and politics, naturalized as "private" versus "public", while the intermediate category of "social" has been neglected. The contemporary split between "civil society" and "private enterprise" is quite different from Hegel's unification of these two domains. But Hegel placed "the state" as a different category in his philosophy of law.  

Sociology is also attractive because of it's imperial ambitions. There is work in "economic sociology," "political sociology," "organizational sociology," etc. According to Joas, sociology includes the study of social change as a key area of inquiry and thus is different from economics, which focuses on "thermostatics".

I think one trigger word was "interaction" when I was reviewing *Measurement Across the Sciences*.  

On the other hand, social theory seems incompletely separated from social philosophy. New "scientific" fields that would like to spin off from philosophy periodically occur, and usually the goal is to distinguish itself from it's "rudimentary" philosophical precursor. 

The "natural" sciences have clearly had great success with this separation. So much so that "natural philosophy" has to be defended as even an actual thing. Much of natural philosophy seems to be done by scientists that take an interest in philosphical aspects of their discipline. I think I started reading philosophy more generally after becoming somewhat suspicious of scientist-philosophers such as Ken Wilber or Robert Rosen, who sometimes seemed to be reinventing the wheel.  

The psycho-social sciences less so, although psychology and economics have had some success by emphasizing their proximity to the natural sciences. Anthropology split itself, with "physical" anthropology being more scientific and "cultural" anthropology more "social" (based on a Google search, there has been some debate on the term and "social", "cultural", and "sociocultural" anthropology are recognized subfields.)

# Why Study Pragmatic Social Theory

Since Matt McManus has developed a book on "liberal socialism," it seems like a book on "pragmatic socialism" could be valuable (would probably need to be called something like "pragmatism and socialism" to avoid the more obvious vulgar connotations with "pragmatic". One could also argue that "liberalism and socialism" would be a better title anyway). Any such development could draw upon  