---
title: "Notes on The Evolution of Semiotic Self-Control"
author: "Bradley Venner"
format: html
---

The Peircean reference to Kaina Stoicheia was found in Frederik Stjernfelt's contribution *The Evolution of Semiotic Self-Control*. This notion of *semiotic self-control* seems like a very nice interpretation of the concept of autonomy, and this essay extends this notion throughout evolution. I really need to read "Natural Propositions"! Of course, autonomy calls out to the distinction between "physis" and "nomos" more directly than the term self-control.

The article begins critiquing Deacon's notion that symbols can be distinguished as a phase in biological evolution. Stjernfelt points out that "dicisigns" are a type of symbol and points out that "natural propositions" must occur very early in biological evolution. This is consistent with the biosemiotic notion that thirdness and life are coextenstive.

> So Peirce may describe the Dicisign as a special sign uniting two different signs both related to the same object, but in two different ways.

So does the Dicisign have the structure of a loose morphism (i.e. span, cospan or possibly profunctor)

> Pragmatically, the existence of Dicisigns will be displayed by specific perception-action connections – in an organism’s behavioral possibility of acting in a typical, categorized way prompted by the categorical perception of some biologically important, stable feature of its environment. p. 45

Baez analyzed this perception-action link as a cospan in their "agent" blog series, but thinking of a cospan as a habit allows for 2-cells to represent the habit of changing habits.

It would be valuable to analyze this example of *e. coli* and *sugar* as an example of an evaluation. 

The main argument of the paper is that self-control essentially involves hypostatic abstraction, and that this ability is key to thinking about thinking, in that the original thought must be transformed into an "object of thinking". There is a ladder of self-control in this chain of abstractions. Several quotations from Peirce are used to illustrate these chains.

A correspondence between semiotic self-control and joint attention is developed. He references Tomasello's work on joint attention, which I haven't read. This section seems important as it covers the same gap as from individual to collective autonomy covered by Castoriadis. A link is made between the game-theoretic understanding of logic in Peirce and joint attention. 