---
title: "Notes on evidence-based economics"
author: "Brad Venner"
date: "5/7/2025"
output: html_document
---

Quick summary before getting back to work. Was thinking about the triad (evidence, inference, inquiry) as a description of semiotics and how this might related to (measurement, systems). The latter requires 

Anyway, I read a (review)[https://ndpr.nd.edu/reviews/evidence-inference-and-enquiry/] of the book (Evidence, Inference, and Enquiry)[@dawid:2012:evidence] that included a chapter-by-chapter summary of the book. I had previously engaged with this line of thinking, including buying Schum's book on probability and evidence and Anderson and Twining's book *Analysis of Evidence*[@anderson:1991:analysis]. As has been typical of many of my "special" projects, I never really advanced this to an actual work project that left my office. However, I still feel like this could potentially be a fruitful area, particularly with the "libshit" focus of OpenPUC. Could LLM's be used to fruitfully analyze evidence and could such methods be used in a collaborative modeling process? 

At a basic level, the evidence triad and the Peircean triad are identical. The primitive notion of evidence seems like firstness, as an awareness of the presence of an object related to a sign-vehicle. Semiotics seems to accomodate the diversity of evidential forms encountered in law. In a legal setting, all evidence is symbolic but in natural science setting "indications" play a central role. 

Formal methods for analysis of evidence fall into the same problem as formal methods elsewhere, in that they cost a fair amount to develop but may only have questionable benefit unless applied widely. I'm encountering this problem with measurement uncertainty right now. For the OpenPUC project, there are a great diversity of quasi-legalistic proofs available in the docket. A basic question is whether LLMs could be used to help develop formal analysis of arguments, and to what extent could "categorical semiotics" be used as a tool of "argument representation"?

Anyway, one of the articles in EIE was a paper by Michael Joffe entitled *What Would a Scientific Economics Look Like?*[@joffe:2011:what]. Joffe is a biostatistician/epidemiologist that seems to have taken up economics late is his career. This paper compares the understanding of evidence in economics and biology and blames the relative lack of progress on economics on the substitution of assumptions for evidence.

Another paper by Joffe that I briefly reviewed was *The World Created by Capitalist Firms* at the web site (evidence-based-economics.org)[https://evidence-based-economics.org/articles/economics-growth-and-the-capitalist-firm/the-world-created-by-capitalist-firms/]. This web site was set up by Joffe and includes a number of his papers on the subject. This paper argued that theories of economic growth should focus on the capitalist firm, as the takeoff of capitalist growth occured with the introduction of this form. This argument reminded me of both Shaiks' concept of real competition and also Bryer's concept of the central role of accounting in the growth of capitalism, particularly in cost- and management-accounting. There was also another book that highlighted the divergence between the concepts used in neoclassical economics and econometrics on Real-World Economic Review. Forgot the author!

Anyway, it would be interesting to develop the analogy between biological and economic organization using more recent models of biological organization. There is some relation in that the "means of production" are also the "products of production" in a way that is reminiscent of biological organization. 

Jaffe's article *Equilibrium, instability, growth and feedback in economics* [@joffe:2020:equilibrium] brings up a point also developed by Shaikh - a diversity of "micro-foundations" can lead to the same observed "macro-behavior" due to the presence of feedback relations. 
