---
title: "Thoughts on The Big Picture"
author: "Brad Venner"
date: "4/21/2025"
output: html_document
---
I told Marie this morning that I was juggling several different ideas that I was hoping would come together. I thought I should try to write down these different interest areas at a high level of generality, and maybe some preliminary thoughts on the links between them.

From the top of my head and after some refining, these areas are:

* Actors and agents:

    +  Actor models and message passing,

    +  Cognitive agents,

    +  Knowledge engineering.

* Semiotics and systems:

    + Self-organizing multi-agent systems,

    + Measurement systems,

    + Accounting and accountability.

* Democracy and governance:

    + Economic democracy,

    + Citizens' assembly.

There are some more formal areas of interest that I am hoping will help connect these areas:

9. Category theory, particularly categorical systems theory.

These formal areas are necessary to undertake a project with this vast scope and limited time. The idea is that progress in these formal areas can help make progress in the more substantial areas above. 

This project is more focused on taking action than systemics-semiotics-cybernetics-dialectics. While I think this latter project

# Actors and agents

Both actors and agents as research areas originate in the MIT Artificial Intelligence lab. Hewitt invents the actor model 

It's a bit of a grey area whether actor- and agent-based models would be formal or substantive areas. I think it's the latter, because the community of agent-based modelers resides in wide areas of the social sciences. Although the link between actor- and agent-based models is not "necessary," my intuition is that this is a promising direction in developing these models, and also that Hash.AI has proposed building an agent-based modeling system on top of an actor-based system.

A related area is the entity-attribute-system data model used in game engines. Game engines could be used as a foundation for agent-based simulation, as used in projects like Krabmaga. The EAS data model seems related to the ACSets developed in Algebraic Julia. Baez also develops a categorical approach to agent-based model that uses a colimit-based approach to model transitions that reminds me of "systems" in the EAS model.

My intuition is that agent-based modeling will be important for accountability, economic democracy and citizens' assemblies. 

## Cognitive agents

I left this category off my list, as I haven't done as much work in this area lately. There is a fair amount of overlap between this and knowledge engineering, but I'm going to treat it as a separate category because cognition is such a major theme in both semiotics and artificial intelligence. Semiotics investigates the threshold and emergence of human cognition from biology, while artificial intelligence explores the threshold between human and artificial intelligence. The term "agent" is a very pragmatic idea that crosses these various boundaries, and there are interesting overlaps between "agency" and "autonomy". 

I'm also implicitly including multi-agent systems withing 

## Knowledge engineering

Data-driven agent-based modeling can be extremely time and resource intensive. One of the insights that Mycorrhiza is building is that there is a potential synergistic relationship between natural and artificial systems in the modeling process. Clearly RAG in LLMs can provide more accurate answers than LLMs alone. Google/DeepMind have shown that neurosymbolic approaches can be valuable in implementing non-trivial reasoning in speciality domains. 

# Semiotics and systems

## Measurement systems

## Accounting and accountability

# Democracy and governance:

## Economic democracy

Nathan Tasker points to administrative law as a model of balancing democracy and expertise. Pitt's work on SOMAS also has some ideas on balancing these two desiderata.

> There are various models for democratizing administrative agencies — “local councils” and (citizen oversight juries)[https://www.dissentmagazine.org/online_articles/give-political-power-to-ordinary-people-sortition/] to name a few — and more generally a wide literature on balancing the need for expertise with the need for democratic accountability. (Just Another Administrative Agency)[https://www.crisesnotes.com/just-another-administrative-agency-preserving-central-bank-discretion-without-illusions/]


## Citizens' assembly.
