---
title: "Thoughts on Systems and Index"
author: "Brad Venner"
date: "1/15/2025"
output: html_document
---

I was listening to a podcast episode of *Philosophy Bites* entitled  *Decision Making Under Indeterminacy*. Two things struck me. First, the lack of priority given to Peirce in this discussion. Peirce took vagueness extremely seriously throughout his philosophical career, and it seemed in error to not center this discussion on his work. The podcast was part of a larger project in [Vagueness in Ethics](https://vaguenessandethics.wixsite.com/project) at Uppsala University, so it may be that Peirce gets more credit in the larger project.

The second thing was the relationship between Peirce's notion of index and the concept of system. Although a system is often considered as a whole that contains part, the boundary between system and environment is also crucial. This boundary seems important to Peirce's notion of index, which he later defined (get reference) as a distinguishable space-time region. So there is an implicit notion of topology in this understanding of "index" that could also be applied to the components of a system. 

When I asked Perplexity.AI to compare these concepts, it brought up the notion that an index is a particular type of sign that has a causal connection with it's object. This is certainly true, but my sense is that in Peirce's later work that indices were crucial to the definition of a proposition but also even to iconic signs. 