---
title: "Thoughts on Measurement of Measurement Systems"
author: "Brad Venner"
date: "4/3/2025"
output: html_document
---
There is an essential recursive property to thinking about measurement systems. If a measurement system is a system, then it should be able to be measured. The mideaval way out of this problem is to classify the properties of measurement systems as "second intentions". 

According to the Wikipedia entry for [non-functional requirement](https://en.wikipedia.org/wiki/Non-functional_requirement), a synonym is "constraint". This fits nicely with the notion of "constraint" in Myers' categorical systems theory, as well as with the same concept in biological organization theory. 

Also, a measurement system is a "system of systems". There is the system under measurement, the measuring system, and the "interpretant system" (Rosen called this the "formal system", which might be a better term. Could also be "symbol system". Not sure what it's called in representational measurement theory.)

So where to start in developing measurement system theory/science/engineering? One possibility is the ladder sign -> evaluation -> measurement. An "evaluation" would be a sign with an interpretant as a symbol, at least in representational measurement theory. It would be interesting to check this idea against Dewey's work on the theory of valuation. Mari states that they use "evaluation" in

> the technical, non-axiological sense of *attribution of a value to the property of an object.*

I read a paper that distinguished evaluation from measurement. I wonder if I can find it again. Google search was unhelpful. Could be the earlier Mari paper *Epistemology of Measurement* from 2003. Starts with a quote from Plato, satisfying Whitehead's "footnotes on Plato" aphorism.

Mari, 2003 claims that the general epistemological problem of measurement is "what characterizes measurement with respect to generic evaluation." 

Mari lists 4 properties/attributes/characteristcs of a measurement:

* an empirical process
* designed on purpose
* whose input is a property of an object
* that produces information in the form of values of that property

Mari shorthands this to *a designed empirical property evaluation*. Mari says these are necessary and not sufficient conditions, and that there can be DEPE's that are not measurements.

I think this definition misses the essential pragmatic quality of a measurement by defining a general "purpose" rather than the specific goal of producing "inter-subjective" information. Thus, the more general concept of valuation does not require an inter-subjective component. Values can be quite subjective, particularly if you want to have a conversation with a liberal.  

Searching the PDF for instances of "evaluation" gives an earlier paper by Mari called "A relational theory of measurement: traceability as a solution to the non-transitivity of measurement results". This reminds me of a virtual double category, where some properties are preserved even when strict composition is not available. 

Towards the end of Mari, 2023, they sketch the notion that measurements are both objective (i.e. object-related) and inter-subjective. Are these "non-functional" requirements of a measurement system? Looking through the list of non-functional requirements below, "reproducibility" is listed as is "accuracy". The latter could probably be redefined in terms of "object-relatedness", while "reproducibility" could be considered as "inter-subjective."

Decided to Google this combination of terms and ended up looking at a paper entitled *Intersubjectivity and value reproducibility of outcomes of quantum measurements* by Masano Ozawa [@ozawa:2024:intersubjectivity]. A bit afield from Mari's "non-quantum" measurement theory but does stand for the proposition that intersubjectivity and reproducibility are related concepts, although these terms are given a technical meaning within the QM formalism and I'm not sure I totally get the difference.

# Relational measurement theory

Continued Googling around "measurement theory". Found a couple papers by Ken Krechmer on relational/relative measurement theory. He cite's Mari's 2007 paper entitled *A relational theory of measurement* [@mari:2007:relational]. 

These two papers bear an interesting relationship. The later paper does not cite the earlier paper. Furthermore, Mari 2007 is cited as "relative measurement theory" in the later paper and "relational measurement theory" in the earlier paper. These papers were published in the same journal two years apart, and the (auto-generated?) highlights on the web page give essentially the same points. The highlight that caught my attention was "reproduces Ozawa’s (2003) universally valid uncertainty relation." Compared to Ozawa's crystalline prose, Krechmer is hard to read. Could be better to understand Mari's original paper and Ozawa's "universally valid uncertainty relation" well before trying to understand how Krechmer links the two.

It's interesting to think about this in comparision to Mari's later *semiotic theory of measurement* developed in their 2023 book. As Deely explained, Poinsot's semiotic theory was a *relational theory* in that it considered a sign to be a relation in the Aristotelian sense and that the key innovation was that the "being" of relation was independent of *ens real* or *ens rationis*. Although Peirce's notion of semiotics was superficially more "triadic", Bellucci showed that his notion was derived from Scotus that was more relational (hope I can find this reference again). What links generalized perception and purposeful action is habit, and it is in the nature of habit to be natural, conventional or stipulated.  

# List of non-functional requirements
accessibility
accountability
accuracy
adaptability
administrability
affordability
agility (see Common subsets below)
auditability
autonomy
availability
compatibility
composability
confidentiality
configurability
convenience
correctness
credibility
customizability
debuggability
degradability
determinability
demonstrability
dependability (see Common subsets below)
deployability
discoverability
distributability
durability
effectiveness
efficiency
elasticity
evolvability
extensibility
failure transparency
familiarity
fault-tolerance
fidelity
flexibility
inspectability
installability
integrity
interactivity
interchangeability
interoperability
intuitiveness
learnability
localizability
maintainability
manageability
mobility
modifiability
modularity
observability
operability
orthogonality
portability
precision
predictability
process capabilities
producibility
provability
recoverability
redundancy
relevance
reliability
repairability
repeatability
reproducibility
resilience
responsiveness
reusability
robustness
safety
scalability
seamlessness
self-sustainability
serviceability (a.k.a. supportability)
securability (see Common subsets below)
simplicity
stability
standards compliance
survivability
sustainability
tailorability
testability
timeliness
traceability
transparency
ubiquity
understandability
upgradability
usability
vulnerability