---
title: "An apologia for creativity in measurement"
author: "Brad Venner"
date: "5/29/2025"
output: html_document
---
I spent my "surplus" time this weekend and late last week reading "social theory", in particular Hans Joas' book on social theory, but also revisiting Roberto Frega's work. I've also spent a fair amount of time in the past reading sociology-adjacent writers (social philosophers?) like Apel, Dewey or Castoriadis. Is this a good use of my time? In particular, is sociology sufficiently valuable to developing *Citizens' Nexus* to justify the investment? In other words, is CN primarily a technological problem or an "institutional" problem? It's easy to say "both" by using the term sociotechnical system, but the question of priority is a question of resource management. Would it be most productive to focus on developing citizens' assemblies using existing information systems, or would it be better to focus on developing information systems and then working with "partner" organizations to use and evolve the system. This latter strategy is what Mycorrhiza is doing with Kessler.

Another question is whether to pursue a textbook-level approach (such as reading Joas) or a Wikipedia-centric approach? As I was writing this entry I ended up spending a fair amount of time on Wikipedia, and it can feel more productive to develop a surface-level understanding of a network of concepts rather than the rather slow linear presentation of a work 

On one hand, sociology is attractive because it has developed as an alternative to economics and *Citizens' Nexus* is in my understanding primarily a project in economic democracy.  Historically, sociology focused on the "residual" of rational action, as explained by Joas, as it split from the more well-established fields of economics. It also seems like there is an unproductive split between economics and politics, naturalized as "private" versus "public", while the intermediate category of "social" has been neglected. The contemporary split between "civil society" and "private enterprise" is quite different from Hegel's unification of these two domains. But Hegel placed "the state" as a different category in his philosophy of law.  

Sociology is also attractive because of it's imperial ambitions. There is work in "economic sociology," "political sociology," "organizational sociology," etc. According to Joas, sociology includes the study of social change as a key area of inquiry and thus is different from economics, which focuses on "thermostatics".

I think one trigger word was "interaction" when I was reviewing *Measurement Across the Sciences*.  

On the other hand, social theory seems incompletely separated from social philosophy. New "scientific" fields that would like to spin off from philosophy periodically occur, and usually the goal is to distinguish itself from it's "rudimentary" philosophical precursor. 

The "natural" sciences have clearly had great success with this separation. So much so that "natural philosophy" has to be defended as even an actual thing. Much of natural philosophy seems to be done by scientists that take an interest in philosphical aspects of their discipline. I think I started reading philosophy more generally after becoming somewhat suspicious of scientist-philosophers such as Ken Wilber or Robert Rosen, who sometimes seemed to be reinventing the wheel.  

The psycho-social sciences less so, although psychology and economics have had some success by emphasizing their proximity to the natural sciences. Anthropology split itself, with "physical" anthropology being more scientific and "cultural" anthropology more "social" (based on a Google search, there has been some debate on the term and "social", "cultural", and "sociocultural" anthropology are recognized subfields.)

# Pragmatism and Socialism

Since Matt McManus has developed a book on "liberal socialism," it seems like a book on "pragmatic socialism" could be valuable (would probably need to be called something like "pragmatism and socialism" to avoid the more obvious vulgar connotations with "pragmatic". One could also argue that "liberalism and socialism" would be a better title anyway). Any such development could draw upon pragmatic social philosophy in the same way that liberal socialism draws upon liberal political philosophy. Frega [@frega:2014:between] outlines three models of social philosophy: the analytic, the critical and the pragmatic. They argue that analytic (also known as Anglo-American) social philosophy is usually equated with political philosophy and when it is referenced it is usually about something like Parson's "normative order". 

Can the pragmatic defense of the social also be understood as developing a category between physis and nomos? Frega [@frega:2014:between] argues that analytic social philosophy draws 

>a clear demarcation between normative and descriptive theory, and between the domain of philosophy \(normative\) analysis and that of the social sciences \(explanation and forecast\). 

Frega develops the close relationship between the social philosophy developed by pragmatism and critical theory. The main distinction he draws is between reform and revolution. Critial theory assumes a need for revolution and requires a critical perspective that is somehow embedded yet outside of current society \(immanent transendence\). Dewey's reform-based approach does not locate the normative outside of society and posits that norms arise within the context of specific problems and have a finite life. This fits with the idea that a performance measure can transition from help to hinderance as the measure can be mistaken for the goal. Although the reform/revolution debate continues on in Marxism, my own sense was that Marx did not take a firm position and that his admiration for parts of capitalism implied that a certain level of reform was possible. For example, workplace cooperatives might still maintain a similar organizational structure to capitalist firms, but with greater emphasis on democratic accountability of management to workers.

Frega's proposed division into habits, patterns of interaction and institutional order bears a family resemblance to Poinsot's division of signs into natural, customary and stipulated. Dewey's social psychology more closely identifies natural signs and impulse but may overestimate the stipulated category by identifying it with "intelligence." Stipulated law is clearly symbolic and sometimes may have even been intelligent but can also settle into stale routines. This would be a good idea to write up but I'd like to involve Peirce's categories as well. My intuition is that one of the alternate interpretant categories would be closest, with the division emotional, energetic and logical having the closest ordinary language resemblance. Although both Peirce and Poinsot were eager to develop classifications, Peirce was also thinking of more dynamic interpretations such as stages. Hegel's use of the term "moments" is also helpful, where each aspect is always present but at any moment in time one may predominate. Peirce's early identification of different processes of "separation" in his first category paper, such as abstration and precission, seems like it would also be helpful. It could be that in human experience the "stipulated" moment is always present. In ordinary language, this is called "rationalization" as we provide an explanation of why an energetic habit is operational. 

Would it be worthwhile to bring in Freud's social psychology here? The idea of id, ego, superego also has a family resemblance, but these ideas tend to be popularized as purely residing in the individual. An obvious interpreter would be Castoriadis, who has both a triadic semiotic theory and a deep understanding of both Marxism and Freud. Following McManus' model, Castoriadis could be a central figure in "pragmatism and socialism", as could Cornel West and Axel Honneth. Following Frega, this project could be expanded to "liberalism, pragmatism, socialism" with the last category covering critical theory and the first category including Rawls. Frega use of analytical, pragmatic and critial as identifiers focuses attention on the 20th century, since "analytical" and "critical" make their appearance in this century. "Liberalism, pragmatism, socialism" has a more 19th century focus. 

As Frega outlines, the emphasis of pragmatism as a social philosophy would be on the category of "custom" or "habit", but where these are identified with "patterns of interaction." Frega doesn't supply tons of examples of what he means by "patterns of interaction," but this could be supplemented by formal examples from message passing and examples of social animals that have emergent patterns of interaction without "stipulation." We are lucky in the 21st century to have such good studies on "animal intelligence" where we have examples of changes in habit at the organism level that do not rely upon mere mechanistic understanding of habits.

Note that Frega critiqued Testa's notion of habit from a 2016 paper in his "social ontology" paper. I wonder if he updated this critique in the version that appeared in Testa's book?

Both Marx and Hegel examined "anglo-american" philosophy (at that point, only "anglo") pretty deeply, and one could argue that Marx is the first pragmatic socialist. He certainly identified himself with "scientific socialism" whereas according to Apel Peirce advocated "logical socialism". Marx does not deny liberalism but in many ways tries to show that it is incompletely realized under capitalism. Peirce strongly advocates to retain the category of the "individual" as does Dewey, and their model of association retains the individual in a way that more "organicist" understandings tend to neglect. I know from secondary literature that both Hegel and Kant were influenced by English empiricism (Kant's famous "dogmatic slumber"). Hegel's analysis of "civil society" brought together 

> both the 'bourgeois' sphere of market relations and the 'civic' sphere of institutionalized individual and communal rights (https://alioshabielenberg.com/the-relationship-between-civil-society-and-the-state-between-hegel-and-marx/)

The existence of what are clearly "institutional orders" in Hegel's concept of "civil society" probably shows that civil society is more complex than simply custom and that there is a difference between "customary law" and "civil society". Bielenberg refers to an 1843 manuscript from Marx published as the *Critique of Hegel's Doctrine of the State*. I did not know that there was anything except Marx's notes on *Philosophy of Right*.

Hegel develops the incomplete 2 x 2 table

|           | Altruism | Egoism        |
|-----------|----------|---------------|
|Particular | Family   | ?             |
| Universal | State    | Civil Society |

Hegel defines altruism as

> our willingness to make sacrifices in solidarity with others.

Great Marx quote:

> Democracy is the solution to the riddle of every constitution.

This translation is much catchier than "democracy is the solved riddle of all constitutions". I should make this a bumper sticker.

Marx's idea that the state emerges from real people resembles Frega's idea that political philosophy emerges from social philosophy and that the latter is primary.

# Social philosophy and *Citizens' Nexus*
So what can social philosophy contribute to *Citizens' Nexus*? One obvious caution is to avoid thinking of *Citizens' Nexus* as developing a "generic process", and instead think of it as a meta-process for developing citizens' assemblies that are problem-specific and open. I've critiqued this notion of procedures as "generic processes" and felt that specifications are more helpful as a "meta-process" that can be realized by a variety of different processes. This probably involves loosening the notion of "flow of control" that is endemic in the notion of specification. Could this involve the more flexible notion of control flow in message passing? Or perhaps the difference between policy and action as developed in stochastic optimization? 

# Relational vs interactive sociology

Frega treats these terms as more-or-less exchangeable, footnoting paragaphs with the term "interactionist" with a reference to "relational". I have not seen "interactionism" used much in my previous study, and it seems to have a specialized meaning in sociology. However, the term "relational" was placed at the center of semiotics by Poinsot \(and Peirce to a lesser extent\), in biology by Rosen and Rashevsky, in measurement by Mari, and in quantum mechanics by Rovelli. The book *Biological Organization*, which I read over Christmas, builds upon Rosen's relational biology, although it has some interesting modifications to include a more dynamic understanding of constraint that had some resonance with double category theory. To a lesser extent, Hewitt's defense of the actor model summons relational quantum mechanics, so there is potentially a "relational informatics" based on the actor model, although Hewitt did not really develop this analogy and Google does not distinguish "relational informatics" from "relational database".

My personal hope is that "categorical semiotics" can help elucidate "relational semiotics" by placing the concept of "relation" within multiple category theory. My hope is that "categorical systems theory" and "categorical semiotics" can both be developed and used within measurement systems.

When I looked at "relational sociology" earlier, it did not include Rashevsky's work. There is a chapter from *The Palgrave Handbook of Relational Sociology* entitled *The Relation as Magical Operator: Overcoming the Divide Between Relational and Processual Sociology* [@vandenberghe:2018:relation] that develops the difference between the more static view of "relation" and the more dynamic view of "process," which is somewhat elided in Frega's account.

>Anyone who has dabbled with relational sociology will have noticed that it fuses two different approaches, a relational and a processual one, into a single one, uniting them under a single flag of convenience. The \[relational\] turn ... is a hypenated one. The unity of the label should not hide the polarity between its relational-structuralist pole and its processual-pragmatist pole.

"Relational methodologies" such as "lattice matrices, graphs and correspondence analyses" are proposed as an alternative to "general linear models". There is no footnote here. The potential for a radical innovation in methodology is one of the motivating ideas behind Mycorrhiza that I have interpreted as "something" between "agent-based modeling" \(science view\) and "multi-agent systems" \(engineering view\). 

I really like this next paragraph. One of the better modern statements of the need for social change. He's clearly read his Marx.

> The point I want to make, however, is not so much about the emergence of social structures, but about their reification, alienation and domination, which presuppose both the existence of social entities and their emergence. Relational sociology does not have to ignore the existence of alienated social structures that are out of control. Those are like “standing waves” (Abbott 2001, 263)— human-made, pseudo-natural, tsunami-like processes that will most probably engulf their producers if they remain unchecked. At the bottom, those crystallizations and reifications are human processes; yet they are also inhuman structures that follow their own laws and have their own dynamics. Precisely because they are threatening and alienating, we need to be able to conceptualize them both as structure and as process. As structure, because if we deny their existence, we cannot properly investigate their inertia, their mechanisms, their operations, the threat they pose to human existence. And as process, because if we want to change their course, channel and redirect them, we need to continuously remind ourselves that they only persist to the extent that they are continuously reproduced or, to give a more activist slant, that we let them reproduce themselves and do not actively try to transform them.

One more:
> For political reasons, I would now argue that both structuralism and processualism are necessary and complementary. To change the world, we have to know what the structures are and how they function; and—sign of the times(!)—in order not to be tempted by despair, we also need to be able to understand these self-same structures as processes that can be canalized, redirected and changed.

The following almost directly maps relational sociology to double categories and uses similar terms (coincidence?). Vertical morphisms are "functionalist" here and "functors" or "tight" in double categories. Horizontal morphisms are "interactions" here and "loose" in double categories. The proposed "transversal relation" would map to 2-cells, but may need to be understood as a triple category to really make this work, as the proposed relation between "interactions" and "systems" may require relating processes between 2-cells

> Before I proceed to make my case, let me visualize the dimensions in spatial terms and suggest that a complex social theory needs to integrate three types of relations into a well-articulated triptych with moving parts: a horizontal relation between “people” interacting with each other (the lifeworld of the phenomenologists); a vertical relation between “parts” of systems, floating above the head of the actors, constructed by the analyst, conditioning the actors’ practices (the system of the functionalists); and a transversal relation that relates the constructs and concepts of the analyst to those of the actors themselves, and both to the reality they refer to (the reality of complexity theory).

I was so impressed with Vandenberghe's essay that I downloaded his book *For a New Classic Sociology*. I also went through their Google Scholar page and did not find any significant follow-up to this essay. 

The contrast with this book and the relational sociology paper couldn't be more stark. Instead of building on the concept of the relation and/or interaction, the book advocates for a social theory built upon the anthropological notion of the gift. Although it would be possible to develop the notion of the gift with semiotics and thus to relation, it seems very human-centric. It's hard to imagine such a concept applying to even social animals, although perhaps activities like mutual In contrast, as Vandenberghe touches on and Frega develops in greater detail, the concept of association was though by Dewey and others to transcend the social and apply to the physical world. Perhaps the main difference betwen social theory and social philosophy, since the former dwells explicitly with the academic division of labor whereas social philosopher have some potential commitment to other parts of philosophy. Peirce developed semiotics as a concept that could cross among various parts of human knowledge.

I also read Testa's essay in *Habit* that compared the concept of habit between cognitive science and social theory. He highlighted the same hendriatis of habit, custom and institution that Frega highlighted and that seems close to Poinsot's notion.

# Social epistemology and social inquiry

How can Peter Senge's notion of the "learning organization" be applied and expanded to help deal with our polycrisis? Large-scale systemic change is clearly necessary, but can Dewey's "method of intelligence" be applied in time to avoid the worst? If social epistemology is the aspect of social philosophy that deals with "social intelligence," are there practical ways to improve social organization that can avoid traps such as bureaucracy?

Social inquiry fits Lincoln's hendriatis: Inquiry by society, inquiry for society, inquiry of society (understanding the last "of" as "into"). Society is the object, the instrument and the purpose of inquiry. The term "learning organization" does not stress the reflexive dimension as much as "social inquiry".

Technology clearly plays a key role in social inquiry. The "built environment" as the cumulative efforts of social poesis can be the object, instrument and purpose of inquiry. 

What should the interaction of sociology and technology be called? It's interesting how different the connotations of these words. Techne clearly has its roots in Greek and was a major category in Aristotle. We have "technology" and "epistemology" but no equivalent for "phronesis". One could argue that adding "ology" to techne and episteme is redundant since these are already forms of knowledge. It seems like "sociology" could occupy this space.

Googling "sociology phronesis" came up with a number of hits. One article was *Examining Normative Sociology and Phronetic Social Science in the Light of Practical Reason*. The title implies a translation of "phronesis" as "practical wisdom" or "practical reason". The article was published in "Civic Sociology"

Summary of phronetic social science:
> phronetic social science is a transformed social science that is “done in public for the public” (2001, 166), predominantly concerned with enhancing deliberation on what is desirable (2001, 129, 167) by increasing our ability “to think and act in value-rational terms” (2001, 130). 

This almost perfectly describes a reachable goal for a "pre-assembly" around decarbonization. The recommendation for a citizens' assembly based on values rather than on policy seems somewhat related.

 Tsilipakos points to the limitations of the university setting in developing practical reason. Is there an alternative institution? Did Aristotle recognize the assembly as an institution for developing practical reason? If not, was this due to an anti-democratic bias?

 Perhaps part of the problem is thinking of an academic discipline as restricted to any of these forms of knowledge. Every institution develops some form of practical reason, and an institution focused on developing practical reason would necessarily rely upon symbolic knowledge and material objects. Tsi discusses the Jesuit curriculum designed to foster practical reason using casuistry, or case-based reasoning, an approach that is still used in applied ethics.

 The pragmatic notion of habit and it's social aspect of custom seems very related to this notion of "practice". The related notion of "ethos" and it's use as "ethics" connects this connection between habit and practical reason. The relationship between "character" and "habit" are again quite close, as "character" can be considered the collection of "habits". The "habit of changing habit" is perhaps most easily applied to thought, less so to making and perhaps least so to doing. This "thinking, making, doing" hendriatis has the benefit of not making these separate domains. Pragmatism in general does not often distinguish between "making" and "doing."

 Peirce marked out ethics as the second normative science, but this seems like the "episteme" of "phronesis". T.L. Short's article *Normative Science?* describes ethics as what we ought to to and aesthetics as what we ought to desire. Peirce believes that these are "norms to be discovered through observation". Ethics under Peirce 
 
 >is a more general study of how rules of conduct may be adapted to the ends adopted, whatever those ends may be, and that logic is not based on any moral view but is best conceived of as the ethics, in the preceding broad sense of that term, of inquiry.

This notion of end as a "desire" is reminiscent of Castoriadis' "imaginary". 

> According to Robin, inquiry into inquiry's aim belongs to what Peirce named 'esthetics' and inquiry into the methods for achieving that aim belong to the 'ethics' of inquiry... Robin set up a dialectic between the norms of science and the science of norms.

Or the norms of inquiry and the inquiry into norms, to echo the parallel construction with social inquiry above. 

An inquiry into what we must do must be governed by the norms of inquiry, and these norms are discovered by inquiry. In this way, my use of "social inquiry" is wrong - it is an inquiry into what we should do.

Short claims that Peirce anticipated the position that observations presuppose theories. EP2:Ch.16 on perceptual judgement and EP2:Ch.6 for a critique of positivism.

# Artificial sociology

Gemini has a nice explanation of artificial sociology that I won't repeat here. But the sociological tradition has a long tradition of skeptical examination of "rational" theories of action that were inherited from economics. Since these ideas have strongly influenced current developments within AI, there should be material from sociology that can be applied to the design of agent-based approaches. Note that "agency" has fully crossed over between the natural and technological domains, perhaps due to years of work by AI researchers. Gemini places agent-based modeling within this field but doesn't discuss the design applications. It could be that "computational sociology" could explore the relationship between agent-based modeling and multi-agent systems more systematically.

Wikipedia has a good entry on (computational sociology)[https://en.wikipedia.org/wiki/Computational_sociology]

Wikipedia also has an entry on (agent-based social simulation)[https://en.wikipedia.org/wiki/Agent-based_social_simulation]. This entry places this tradition within the series on (multi-agent systems)[https://en.wikipedia.org/wiki/Category:Multi-agent_systems] that includes pages on multi-agent planning and multi-agent reinforcement learning but not agent-based social simulation. 

I found an old paper by Steve Woolgar entitled *Why Not a Sociology of Machines* [@woolgar:1985:why]. Woolgar worked with Latour in the early days of Science and Technology Studies. Woolgar worked with Latour to develop actor-netowrk theory and this paper applies this perspective to artifical sociology. 

A forward search from this reference in Semantic Scholar gave 135 citations, so a somewhat influential paper. There were several papers by A. Rezaev that referred to "human-centered artificial intelligence". This is the focus of the (Stanford group)[https://hai.stanford.edu/] that did the AI trainings for government workers last year. 

One relatively highly cited paper was *A sociotechnical perspective for the future of AI: narratives, inequalities, and human control*. This paper focuses on the human side of the divide and places the applications of sociology in the design of artificial societies as "computational social science."  

I had identified Pitt's work (self-organizing multi-agent systems) as a major contribution to using social science in the design of multi-agent systems. 

# Artificial phronesis

This goes in the category of "if I can think of it with my limited understanding, it probably already exists". There is an existing literature on this subject. Looks like a lot of this is in a single-agent context. My understanding of phronesis is that it's closely related to ethos and involves acting correctly in social situations. In this context, "natural" phronesis would connect to phronetic social science.

Much of the AI alignment issues seem to be related to creating ethical, pro-social robots. Teaching phronesis to robots may be extremely important in teaching it to humans as well. If phronesis (as a pro-social logic of cooperation) is key to socialism, developing cyber-physical-social systems that are high-quality and meet ecological,social and cultural needs will be necessary to getting out of capitalism. Can cooperation be elevated over competition as the main guiding principal of economics, society and politics while still being robust and aware of "competitive games"?

# Participatory Action Research

Was writing the section above on "artificial phronesis" when I went to check my email and got something from the EPA Participatory Science workgroup. There are "community cafes" scheduled and I wondered about the relationship between "citizens' assemblies" and "participatory science". There wasn't a lot of directly relevant articles, as in general these two ideas don't have a lot in common, as citizens' assemblies are overly focused on sortition-based approaches while "participatory science" is focused on using your volunteer labor but not necessarily on action (aka decision making)

Participatory action research is somewhat focused on combining inquiry, participation and action. There is a potential link to Dewey's analysis in *The Public and its Problems* as a model of public inquiry. Dewey did not emphasize the participatory side, but this notion of participation seems important. George Monbiot emphasized the notion of "belonging" in the development of left alternatives, but the notion of "participation" seems to include this while still allowing for conflictual elements.

> While a common denominator, the combination of participation, action and research reflects the fragile unity of traditions whose diverse ideological and organizational contexts kept them separate and largely ignorant of one another for several decades. 

The Wikipedia article emphasizes the connection with action research in the workplace and the role of the Tavistock Institute, which I've encountered in looking at sociotechnical systems. There is also a connection with "organizational development" that was let by the National Training Laboratories in the US.

The Wikipedia article mentions two initiatives blending PAR with ICT: open-source governance and e-democracy. Also references a John Forester book called *The Deliberative Practitioner*. (sadly, not Jay Forrester)/

Forester is a professor of city and regional planning at Cornell University. It appears that he has continued to work in public planning as collective action. His introduction to the edited volume *On Theories and Practices of Collective Action and Sustained Cooperation* brings up the parallel notion of "sustained cooperation," which has an institutional flavor. 

The Wikipedia article does not discuss the potential impact of RLMs on PAR, nor on the potential to train RLMs to assist with PAR. 

# Critical systems theory

I listened to a *Future Histories* podcast featuring an interview with Jan Overwijk about his book *Cybernetic Capitalism*. He posited a transition between a "technoscientific imaginary" based on "thermodynamics" (or machines) to one based on "cybernetics." I'm not sure about the latter designation, as his explanation on the podcast seemed to emphasize the post-structuralist emphasis on monism and hybrids rather than the first-order cybernetics outlined by Mirowski in *Machine Dreams*. What it largely reminded me of was the distinction between a category and a co-category, or perhaps more prosaically an algebra and a co-algebra. The complex relationship between a double category and it's opposite developed by Evan Patterson might be a richer model than the Heyting/co-Heyting duality that I had promised myself that I would work on due to reading about the actor model of computation and Carl Hewitt's work on non-explosive "inconsistency-friendly" logic.  