---
draft: true
title: "Adjoint logic and digital municipal socialism"
author: "Brad Venner"
date: "7/28/2025"
output: html_document
---

Spent the weekend thinking about and talking with Nic about municipal socialism and reading Kolasi's *The Physics of Capitalism*. Not sure how much progress I made, but I'll use this entry to keep track of any arising thoughts.

Nic expressed a general skepticism about thinking about digital municipal socialism as "the mother of all applications". He encouraged me to be skeptical of trying to build too much and to use existing tools when possible. 

I was listening to an interview with Samuel Moyn on *Behind the News* and they quoted Linda Miller saying that focus on local action (such as municipal socialism) would almost by definition not be sufficient to avoid the need for national action. I think this analysis misses two things. First, there is great skepticism in the US about the role of government and that socialists have to aknowledge and refute this skepticism by proving that "universal services" can enhance the quality of life for the vast majority. Second, new municipalism explicitly embraced the notion of a network of municipalities sharing solutions among each other (such as software). An a priori local/global distinction misses the "cartesian" semantics (i.e. copying is possible) of an open-source platform that can be modified and improved over time.

Nic also pointed out that every municipal socialist project will immediately be under attack by the capital order. This will be harder for US municipalities to defend against than for independent nations, since there are fewer tools of autonomy granted to the former. Digital tools can potentially help build autonomy that could resist this attack, but it will be an uphill battle. So it might be easier to build voluntary democratic systems such as a citizens' assembly and to iterate on these implementations prior to siezing power. So can municipal socialism be a long-term goal while avoiding engaging the electoral system? But sole focus on the "civic sector" would leave Mamdani out to dry and neglects the urgent need to develop practical tools to build an assembly to support "actually existing municipal socialism" ASAP.

One slogan I though of was "sovereignty, solidarity, sustainablity," which roughly corresponds to democracy, society, ecology in democratic eco-socialism. I like the new slogan as it's more action based. Google Gemini has a great development of this concept that's worth quoting in full.
  
One project would be to watch the *Build and Fight* webinar series from Cooperation Jackson on an accelerated time frame to catch up with the monthly series. We've talked about hosting dinners for some time and this might be a good structure. Probably should watch at least one before opening this to other people to make sure that they don't totally suck.

Another organization of interest that was covered by a Current Affairs podcast is UNFTR (unfuck the republic), which has 5 non-negotiable demands. It would be interesting to compare the Build and Fight program to the non-negotiables. The former is clearly a longer-term project and includes a number of more anarchist/associationalist threads, while the non-negotiables are more classic top-down policy programs.

# Lempert on ABM in deep uncertainty

A blast from the past. Lempert wrote a paper on deep uncertainty that made a profound impact on me. I believe this was shortly after 9/11. I met with Leslie at 240 Union some time after this. Anyway, he wrote a short introduction to a 2001 Sackler Symposium (yes, that Sackler) that combines his insight into modeling methods for deep uncertainty with the use of agent-based models [@lempert:2002:agent].

Lempert points out that agent-based models are most useful when simpler (more mechanical?) models fail to capture the situation. Lempert argues that these are situations of "deep uncertainty". But in these cases, the usual justification of model-building to "make a decision" does not hold. Lempert argues that ABM should be used in a multi-scenario mode and to look for "strategies" that are superior across a range of scenarios, without needing to be best in every single scenario. These "robust strategies" are typically adaptive.

I don't necessarily see how Lempert distinguishes from this approach and more conventional single-agent Markov decision processes (and reinforcement learning as a special case of approximate dynamic programming), which also can produce adaptive strategies. Perhaps the extention to multi-agent reinforcement learning can help motivate the necessity of the move to agent-based modeling. There is a related notion in the Bayesian literature where "robust Bayes" can be interpreted as a decision procedure that works over a variety of priors. 

I believe that Lempert's analysis can be extended to institutional analysis and design, where not only are agents working to find a strategy over a fixed environment but where the "institutions" themselves emerge out of agent interactions. Thus, the outcome may not be a "robust policy" but a "robust institution" where the forms of communication, decision-making and shared values are also transformed from some initial baseline. From robust strategies to resilient institutions.

# Browne on social theory and political imaginary

I had added this book to my "Libgen tasks" a while back. Browne works both with "creative democracy" and "democratic creativity". In this book, he tries to develop a notion of social theory that is informed by the notion of political imaginary.

Transformational design of cyber-physical-social systems requires a relatively deep inter-disciplinary perspective. I'm still hoping that categorical semiotics can provide the core for these inter-disciplinary transformations. I've looked at work from computer science (ajoint logic, behavioral types), biology (biological organization), artificial intelligence (self-organizing multi-agent systems, cognitive agents), and sociology (social ontology, collective autonomy). It is clearly a limitation of the idea of cyber-physical-social systems that biology is not explicitly located and why ecological-social-democratic systems could be a better formulation, although explicit identification of the role of information is a benefit of the latter. Ultimately, Aristotle's trinity of praxis-poesis-theoria could still be best. 

The concept of the political is like a representation of the social to itself. But he also includes Catoriadis' idea of a subtantive understanding of the political as also about the "ends" or "purpose" of the society and how institutions can be developed to realize these ends (institutions as means?)

Browne paraphrases Boltanski and Thévenot in *On Justification: Economies of Worth* as stating

> the construction of collective agreement is a process of enacting a particular *cité* or polity that addresses injustices according to normative political principles and which contains a shared "higher common principle" ... *Cités" represent general schema or 'grammars' rather than precise and definitive models. 

There seems to be some overlap between this concept and Ostrom's "institutional grammar". Because there are multiple, overlapping cités that could potentially conflict, does institutional analysis need some form of paraconsistent logic to make sense of these "contradictory" demands? There's also Rosen's understanding of complex systems as allowing or requiring multiple models. This essential idea of plurality seems well suited to an "adjoint logic", although both "classical modal" and "substructural modal" approaches are probably required. 

> The synthesis of the subject and history in the constitutive form of praxis, that is, the process of the emancipatory tranformation of social structures and institutions by subjects who transform themselves in the process, was at the core of the political imaginary of the philosophy of praxis.

Don't know if Browne is using "the philosophy of praxis" in the Marxian sense, but this is a nice summary of my "political imaginary" of a digital citizen's assembly. 