---
title: "Thoughts on Measurement Systems"
author: "Brad Venner"
date: "3/18/2025"
output: html_document
---

Conventional metrology assumes a substance-attribute ontology. Peirce analysis of the proposition implied that the relationship between a proposition and a sign was something like a subtype. However, there is also the idea that a sign could be something like a morphism of propositions. In this case, a double category might be a better model.  Analysis of "semiotic systems" would be a special type of "system". This would place the analysis of "semiotics" within the double categorical approach developed by Myers.

There are at least three other major approaches to categorical systems theory in addition to Myers' work that might be better suited to this analysis. First is the "catcollab" system. This builds upon Patterson's work on "functorial semantics" in double categories. This approach seems closely related to Myers' work, but the exact relationship would need to be worked out. The advantage to using this system would be that potentially CatCollab could be used as an interface.

A second approach is using actegories. I wrote about these last month, but these have a close relationship to both message passing semantics and to "mathematical informatics". It seems like the general double category framework might be sufficient to handle these cases, although this could be complicated by the fact that a monoidal category is already a double category and that might place an actegory into a triple category framework. Just looking on LocalCharts, [Paul Wang](https://www.localcharts.org/t/nondeterministic-behaviours-in-double-categorical-systems-theory/33524) describes Myers' double categorical systems theory as a "monoidal double category". This framework of "nondeterministic behaviors" might be a good match for measurement systems as it includes imprecise probability.

# Substance-attribute ontology

Relational quantum theory attempts to relativize the notion of "state" in quantum mechanics. Topos quantum theory attempts to develop a "realistic" view of quantum systems but strangely takes "actuality" (i.e. boolean propositions) as "real". It seems like Peirce's triadic (modal) notion of reality could be a natural fit to a topos-theoretic view of quantum systems. At the "propositional" level of a topos, the modalities of possibility and necessity (may) correspond to intuitionistic and "dual" intuitionistic logic. The caveat "may" is important because it's not clear whether the "lattice dual" or the "algebra dual" (i.e. coalgebra) should be used here. Is it a co-Heyting algebra or a co-Heyting coalgebra.

Ellerman's work seems important here, as he attempts to "dualize" the "logic of parts" into the "logic of partitions". Ellerman also works with relational models of quantum systems, although I'm not sure if he has related these two aspects of his work. 

Mari's semiotic measurement system theory, in a manner consistent with metrology, considers measurement as the determination of a quantitative attribute of a substance. 

Aristotle 

Kant considered substance as the "thing in itself"

Peirce's theory of the proposition considered it as a special type of sign that "indicated" it's object. The notion of index is crucial here, as it no longer refers to an ontological notion of "substance" but rather on the ability to share a reference to a "space-time region".

# Performance characteristic

Wikipedia has a page for "system quality attributes". Th