---
title: "Thoughts on Linking Categorical Systems and Measurement"
author: "Brad Venner"
date: "5/1/2025"
output: html_document
---

One basic design question for my proposed "course" would be how to link a more abstract understanding of "measurement system" with a more practical section on "measurement systems analysis" (what Mari calls semantics, or the object-relatedness of a measurement system). Although I like Mari's narrative development of their system, I'm not sure that this would be the best way to present the material. I've tended to think about beginning with more concrete systems that students would be concerned with (such as grades) and develop more abstract understanding over the course. This does parallel Mari's development in a way, but the resistance to introducing a more explict semiotic framework until the last chapter seems like a weakness. Mari also does not include an explicit link to systems theory, which seems like a missed opportunity, since "system" is an explicit primitive concept in the VIM, unlike sign (which is called an "indication"). So does it make sense to introduce an abstract conceptual framework early in the course? Mari develops a "problem-focused" preliminary definition of a measurement system early in the book. This could be modified to include an early introduction of the term "system" as something that's preserved across transformations (i.e. system under measurement, measuring system, interpretant system) rather than the object/property primitives that Mari brings in from metrology. 

One way to link a more theoretical focus on measurement systems, developed within categorical semiotics, with a more applied "measurement systems analysis" could be through the use of $Para$ and the categorical systems theory that has grown up around Hedges. Cappucci crosses between this and Myers' double-categorical approach. Since $Para$ was developed for use in machine learning, and there is a strong link between machine learning and measurement systems (controlled calibration looks very much like supervised learning, and non-targeted analysis looks like unsupervised learning), it should be relatively straightforward to explicitly link the two. On the other hand, although the "neural network" does provide a black-box approach to modeling the relationship between object and indication, I'm not sure how a neural network would handle "general inverse" problems. This is probably an essential problem with black box models and probably points to limitations with pure black box measurement models.