---
title: "Resolutions on New Year's Day"
author: "Brad Venner"
format: html
---

# Physical

1.  Commit to strength training. Goal would be to maintain muscle mass and bone density. Emphasis on weight-bearing multiple joint exercises. Use grease the groove techniques.

2.  Get knee examined. Go to physical therapy and try to prevent any future injuries. Try to avoid chronic knee pain.

3.  Get greater consistency on meditation practice. 

4.  Clean major areas of chaos - garage, furnace room, Nic's room, 

5.  Find good home for birds or build outdoor aviary.

# Social

1.  Identify online social groups consistent with my interests and find ways to participate and contribute. For example, 
    a. the (International Network for Democratic Economic Planning)[https://www.indep.network/] for economic democracy, 
    b. The (Mind and Life Institute)[https://www.mindandlife.org/] for cognitive science and meditation (or perhaps Upaya Zen Center), 
    c. the AI Objectives Institute for socially-minded applications of AI.

2.  Identify offline (local) social groups and find ways to participate and contribute. This could be local chapters of national or international groups. It could be starting a local group focused on one of my interest areas. 

3.  Continue to work on my relationship with Marie. Strive to make this my most important relationship and to be open and honest. If we do not continue to do marriage counseling, perhaps do books on tape, read books out loud, or do other activities to develop a shared understanding.

# Work

1.  Find a way to "institutionalize" uncertainty practices. This could be developing a short course on measurement uncertainty analysis. Perhaps work

2.  Find a project to do in Rust. Perhaps this could be designing measurement systems in CatColab.

3.  Move workflows from RStudio to VSCode. See if I can implement 

