---
title: "Bogdanov and self-organization"
author: "Brad Venner"
date: "2025-02-01"
format: html
---

# Adding cybernetics

Should I add "cybernetics" to my project "Dialectics Semiotics Systems"? I've tended to think of cybernetics as a special case of systemics, but if I formulate this project as an intellectual history, does it make sense to explicity include it. The Wikipedia article on "self-organization" credits the introduction of the term to W. Ross Ashby. I've been thinking about self-organization as part of my recent "study" of *Self-Organizing Multi-agent Systems" by Pitt. On the other hand, I'm not including "information" in my list, so I could include cybernetics as influenced by information theory. I'm also not including other concepts like "autopoiesis," so any list of concepts will be somewhat arbitrary. 

If I credit "dialectics" to Hegel, I'm really looking at 200 years of work, so the meta-concepts will have lots of sub-concepts, flows between concepts, etc.  

# Bogdanov from dialectics to organization

Bogdanov is a key "boundary thinker" between dialectics and systems, which is the title of this article. 

Bogdanov relates metaphysics to productive systems. Fuedal systems have a strong distinction between "organization" and "executive" functions, which leads to a dualistic metaphysics. Capitalist systems adopt "metaphysical monism", which results from the division of labor under capitalism.567yipo\above 
 
> Nature and spirit represent simply different levels of organization in a continuous monistic hierarchy. (p. 45)

> This focus on "organization" led Bogdanov to downgrade the importance of the "dialectic" in his system. For most of the Marxist tradition, the term dialectic refers first and foremost to the inter-connectedness and holism of matter. The principle of contradiction is simply an implication of this relationality and holism. (p. 46)

> All human activity for Bogdanov is organizational in character. Work is the "organization of the external forces of nature." Politics is the "organization of human forces." Knowledge is the "organization of experience." "Mankind has no other activity except organizational activity, there being no other problems except organizational problems (Bogdanov 1928/1980: 3). (p. 47)

> The struggle for socialism is not at all embodied in a single war against capitalism and in the simple collection of forces for that task. This struggle is a positive and creative work - the creation of the new elements of socialism in the proletariat: in its intemal relations, in its unifying living conditions. It is the working out of a socialist, proletarian culture (Bogdanov in Rowley 1987: 284).

The author of this essay is Anthony Mansueto. He is a scholar of religion and (still!) maintains a (blog)[https://seekingwisdom.com/blog/]. 

# Pitt, SOMAS, Chapter 1

Pitt defines the event calculus, which he has stated he will use throughout the book, as a multi-sorted first-order predicate logic. 

Pitt distinguishes between 

# Pitt, algorithmic reflexive governance

Hard to imagine a more contra-Castoriadis title than this one. Castoriadis put great emphasis on the role of imagination in the design of institutions. Yet the goals of the two projects seem aligned - reflexive governance and collective autonomy have a family resemblance.

> Reflexivity, generally, is the ability of a structure, process, or organisation to reconfigure itself in response to reflection upon its own performance.

Castoriadis puts creativity at the center of a reponse to a realized deficit, following pragmatism in spirit. C's analysis of "substantive democracy" places 

Peirce has a more cynical view of "reflection" in considering the persistence of habits. Creatures don't want to "really" think and feel like this is an unstable state that they would like to get out of. Much "thinking" is habitual, as habits of belief are still habits. A true "pragmatic crisis" requires a creative response as existing habits are felt to be inapplicable.  

A detailed analysis of "creative democracy" and "collective autonomy" remains on the to-do list. It seems like Joas could play an important role in updating some of Dewey's conceptions. Could I follow Pitt's example and look at formalizing Joas' sociological theory and Dewey's theory of inquiry?

But can systems be developed that lower the cost of reflection/problem solving? Peirce identified this capability as the "habit of changing habits".

Back to Pitt. Four dimensions of reflexivity are modeled, each with two "poles". Each dimension is solved by an algorithm. The notion of "algorithm" is used in a somewhat esoteric manner to mean something like "governance process". Us Rosenites have a somewhat specific understanding of algorithm and think of it as a non-living process. Obviously an open question if these "algorithms" are as mechanical as Rosen argues. Of course, Pitt is most interested in implementing multi-agent systems so these ideas have to be computable. Semiotics doesn't have the same problem with the notion of machines processing signs or humans relying on machines to make signs.

| Dimension | Pole 1 | Pole 2 | Algorithm |
| --------- | ------ | ------ | --------- |
| Sources of knowledge | public participation | expertise | relevant expertise aggregation | Ober |
| Composition of public discourse | diversity | consensus | interactional justice | Pitt |
| Institutional architecture | polycentricity | centralization | zone of dignity | Ober | 
| Institutional dynamics | flexibility | stability | quasi-stability | Rawls |

## Refle