---
title: "Notes on A Relational Theory of Measurement"
author: "Brad Venner"
date: "4/17/2025"
output: html_document
---

The "relational" or "relative" theory of measurement plays a key role in Krechmer's quantum measurement theory [@krechmer:2016:relational]. Since Hewitt suggested that the actor model of computation was inspired, in part, by relational quantum mechanics, it's interesting if these two relational theories could be related (lots of relations!). 

I'm also intrigued by the centrality of "non-transitivity" of measurement in the theory, as this suggests measurement models with something like virtual double categories. It would be particularly interesting if "representational measurement theory" was modeled in regular double categories, since Mari suggests his approach could be considered an extension of this theory.

Since lax functors between double categories have been proposed as a central construction in categorical systems theory, there is potentially a nice relationship to a (virtual) double  approach to measurement systems and categorical systems theory.

Finally, I'm interested in the potential to understand "properties" as "functions" (or functors in a double category). Extensional set theory proposes that a "property" of a set are in correspondence (what correspondence, exactly) to a (characteristic) function to 2. Lawvere seemed to propose a more expansive concept of property in his *Sets for Mathematics* [@lawvere:2003:sets], which I understood to have proposed this idea. In the relationship between logic and double categories, the "tight arrows" correspond to terms, but it seems like they could be understood as attributes given the induced "functional dependence" of the two objects.

# A relational theory of measurement

Mari defines quantity as the quantitative property of an object, while the VIM definition uses "substance-attribute". Reminds me of Deely' objection to the inversion of subject and object in later philosphy.

Mari states that functional modeling is implied in the representational theory of measurement. They summarize the theory as the notion of a mapping between an "object set" $A$ and a "symbol set" $X$, and that quantities are identified with functions $m:A \rightarrow X$. They then factor this measurement using the partition (i.e. equivalence class) induced by the function. This  into a "classification function" from A into the equivalence class induced by $m$, and a "labeling function" that is one-to-one between the partition and $X$. 

I believe that Mari defines a "general quantity" as the class of morphisms from A to X and a "specific quantity" as a specific morphism such as $m$ above. Could be a similar distinction in a logical system between a "specific term" as relating elements from two different objects and a "general term" as something more like a function type?

Surely someone has already developed "categorical measurement theory" as a more-or-less straightforward generalization of "representational measurement theory"? Seems like Rosen's book *Fundamentals of Measurement and Representation of Natural Systems* [@rosen:1978:fundamentals] could easily play such a role. I need to get off my ass and read this book. Rosen's book was published in 1978, 7 years after the first volume of *Foundations of Measurement*.

The basic idea is that there are empirical relations among the elements of $A$ that must be preserved by the morphism to $X$. But this seems much closer to the notion of a functor between categories and not like the atomic elements of a set.

The relational theory uses the same notion of factorization system, but instead of assuming that $m$ is known so that the equivalence class can be deduced, the first part of the factorization corresponds to an experimental process, while the second step corresponds to the "calibration" of the measuring system.

Taking a break to go home. Will pick this up tomorrow.

The strange thing about this paper is the lack of emphasis on the substance-attribute ontology. If the goal of measurement is to preserve the empirical relations between attributes, then why aren't these empirical relations included in the model? The proposed equivalence relation based on the "measured attributes" also does not obviously preserve any of the proposed empirical attribute structure. There is the structure of partitions in a "quotient logic" but this seems to have more to do with the measurement scale.

I seem to remember that there is a notion of addition in the measurement theory and that the goal of a scale was to preserve this "monoidal structure." So I'm not sure that Mari's presentation of this material is as "categorical" as it could be. But there is suprisingly little on "non-quantum" measurement on Nlab. It also could be that *Measurement Across the Sciences* could be more categorical (in addition to more semiotic) than this paper.

Mari introduces the notion of "reference objects" $A_R$ that are a subset of A and that there are a set of reference objects $A_{Ri}$ that are distinguishable (i.e. $!(m(A_{Ri}) \simeq m(A_{Rj})) if i \neq j$). \,j       =03
# Measurement systems in Julia or Rust

I was thinking last night about whether to do the measurement systems project in Julia or Rust. Some advantages with Julia is that it's a simpler language to pick up than Rust and it has some fairly well developed statistical packages that could potentially ease the transition between the (projected) more theoretical "systems" parts and the more practical "analysis" parts. In Julia, the overall project could fit in the "Algebraic Julia" ecosystem. In particular, the ACset data type could be a good fit for defining a substance-attribute ontology where there can be relations between substances. 