---
title: "Notes on Technology as Capital"
author: "Brad Venner"
date: "1/14/2025"
output: html_document
---

This paper was brought to my attention by ResearchGate this morning. The initial paper by Roos and Hornberg was critiqued by David Schwartzman; their reply was highlighted by ResearchGate. This exchange can also be taken as a critique of this tradition or related energy democracy efforts. Since I have aligned myself with this tradition, there is a "breakfast of champions" quality to this paper.

The three papers are:
1. Technology as Capital: Challenging the Illusion of the Green Machine
2. My Response to Roos and Hornborg, Technology as Capital: Challenging the Illusion of the Green Machine, Schwartzman
3. Challenging the Green Machine: Rejoinder to Schwartzman

Roos is affiliated with *The Center for Political Ecology* at Lund University. It may be fair to take Roos as a representative of the *ecosocialist degrowth* movement.

Schwartzman is a retired professor of biology who spent his career at Howard Universtity. They appear to have spend their retirement on ecosocialism - could be an interesting person to talk to. 

Schwartzman's rejoinder rejects the ecomodernist label placed on him by Roos and Hornberg. TaC only had one paragraph dedicated to Schwartzman, compared to two pages on Leigh Phillips (of the Breakthrough Institute - a questionable allegiance for a Marxist scholar) and 4.5 pages on Aaron Bastani, who's book *Fully Automated Luxury Communism* leaves little doubt about their allegiance to ecomodernism. Furthermore, Roos only cites a 2008 paper and negelect the 2019 book *The Earth is Not for Sale* by Schwartzman.   

Roos uses a Trumpian argument style, making indirect insinuations rather than direct argument ("some people say ..."). The TaC paper says "Other (energy researchers) have focused on their comparatively low *net energy* or EROI" as a way of casting aspersions on solar energy without directly making the case. Although I don't have Schwartzman's response, the rejoinded brings up EROI indirectly again, stating "It has long been discussed whether some modern energy strategies, including biofuels and solar photovoltaics (PVs), fulfil the criteria of having a high enough EROI ratio to be able to sustain modern high-energy societies." They subsequently bring up the importance of boundaries in defining EROI but don't really negate their previous insinuations. Further, they cite a paper by Murphy [@murphy:2024:energy], which argues against the claim that these measures are context-specific, instead arguing for the standardization of measures and showing that mainstream renewable technologies have a better EROI than fossil fuel sources, directly contradicting the insinuations in their paper.