---
title: "Measurement and modeling in/of/for democratic ecosocialism"
author: "Brad Venner"
date: "6/10/2025"
output: html_document
---

# Measurement and modeling in/of/for democratic ecosocialism

The title implies both an expansion and contraction of the two projects of "measurement and modeling" and "democratic ecosocialism". I've been working on the former project both at work and in private, with measurement the focus of the work project and modeling the "focus" of the private project. The relationship between measurement and modeling is interesting, and a general hypothesis would be that modeling is what distinguishes measurement from evaluation. In VIM, measurement includes a model as an essential component.

I've thought of my future project with Mycorrhiza as developing agent-based social simulations/models for use in universal public services, beginning with energy and/or broadband. 

I listened to the audiobook version of *Less is More* by Jason Hickel while driving Elena's car to Everett. This book made me rethink my dislike of the degrowth framing. I've thought that degrowth plays too much into the notion of "generalized exchange" under capitalism. It also seemed very unlikely to be able to be implemented by democratic means as it would always be unpopular. For the former concern, Hickel essentially identifies "growthism" with "capitalism", so post-growthism (degrowth) and post-capitalism are synonyms. Although ultimately a positive alternative to capitalism must be developed, it's certaintly valuable to diagnose the problem. 

For the latter concern, Hickel's list of actions in Chapter 5, "Pathways to a Post-Capitalist World" felt like they could be much more popular than the name "degrowth" would imply. Hickel advocates for (universal public services)[https://jasonhickel.org/blog/2023/3/18/universal-public-services] as an essential component of the degrowth agenda. But for the majority of people, universal public services would improve their quality of life and therefore would not be seen as "degrowth". Mamdani's recent victory was based on an "affordability" agenda. The affordability gap has been increasing over many years and universal public services would be a means to address this gap. Mamdami focused on several such services, such as transport (free buses), food (community grocery stores) and housing (rent control). Many of his proposals stop far short of universal public services but are clearly on such a pathway.

# Substitution vs exchange in semiotics

Clara Mattei's paper on economics presents a "subjective" interpretation of Marx that reminds me very much of pragmatism. She says that "exchange is at the basis of any economic system." This made me think of the role of substitution in logic and what Peirce says about the primary role of "illation" in logic and his shift in thinking from algebraic logic, with the principle of substitution of equals for equals, with a more topological approach with the existential graphs. 

Philip Rose argues that illation is a relation of inferential growth.

Jules Hedges wrote a blog entry on modeling of emergence with lax functors. Is this purely a two-categorical notion, or is there a shadow of this relationship in Boolean or Heyting algebras. Hedges continues work with the CyberCat institute, which I have been neglecting due to my general distaste for game theory and preferring the Myers version. Nevertheless, this is probably still important work. There was a link to a paper on "Institutional Modelling" that was not free. I saved the paper in my semanticscholar library under CPSS. 