---
title: "Thoughts on Creative Democracy and Citizens' Assemblies"
author: "Brad Venner"
date: "3/12/2025"
output: html_document
---

I spent a fair amount of time talking with Nic about the Citizens' Nexus project on Sun, Mar 9. We agreed to write something up about the project, which has prompted me to think about democracy and what would improve its chances in the Trump 2.0 "administration." 

There is a temptation within the notion of a citizens' assembly to substitute one form of procedural democracy for another. I believe that a richer notion of the citizens' assembly is necessary. This leads me back to the notion of sortition. While the Greek's did use sortition for selection of office-holders, the assembly, the ecclesia, was open to all citizens. What is conventionally called a citizens' assembly more closely corresponds to a "boule", the council of 500 that prepared "decrees or law proposals" that were voted on by the ecclesia. This understanding may be a little off - there is a website called [Equality by Lot](https://equalitybylot.com) that looks at these issues in great detail. But the basic idea seems to be that the ecclesia was a self-selected group of citizens and that office-holders were selected by lot from willing participants in the assembly.



# Carl Hewitt

## Actor model of computation

## Paraconsistent Logic

Hewitt argues that any real-world knowledge base will be "inconsistent". He argues that because computers must interact with the knowledge base, formal methods must use paraconsistent logic.

Hewitt spent much of his career arguing against "logicists" in AI. His Planner system was explictly developed to argue against first-order logic formulations of the planning problem. Later, he argued against Prolog using the *actor model*. So his arguments against classical logic in "knowledge integration" is consistent with previous stances.

Unfortunately, Hewitt never took up category theory. His "direct logic" was a paraconsistent logic that he developed to be a minimal change from classical logic. For a variety of reasons, it seems to me that "dual intuitionistic logic" would be a better starting place for investigation. First, because the "modal" understanding of this logic seems to echo Peirce's ideas about a "logic of vagueness". Second, because it seems like this could serve as a basis for higher-order generalizations, including modal homotopy type theory.  