---
title: "Notes on Semiotic Information Quality"
author: "Brad Venner"
date: "4/15/2025"
output: html_document
---

Was reviewing Mari's paper *Quality of Measurement Information in Decision-Making* [@petri:2021:quality]. This paper layed out their semiotic framework for thinking about information quality. Their citation of the syntax/semantic/pragmatic triad from Morris made me wonder about the differences between Morris and Peirce on semiotics. I briefly reviewed a paper on the debate between Morris and Dewey that began with Dewey's article on Peirce's semiotics. This is something I'd like to explore in greater detail, as I can't say I totally understood the basis of Dewey's critique based on the secondary paper. So I need to get this paper when I'm home. *Peirce's theory of linguistic signs, thought, and meaning* published in 1946. Has 125 references on Semantic Scholar.

One of the citations was a book *How the Cold War Transformed the Philosophy of Science* by George A. Reisch. This might be interesting, both to better understand Neurath and Morris but also to better understand the fate of "logical empiricism" in the United States. 

If we think of information as the outcome of inquiry, then Dewey's theory of inquiry might put greater emphasis on the inquiry process in motion rather than the resting point of information. This emphasis on the dynamic quality of knowledge could also relate to the notion of induction or Beer's Level 5 of identity/purpose.

One more aside - Aziz Rana's podcast on The Dig highlighted the link between "identity" and "purpose". The US Constitution provides a purpose to the United States as spreading liberal constitutionalism throughout the world, but also helps citizens understand what the United States is. Rana expressed it more eloquently, but I hadn't really thought about the link between the concepts of identity and purpose. 

It might be helpful to consider the semiotic theory of "information quality" and compare it to EPA's "data quality" framework Letting 

# Notes on A Semiotic Information Quality Framework

Data is what is stored and information is what is retrieved (i.e. delivered to, presented to, and interpreted by the user).

ISO 25000 standards are known as System and Software Quality Requirements and Evaluation) (SSQuaRE)

This paper cites a paper by R. Stamper entitled "The semiotic framework for information systems research" [@stamper:1999:semiotic] as an example of an early application of semiotics to information systems. This article was not available on Semantic Scholar, but I did a Google search on the title and found a paper called "The Semiotic Framework" by AJJ van Breeman [@breeman:2010:semiotic] that compared the semiotics of Peirce and Stamper. van Breeman argues that Stamper's framework was based on Morris' semiotics (as was Petri's) and that there are real, substantial differences between the two. However, he points to the limitation of Peirce's framework (it's lack of treatment of interaction of signs, in general) and finds value in Stamper's framework. van Breeman co-authored a book *Knowledge in Formation* [@sarbo:2011:knowledge] that was quite explicitly semiotic in design. There are also multiple references to "organizational semiotics," another semiotic framework related to an area covered in systems theory. The Wikipedia article on [organizational semiotics](https://en.wikipedia.org/wiki/Organisational_semiotics) states that Stamper began this work in his 1973 book *Information in business and administrative systems* [@stamper:1973:information]. Stamper was trained as a statistician nd worked in industry prior to academia.

There is clearly quite a bit of conceptual overlap between "organisational semiotics", "management cybernetics", and "socio-technical systems". There are probably dialectical studies in this area as well. But this raises the question of whether either of these notions are more primitive. Cybernetics seems to accept "system" as a primitive and focuses on relations between systems, but "systems theory" wants to deal with compositional or boundary relations (or modes of interconnection) that are not strictly informational. On the other hand, the notion that a system is a whole implies that to be a system is to have an emergent property. If semiotics and information can be identified, then perhaps "system" is the primitive term and "semiotic systems" and "information systems" are special types. The Wikipedia entry on [system](https://en.wikipedia.org/wiki/System) cites Carnot as originating it's modern use in thermodyanmics, which means that broad concepts of information and system emerge at a similar time. 

Is this move to "information systems" taking me too far from "measurement systems"? For the purposes of the work project, almost certainly, but maybe not for post-retirement? An academic discipline of "systems science" is clearly embedded in a semiotic system and the "objects" of study can only be known via informational or semiotic processes. So these ideas depend upon one another. The origin of "system" as an engineering concept points to the idea that engineering and science are not separate pursuits but co-evolve. But "systems" concepts also arise in dialectics, and the study of ecology is conducted in large part by Marxian biologists that shape the notion of system. So again it seems best to treat the ideas of semiotics, dialactics, systemics, informatics, cybernetics as being mutually interdependent. But given their vast scope and the vast quantity of the literature, only an "information system" of great power could help any single person get a grasp.

One other use of "system" that perhaps derives from Carnot's first modern use was the notion of "philosphical system" that was used in German idealism

van Breeman proposes a broad purview for informatics aka information science, quoting De Tienne that information science has become:

> a confluence of studies in artificial intelligence, cybernetics, cognitive science, formal logics and other related activities that study how natural or artificial systems represent, transform and communicate information [@de_tienne:2006:peirce]

De Tienne's paper reviews Peirce's two theories of information and the potential of semiotics to provide "a general theory capable of unifying all existing information theories, notably by showing exactly what function each fulfills within a common spectrum of concerns." 

Googling Andre De Tienne shows that he is the director and general editor of the Peirce Edition Project and a professor of philosophy at Indiana University.

