---
title: "Abstract for Multi-Agent Simulation for Cyber-Physical-Social System Design"
author: "Brad Venner"
date: "1/21/2025"
output: html_document
---

I was asked to give a presentation at the NEIC Technical Information Exchange on May 20-22, with abstracts due on Feb 15. I'm thinking of presenting two abstracts. One will be on "Reconciling Top-Down and Bottom-Up Uncertainty Approaches using Taguchi Designs". I will develop the other abstract here.

# Jeremy Pitt

I found Jeremy Pitt's work while searching for multi-agent systems. Pitt is a *Professor of Intelligent and Self-organizing Systems* at [Imperial College London](https://profiles.imperial.ac.uk/j.pitt). Pitt has been working in the social-technical system domain for over 30 years (probably a little younger than me). His focus is on "self-organizing multi-agent systems" (SOMAS). He wrote a book in 2021 called *Self-Organising Multi-Agent Systems: Algorithmic Foundations of Cyber-Anarcho-Socialism*. His graduate student Matthew Scott was developing a framework for building SOMAS in Golang, although there has not been much recent activity on the [GitHub repository](https://github.com/MattSScott/basePlatformSOMAS). 

The link between self-organization and multi-agent systems is intriguing. I have not seen references to Pitt's work in the "digital socialism" space (Morozov), the "cyber-communism" space or the "democratic economic planning" space. The link to "self-organizing systems" brings in conceptual links to paradigms of biological organization, such as Leonardo Bich's [Biological Organization](https://doi.org/10.1017/9781009393959) [@bich:2024:biological] or Robert Rosen's [Life Itself](https://cup.columbia.edu/book/life-itself/9780231075657) [@rosen:1991:life]. It also reminds me of the *collective autonomy* project by Castoriadis, which tried to link self-organization and democracy.

The ongoing example in the book of a smart home in a community energy system makes this a good potential book to study in SwitchBox. Maybe I can get Nic/Mirri to join as well.

Reading more of the first chapter of the SOMAS book. Definitely reads like a personal monograph, with humorous asides in footnotes. Pitt goes over his history of personal involvement in multi-agent systems. Stopped reading at a physios/nomos division (i.e. laws are either physical or conventional). Made me appreciate my somewhat twisted intellectual journey that I could recognize this. It made me think that my SDS project might be helpful for thinking about SOMAS. In particular, semiotics seems like an essential discipline, since the tension between self-organization and multi-agency can only be resolved by a non-causal understanding of the relationship between agents, yet still rely upon a "natural" basis. Self-organization as a term is founded on the notion of "system," and Bogdanov's tektology and Rosen's relationalism made explicit claims that organization was the essential quality in distinguising "living systems." But Deely's history of semiotics shows that the "category of relation" was crucial in developing Poinsot's semiotics and Peirce developed semiotics within a "logic of relations". So in some important ways "systems theory" was a rediscovery of some of the key ideas in semiotics. However, I believe that contemporary "self-organization" a la Bich has a lot to contribute back.


# Notes

Why not TerminusDB? This is an in-memory database that supports different query languages. Can it be sufficiently high performance to use in a game engine? Are there ways to restrict the domain so as to improve performance (e.g. restrict arrow domains, don't use URLs, etc). 

Looks like TerminusDB is no more. Gavin has moved on to VectorLink.ai,=. which focuses on AI consulting. Sad. It also appears that there aren't very good or specific Rust bindings and these appear to be more primative than the "higher-level" bindings I would hope to see.  