---
title: "Accounting, measurement, valuation"
author: "Brad Venner"
date: "6/10/2025"
output: html_document
---
# Algebraic accounting models

Konstantinos R. Pertsemlidis has written a series of articles that all are essentially rewrites of his idea to reform accounting systems. I found these papers from a forward citation search from the book *Algebraic Models for Accounting Systems* by Ramboud et. al. [@ramboud:2010:algebraic]. I read his papers prior to the book because he emphasizes the syntax/semantics/pragmatic triad that also occurs in measurement theory. 

Locating accounting systems within a more general systems theory could pay multiple dividends. Much like measurement systems, accounting systems have aspects of both semiotics and systems. It makes sense to continue work on measurement systems as these can potentially be specialized to accounting systems. 

How are discrete-event accounting systems related to continuous business process systems? Is this a similar relationship between measurement specifications (aka measurement procedures) and measurement processes? Is there a similarity between measurement uncertainty evaluation and accounting measurement. I think a paper on "Accounting for Uncertainty" could explore this relationship. Although finance has embraced probabilistic methods, I've never seen an accounting measurement with an attached uncertainty. I really think that this could be a fruitful line of inquiry.

The relationship between semiotics and systems seems to be present in double category theory. Double categories can be thought of as a system of logic but they are also used as a logic of systems (as in categorical systems theory). These two inter-related aspects may perhaps be considered in the syntax/semantics duality, where the language-like aspects are considered as syntax (such as "internal logic") and the system-like aspects are considered as semantics. Double categories place an emphasis on "internalization" and thus may be particularly relevant for this syntax/semantic interpretation. Is there any relationship between this syntax/semantics duality and other dualities such as discrete/continuous, algebra/geometry or symbols/physics?  

I would like to better understand the relationship between Patterson's approach to double categories and Myer's categorical systems theory. 

## Logic of systems and systems of logic

Patterson's work on double categories emphasizes the logical aspect of double categories, while Myer's emphasizes the "systems" aspects. Clearly a systems analysis tool relies upon a "logic of systems"  

# Graded categories as double functors

The indomitable Evan Patterson had a blog entry last month entitled (Graded categories as double functors)[https://www.epatters.org/post/graded-categories/]. Patterson says that categories graded by monoids have been a central feature of (CatColab)[https://github.com/ToposInstitute/CatColab] since the beginning of the project. For example, in causal loop diagrams, the edges are decorated by a multiplicative monoid of plus and minus signs. He states

> In fact, within CatColab's mathematical framework, categories grated by a monoidal category are just the models of a simple double theory determined by the monoidal category.

So for a monoidal category $\mathcal{V}$, a category graced by this monoidal category is the same thing as a lax double functor $B(\mathcal{V})^{op} \rightarrow Span$, where $B(\mathcal{V})$ is the delooping double category, aka the monoidal category $\mathcal{V}$ viewed as a double category with a trivial category of objects and arrows. 

The NLab entry on delooping is less than helpful. It seems like this is similar to the construction that a monoidal category can be seen as a single-object bicategory. 

> A bicategory is a (pseudo) double category whose arrow are all identities ... Further examples are in \(Grandis \& Paré, 1999, Sec. 3: “Examples of double and pseudo double categories”\). [https://www.epatters.org/wiki/algebra/double-categories]

I believe that arrows means "tight arrows" and that the "loose arrows" are the monoidal morphisms. But this would be good to check. 

# Sociology of valuation and social accounting

Although there isn't a robust "sociology of measurement" community, there is quite a bit of work on (sociology of valuation)[https://en.wikipedia.org/wiki/Sociology_of_valuation] or "valuation studies" \(I guess this depends on whether an academic wants to work in social science or the humanities\). I'm not sure if this notion of valuation corresponds to the measurement theory notion of valuation (i.e. a map from an "empirical category" to an "informational category"\). There is also the finance understanding of valuation \(e.g. discounted cash flows\).  

A related domain is (social accounting)[https://en.wikipedia.org/wiki/Social_accounting].

Picked one article more or less at random and there could be a fair amount of academic gobledygook in this area. Probably safer to stay in the sociology of measurement, although 

# Motifs and mechanisms

Evan Patterson co-wrote a paper with several authors entitled *A compositional account of motifs, mechanisms and dynamics* [@aduddell:2023:compositional] that looked at the relationships betweens three different system models for biological regulatory networks. The first model was causal loop diagrams, mentioned above. The second model was "petri nets with links", which is a modification of the petri net formalism that allows for "links" between a state variable and a transition variable. These links play a central role in the relationship between causal loop diagrams and the petri net model. The third model is a full dynamical systems model based on a "Lotka-Volterra" system of differential equations. I found this section of the paper tough sledding and I need to revisit this after reading a couple of the prerequisites.

Not only does this paper provide some nice callouts to Eberhart Voit's work, it also provides a very interesting template for thinking about the differences between a specification and a process model. This is a central problem in measurement systems. I also think it could be informative around business process models. The paper cites a year 2000 book on *Business Dynamics* that includes discussion of causal loop diagrams and stock-flow diagrams, but did not include petri nets. 

Could this methodology be extended to activity-based cost accounting? Almost by definition, these are maps between a business process model (aka "activities") to an accounting model (aka "costs") using an implicit or explicit valuation model. Marxists would point to this valuation model as hiding exploitation in the activity model in the accounting model. Ecological economists might view this valuation model as allowing for "primitive accumulation" or "ecological exploitation". But from the viewpoint of measurement systems, the "measuring instrument" plays the key role in mapping a quantitative system property (attribute) to a "value of a property", perhaps using signal transduction. Applying this measurement systems formalism to the ecological case raises all sorts of issues, such as whether there is a system attribute that corresponds to the valuation. The business case will almost certaintly raise even more complex issues (social complexity > natural complexity, all other things being equal). The business case includes ecological valuation issues at the base, but these are usually elided as these are more local models (i.e. specific to a sub-process within a business organization) and I don't know enough to know how they treat primary production.

As I understand in greater detail the accounting world, I anticipate that many of the basic ideas in measurement systems will recur in accounting systems, which strictly speaking are (or should be) an instance of measurement systems. So eventually these two areas of inquiry should be related, if the "transdisciplinary" framework assumption holds. Is there something in common between physical/chemical and business measurement?