---
title: "Viable systems, biological organization, message passing"
author: "Brad Venner"
date: "4/14/2025"
output: html_document
---

# The Unaccountability Machine

I'm reading *The Unaccountability Machine* by Dan Davies [@davies:2024:unaccountability] in the evenings. The project of the book is to apply Stafford Beer's *viable systems theory* to try to understand neoliberal enshitification. An interesting book and project. On thing I like about it that I might emulate is it's short essay form. Ideas are inter-related but there is a blog-like structure to the book that you can imagine being written in week-long pieces.

The five-layer structure of the VSM reminds me a bit of the biological organization model of ? (I don't have this document in Drive. Probably still on the Framework that I was using at Christmas 2024 in KC. Need to get this document and get back to writing this section.)

The notion of a dynamic system of contraints on constraints reminds me of Peirce's notion of induction. If deduction can be considered as the relationship in the constraint system considered statically (necessarily) then induction would be the dynamic system that allows "contradictory" constraints to coexist. Beer's notion of "intelligence" could be related to abduction - the ability to be suprised and attentive to previously "pruned" possibilities. The rough map would be system 3 would be purposive action (secondness of thirdness), system 4 would be creative imagination (firstness of thirdness) and system 5 would be "the wisdom to know the difference", "the habit of changing habits". Beer identified System 5 with autopoesis, which doesn't seem right to me but does point to the notion that a "viable system" has some ability to maintain an identity in the face of environmental adversity.

There's also a potential link to the double-categorical semantics of message passing proposed by Nester [@nester:2023:concurrent]. System 1 would be "computation" and System 2 would be "message passing" (what Nester calls "cornering"). They have done some work extending this model to "protocols" or "session types" in later work. For an "actor" to respond to a "message" could be understood as requiring a "potential constraint" that is only activated upon a receipt of a message. This might link the more logical notions of "loose morphism" in a double category with the more dynamic notions of loose morphisms as "message passing."  

# Towards an improved social knowledge management system

I've made a few attempts to leave my Quarto/Blogdown knowledge management system with limited success. The rise of LLM-enabled editors such as Cursor for code editing may help enable this migration. In addition to developing code to migrate my existing system into some "improved" format, the next system should at least use RAG to interface with a defined knowledge base. One can imagine an "intervenor" crafting a document to submit to a docket. In addition to knowledge of the existing docket information provided by Kessler, the intervenor would like to have access to other knowledge resources, such as published law, scientific papers, previous writings, and so on. As they write their article, the interface should provide "non-destructive" suggestions in the same way that a code editor does. 

A very limited Google search on this idea gave me a blog entry on [Zed AI](https://zed.dev/blog/zed-ai). There is a lot here that I like and it looks like this would be a good place to start. Their Github page calls is "a collaborative platform that is also a code editor". The nice thing about a text-based interface is that it provides an extremely broad system of message passing between agents. The output of a textual process can be almost anything, from a document to a web page to the specifications to create a new actor/agent. Zed has a number of interfaces to different hosted LLMs.

# Notes on the Introduction to the *Handbook of Systems Sciences*

Googled "robert rosen stafford beer" and got this document. Thought I should give it a quick skim. The Handbook looks pretty interesting, and would probably be a more compelling read than the *Handbook of Systems Engineering*, although there's some overlap between the two. The fact that the HSS is over 1400 pages points to the great difficulty faced by any intellectual in the 21st century, since the field of "systems" did not exist until the 20th century. 

Bertalanffy distinguished between systems science, systems technology and systems philosophy. Roughly fits the Aristotelian doing, making, thinking division of knowledge, particularly if social systems are included in systems science. I wonder if "formal systems" would be part of "systems philosophy" (hard to tell what the actual content of this ) 

The rest of the document is an overview of the contents of the handbook and provides summaries of the different sections. Charles Hall wrote one of the chapters, which makes me a little nervous as I'm skeptical of his EROI calculations, although he certainly deserves credit for originating the concept. I do think that EROI is ultimately a systems-level problem, much like surplus value in Marxism. 