---
title: "Thoughts on Mathematical Informatics"
author: "Brad Venner"
date: "2/11/2025"
output: html_document
---

I skimmed the very interesting and provocative "habilitation thesis" by Thomas Seiller called (Mathematical Informatics)[https://theses.hal.science/tel-04616661v2]. The subtitle is "Outline of a mathematical theory of computer science," which does describe the ambition of the project.


The title is provacative given my ambition to write "Semiotics, Dialectics, Systemics", since it implicitly identifies the notions of computation and information. It asserts yet another disciplinary seizure of the interdisciplinary concept of "information" and thus takes a side on the semiotics-systemics conflict (if systemics is oriented around the notion of information, perhaps a claim that is more fairly applied to cybernetics). It might be interesting to revisit (The Knowledge We Have Lost in Information)[nik-khah:2017:knowledge]. Mirowski does not deny the usefulness of the concept of information but does dispute the identification of this concept with the computer.

Seiller did work out a model of "the geometry of interaction" called *interaction graphs* that does include the notion of exponential. So this model may have some important contributions to thinking about Pavlovic's program.

The neglect of obvious contributions by the "applied category theory" school reminded me of the legendary (or apocryphal?) fistfight between Lawvere and Girard. 

Perhaps the most obvious neglect is the theory of actegories, which are the actions of a monoidal category on another category. Seiller proposes the action of a monoid on a "space of configurations" as the basic model of a "computational machine". This seems close to the definition of an actegory if the monoid is treated as monoidal category and the "space of configurations" is another category. But what would the generalization to a monoidal category buy you?

One potential answer is "message passing". The n-Category Cafe article titled (Linear Actegories)[https://golem.ph.utexas.edu/category/2023/09/linear_actegories.html] is a student post reviewing the paper *The Logic of Message Passing* by Cockett and Pastro (CP) that introducted the notion of actegory. This was intended to be a formal theory of concurrency not restricted to computer systems.

> Both of these errors can be avoided through intelligent design of concurrent programs

Aside: is "design" the only way to have good concurrent programs, or is Pitt's notion of SOMAS preferred where some sort of pro-social logic is embedded in agents.

> CP models message passing using an integrated two-tier logic. There is a logic for the messages, which you can think of as coming from the results of sequential computations. Then there is a logic of message passing, built on top of the logic of messages, which deals with the channels of communication.

The terms "message" and "message passing" seem very semiotic. The distinction between the two reminds me of the "dynamic object" (the intended message) and the "immediate object" (the realization of a message that can be sent through a physically-constrained channel).

The "logic for the messages" is modeled as a symmetric monoidal category. The "logic of message passing" is modeled as a linearly distributive category.

The authors point to a limitation in the framework in that the resulting interaction is quite complex. They highlight Nestor's paper (Concurrent process histories and resource transducers)[https://arxiv.org/abs/2010.08233] as providing more simple categorical models for message passing that may be easier to implement.

Nestor's paper is immediately intriguing since it locates message passing in "equipments". This is a different generalization than the actegory framework developed by Capucci and Gavranović, which looks at other "recipient" categories besides linear distributive ones. Anyway, I need to look at both papers. Unfortunately, neither paper refers to the other, so the relations between the frameworks is left to the reader. It's interesting that Capucci has worked in both frameworks, having also done work in categorical systems theory (with a strong double-category flavor). Jules Hedges has continued work in the "actegory" framework.

CG states:

> Indeed, the reason we are interested in actegories in the first place is their effectiveness in capturing the idea of ‘agency’ in categories of systems.

They cite the CP paper above in the first reference. 

Looking on SemanticScholar at citations of (Towards foundations of categorical cybernetics)[https://arxiv.org/abs/2105.06332] gave me the paper (Reformalizing the notion of autonomy as closure through category theory as an arrow-first mathematics)[]. 

So back to categorical models of biological organization! This is one advantage of working in cybernetics, which elides the difference between life and machines from the very beginning. Or allows for commonality in the notion of "governance" for both biology and machines.