---
title: "Compositionality in actor-based informatics"
author: "Brad Venner"
date: "7/09/2025"
output: html_document
---

# Measurement and modeling in/of/for democratic ecosocialism

The title implies both an expansion and contraction of the two projects of "measurement and modeling" and "democratic ecosocialism". I've been working on the former project both at work and in private, with measurement the focus of the work project and modeling the "focus" of the private project. The relationship between measurement and modeling is interesting, and a general hypothesis would be that modeling is what distinguishes measurement from evaluation. In VIM, measurement includes a model as an essential component.

I've thought of my future project with Mycorrhiza as developing agent-based social simulations/models for use in universal public services, beginning with energy and/or broadband. 

I listened to the audiobook version of *Less is More* by Jason Hickel while driving Elena's car to Everett. This book made me rethink my dislike of the degrowth framing. I've thought that degrowth plays too much into the notion of "generalized exchange" under capitalism. It also seemed very unlikely to be able to be implemented by democratic means as it would always be unpopular. For the former concern, Hickel essentially identifies "growthism" with "capitalism", so post-growthism (degrowth) and post-capitalism are synonyms. Although ultimately a positive alternative to capitalism must be developed, it's certaintly valuable to diagnose the problem. 

For the latter concern, Hickel's list of actions in Chapter 5, "Pathways to a Post-Capitalist World" felt like they could be much more popular than the name "degrowth" would imply. Hickel advocates for (universal public services)[https://jasonhickel.org/blog/2023/3/18/universal-public-services] as an essential component of the degrowth agenda. But for the majority of people, universal public services would improve their quality of life and therefore would not be seen as "degrowth". Mamdani's recent victory was based on an "affordability" agenda. The affordability gap has been increasing over many years and universal public services would be a means to address this gap. Mamdami focused on several such services, such as transport (free buses), food (community grocery stores) and housing (rent control). Many of his proposals stop far short of universal public services but are clearly on such a pathway.

# Substitution vs exchange in semiotics

Clara Mattei's paper on economics presents a "subjective" interpretation of Marx that reminds me very much of pragmatism. She says that "exchange is at the basis of any economic system." This made me think of the role of substitution in logic and what Peirce says about the primary role of "illation" in logic and his shift in thinking from algebraic logic, with the principle of substitution of equals for equals, with a more topological approach with the existential graphs. 

Philip Rose argues that illation is a relation of inferential growth.

Jules Hedges wrote a blog entry on modeling of emergence with lax functors. Is this purely a two-categorical notion, or is there a shadow of this relationship in Boolean or Heyting algebras. Hedges continues work with the CyberCat institute, which I have been neglecting due to my general distaste for game theory and preferring the Myers version. Nevertheless, this is probably still important work. There was a link to a paper on "Institutional Modelling" that was not free. I saved the paper in my semanticscholar library under CPSS.

Amineh Ghorbani is the author of *Institutional modelling: adding social backbone to agent-based models*. [@ghorbani:2022:institutional] They are a professor at Delft University of Technology in the Netherlands. Institutional modelling is based on the *institutional grammar*, which is strongly based on Elinor Ostrom's work.

The following definition is taken from Douglas North's book *Institutions, Institutional Change and Economic Peformance*. 
 
> institutions are the rules of the game in a society or, more formally, are the humanly devised constraints that shape human interaction

Rules of interaction can be formalized as multi-party session types. Interactions can also be formalized as games. Categorical semantics have been developed for the latter but perhaps additional work is required for the former. Message passing has been formalized in double categories and more elaborate protocols than simple message passing by Nester. I'm more interested in the latter approach but I shouldn't make a premature judgement as to the "best" approach yet.

An example of an institutional statement is given as:

> Drivers are forbidden to drive their passenger cars with speeds higher than 130 km/h when on the highway or else they will be fined.

Thinking of roads as a common-pool resource, this fits Ostrom's framing of institutions.

In Frega's social ontology, the "institution" is the highest level and there is a lower level of "interaction". Be good to review this paper after finishing this review.

The six components of the institutional grammar are below. They use the mnemonic ABDICO. The letter in the component that corresponds to the component are in bold.

1. *A*ttribute: the person to whom the institutional statement applies. This would be equivalent to the scope of a method. Is there a simple note that I could develop to apply the institutional grammar to analytical methods?

2. *D*eontic type: prohibition | obligation | permission. This imagines institutions as "stipulated rules". Are all institutions stipulated? In real institutions there is a large amount of "customary law", "tacit knowledge", etc tha tis not formalized.

3. A*i*m: the outcome of the statement. Is this the realized behavior or the intended behavior? I.e. specification or process? In the example, "drive with speeds lower than 130 km/h".

4. O*b*ject: the receiver of the action. Example is "passenger car". This one is less intuitive. "Driver of a passenger car" is an alienable role an agent may assume. Does every institution always involve an object? How are object and attribute distinguished?

5. *C*ondition: the situation in which the institution holds (when and where)? In the example, "in the highway". I'm not sure there is always a natural distinction between attribute, object and condition. Isn't "while driving a passenger car" a "when" condition?

6. *O*r else: the consequence of not following a rule. In the example, "they will be fined"

Not every institution has every subtype. Several "sub-institutions" are explicitly identified. Objects are always optional

1. Rules (AICDO) have all components except objects. Are rules always "stipulated law"? Later in the paper it is assumed that are rules are captured in documents, so yes.

2. Norms (AICD) to not have an explicit "or else" component. Various consequences may be pursued by other agents.

3. Shared strategies (AIC) do not have an "or else" or "deontic type" component. Closest to the notion of "shared habit".

This focus on the role of institutions in shaping behaviors of actors reminded me of Spivak's topos type theory and behavioral mereology. Another thing to look at.

Most directly relevant is Baez's agent-based modeling framework. Seems like institutions would be higher-order structures on the behavioral colimits. Would such analysis move this into a triple category?